import { QuizLevel } from '../quizTypes';

export const level8: QuizLevel = {
    id: 8,
    titleAr: 'التاريخ الإسلامي',
    titleEn: 'Islamic History',
    description: 'أحداث مهمة في التاريخ الإسلامي والسيرة النبوية',
    descriptionEn: 'Important events in Islamic history and Seerah',
    requiredScore: 70,
    icon: '📜',
    questions: [
        // Seerah (Life of Prophet Muhammad ﷺ)
        {
            id: 1,
            question: 'في أي عام ولد النبي محمد ﷺ؟',
            questionEn: 'In which year was Prophet Muhammad ﷺ born?',
            options: ['عام الفيل (571 م)', 'عام الحزن', 'عام الهجرة', 'عام الوفود'],
            optionsEn: ['Year of the Elephant (571 CE)', 'Year of Sorrow', 'Year of Migration', 'Year of Delegations'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'ولد النبي ﷺ في عام الفيل بمكة المكرمة.',
            explanationEn: 'The Prophet ﷺ was born in the Year of the Elephant in Mecca.'
        },
        {
            id: 2,
            question: 'ما اسم والد النبي محمد ﷺ؟',
            questionEn: 'What is the name of Prophet Muhammad\'s ﷺ father?',
            options: ['عبد الله', 'عبد المطلب', 'أبو طالب', 'حمزة'],
            optionsEn: ['Abdullah', 'Abdul-Muttalib', 'Abu Talib', 'Hamza'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'والده هو عبد الله بن عبد المطلب.',
            explanationEn: 'His father is Abdullah bin Abdul-Muttalib.'
        },
        {
            id: 3,
            question: 'من هي مرضعة النبي ﷺ؟',
            questionEn: 'Who was the wet nurse of the Prophet ﷺ?',
            options: ['حليمة السعدية', 'آمنة بنت وهب', 'خديجة', 'فاطمة'],
            optionsEn: ['Halima As-Sa\'diyah', 'Aminah bint Wahb', 'Khadija', 'Fatima'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'أرضعته حليمة السعدية في بادية بني سعد.',
            explanationEn: 'Halima As-Sa\'diyah nursed him in the desert of Bani Sa\'d.'
        },
        {
            id: 4,
            question: 'كم كان عمر النبي ﷺ عندما نزل عليه الوحي؟',
            questionEn: 'How old was the Prophet ﷺ when revelation came to him?',
            options: ['40 سنة', '25 سنة', '63 سنة', '50 سنة'],
            optionsEn: ['40 years', '25 years', '63 years', '50 years'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'بعث النبي ﷺ وهو ابن أربعين سنة.',
            explanationEn: 'The Prophet ﷺ was sent (as a Messenger) when he was forty years old.'
        },
        {
            id: 5,
            question: 'أين نزل الوحي أول مرة؟',
            questionEn: 'Where did revelation come down for the first time?',
            options: ['في غار حراء', 'في غار ثور', 'في الكعبة', 'في المدينة'],
            optionsEn: ['In Cave Hira', 'In Cave Thawr', 'In Kaaba', 'In Medina'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'نزل عليه جبريل عليه السلام في غار حراء.',
            explanationEn: 'Jibril (AS) came down to him in Cave Hira.'
        },
        {
            id: 6,
            question: 'ما هي أول آية نزلت من القرآن؟',
            questionEn: 'What was the first verse revealed from the Quran?',
            options: ['اقرأ باسم ربك الذي خلق', 'الحمد لله رب العالمين', 'يا أيها المدثر', 'قل هو الله أحد'],
            optionsEn: ['Read in the name of your Lord who created', 'Alhamdulillah', 'O you who covers himself', 'Say He is Allah One'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'أول ما نزل صدر سورة العلق: اقرأ باسم ربك الذي خلق.',
            explanationEn: 'The first revelation was the beginning of Surah Al-Alaq.'
        },
        {
            id: 7,
            question: 'من هو أول من آمن من الرجال؟',
            questionEn: 'Who was the first man to believe?',
            options: ['أبو بكر الصديق', 'علي بن أبي طالب', 'عمر بن الخطاب', 'عثمان بن عفان'],
            optionsEn: ['Abu Bakr As-Siddiq', 'Ali bin Abi Talib', 'Umar bin Al-Khattab', 'Uthman bin Affan'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'أول من آمن من الرجال الأحرار هو أبو بكر الصديق رضي الله عنه.',
            explanationEn: 'The first free man to believe was Abu Bakr As-Siddiq (RA).'
        },
        {
            id: 8,
            question: 'من هو أول من آمن من الصبيان؟',
            questionEn: 'Who was the first boy to believe?',
            options: ['علي بن أبي طالب', 'زيد بن حارثة', 'عبد الله بن عمر', 'الحسن'],
            optionsEn: ['Ali bin Abi Talib', 'Zaid bin Harithah', 'Abdullah bin Umar', 'Al-Hasan'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'أول من آمن من الصبيان هو علي بن أبي طالب رضي الله عنه.',
            explanationEn: 'The first boy to believe was Ali bin Abi Talib (RA).'
        },
        {
            id: 9,
            question: 'ما هي الهجرة الأولى للمسلمين؟',
            questionEn: 'What was the first migration for Muslims?',
            options: ['الهجرة إلى الحبشة', 'الهجرة إلى المدينة', 'الهجرة إلى الطائف', 'الهجرة إلى اليمن'],
            optionsEn: ['Migration to Abyssinia', 'Migration to Medina', 'Migration to Taif', 'Migration to Yemen'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'هاجر المسلمون أولاً إلى الحبشة فراراً بدينهم.',
            explanationEn: 'Muslims first migrated to Abyssinia fleeing with their religion.'
        },
        {
            id: 10,
            question: 'من هو الملك العادل الذي هاجر إليه المسلمون في الحبشة؟',
            questionEn: 'Who is the just king the Muslims migrated to in Abyssinia?',
            options: ['النجاشي', 'هرقل', 'كسرى', 'المقوقس'],
            optionsEn: ['Negus (An-Najashi)', 'Heraclius', 'Chosroes', 'Muqawqis'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'النجاشي ملك الحبشة كان ملكاً عادلاً لا يظلم عنده أحد.',
            explanationEn: 'Negus, King of Abyssinia, was a just king under whom no one was wronged.'
        },
        {
            id: 11,
            question: 'ما هو عام الحزن؟',
            questionEn: 'What is the Year of Sorrow?',
            options: ['العام الذي توفيت فيه خديجة وأبو طالب', 'عام الهجرة', 'عام أحد', 'عام الفيل'],
            optionsEn: ['Year Khadija and Abu Talib died', 'Year of Migration', 'Year of Uhud', 'Year of Elephant'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'سمي بذلك لوفاة زوجة النبي خديجة وعمه أبي طالب.',
            explanationEn: 'It was named so because of the death of the Prophet\'s wife Khadija and his uncle Abu Talib.'
        },
        {
            id: 12,
            question: 'ما هي رحلة الإسراء والمعراج؟',
            questionEn: 'What is the journey of Isra and Mi\'raj?',
            options: ['رحلة ليلية من مكة للقدس ثم للسماء', 'رحلة للمدينة', 'رحلة للطائف', 'رحلة تجارية'],
            optionsEn: ['Night journey from Mecca to Jerusalem then Heaven', 'Journey to Medina', 'Journey to Taif', 'Trade journey'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'أسرى الله بعبده ليلاً من المسجد الحرام إلى المسجد الأقصى ثم عرج به للسماء.',
            explanationEn: 'Allah took His servant by night from the Sacred Mosque to the Farthest Mosque, then ascended him to Heaven.'
        },
        {
            id: 13,
            question: 'ماذا فرض الله في ليلة الإسراء والمعراج؟',
            questionEn: 'What did Allah obligate on the night of Isra and Mi\'raj?',
            options: ['الصلوات الخمس', 'الصيام', 'الحج', 'الزكاة'],
            optionsEn: ['The five daily prayers', 'Fasting', 'Hajj', 'Zakat'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'فرضت الصلاة خمسين ثم خففت إلى خمس.',
            explanationEn: 'Prayer was obligated as fifty then reduced to five.'
        },
        {
            id: 14,
            question: 'من رافق النبي ﷺ في الهجرة إلى المدينة؟',
            questionEn: 'Who accompanied the Prophet ﷺ in the migration to Medina?',
            options: ['أبو بكر الصديق', 'علي بن أبي طالب', 'عمر بن الخطاب', 'عثمان بن عفان'],
            optionsEn: ['Abu Bakr As-Siddiq', 'Ali bin Abi Talib', 'Umar bin Al-Khattab', 'Uthman bin Affan'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'إذ يقول لصاحبه لا تحزن إن الله معنا.',
            explanationEn: 'When he said to his companion, "Do not grieve; indeed Allah is with us."'
        },
        {
            id: 15,
            question: 'أين اختبأ النبي ﷺ وأبو بكر أثناء الهجرة؟',
            questionEn: 'Where did the Prophet ﷺ and Abu Bakr hide during migration?',
            options: ['في غار ثور', 'في غار حراء', 'في الكعبة', 'في دار الأرقم'],
            optionsEn: ['In Cave Thawr', 'In Cave Hira', 'In Kaaba', 'In Dar Al-Arqam'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'مكثا في غار ثور ثلاث ليال.',
            explanationEn: 'They stayed in Cave Thawr for three nights.'
        },
        // Battles (Ghazwat)
        {
            id: 16,
            question: 'ما هي أول غزوة كبرى في الإسلام؟',
            questionEn: 'What was the first major battle in Islam?',
            options: ['غزوة بدر', 'غزوة أحد', 'غزوة الخندق', 'غزوة تبوك'],
            optionsEn: ['Battle of Badr', 'Battle of Uhud', 'Battle of Trench', 'Battle of Tabuk'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'وقعت غزوة بدر الكبرى في 17 رمضان سنة 2 هـ.',
            explanationEn: 'The Great Battle of Badr took place on 17 Ramadan, 2 AH.'
        },
        {
            id: 17,
            question: 'كم كان عدد المسلمين في غزوة بدر؟',
            questionEn: 'How many Muslims were in the Battle of Badr?',
            options: ['313 رجلاً', '1000 رجل', '3000 رجل', '10000 رجل'],
            optionsEn: ['313 men', '1000 men', '3000 men', '10000 men'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'كان عدد المسلمين قليلاً (313) ونصرهم الله على المشركين (1000).',
            explanationEn: 'The number of Muslims was small (313) and Allah granted them victory over the polytheists (1000).'
        },
        {
            id: 18,
            question: 'ماذا حدث في غزوة أحد؟',
            questionEn: 'What happened in the Battle of Uhud?',
            options: ['خالف الرماة أمر النبي ﷺ فانقلب النصر لهزيمة', 'انتصر المسلمون', 'لم يحدث قتال', 'استسلم المشركون'],
            optionsEn: ['Archers disobeyed Prophet ﷺ, victory turned to defeat', 'Muslims won', 'No fighting', 'Polytheists surrendered'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'نزل الرماة من الجبل لجمع الغنائم فالتف خالد بن الوليد عليهم.',
            explanationEn: 'Archers came down from the mountain for spoils, so Khalid bin Walid flanked them.'
        },
        {
            id: 19,
            question: 'من هو الصحابي الذي استشهد في أحد ولقب بسيد الشهداء؟',
            questionEn: 'Which Companion was martyred in Uhud and called Master of Martyrs?',
            options: ['حمزة بن عبد المطلب', 'مصعب بن عمير', 'جعفر الطيار', 'زيد بن حارثة'],
            optionsEn: ['Hamza bin Abdul-Muttalib', 'Musab bin Umair', 'Ja\'far At-Tayyar', 'Zaid bin Harithah'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'حمزة عم النبي ﷺ هو سيد الشهداء.',
            explanationEn: 'Hamza, the Prophet\'s uncle, is the Master of Martyrs.'
        },
        {
            id: 20,
            question: 'ما هي الغزوة التي حفر فيها المسلمون خندقاً؟',
            questionEn: 'In which battle did Muslims dig a trench?',
            options: ['غزوة الأحزاب (الخندق)', 'غزوة خيبر', 'غزوة حنين', 'غزوة مؤتة'],
            optionsEn: ['Battle of Ahzab (Trench)', 'Battle of Khaybar', 'Battle of Hunayn', 'Battle of Mu\'tah'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'أشار سلمان الفارسي بحفر الخندق لحماية المدينة.',
            explanationEn: 'Salman Al-Farsi suggested digging the trench to protect Medina.'
        },
        {
            id: 21,
            question: 'متى كان فتح مكة؟',
            questionEn: 'When was the Conquest of Mecca?',
            options: ['في السنة 8 هـ', 'في السنة 6 هـ', 'في السنة 10 هـ', 'في السنة 2 هـ'],
            optionsEn: ['Year 8 AH', 'Year 6 AH', 'Year 10 AH', 'Year 2 AH'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'فتح الله مكة لنبيه في رمضان سنة 8 هجرية.',
            explanationEn: 'Allah opened Mecca for His Prophet in Ramadan, 8 AH.'
        },
        {
            id: 22,
            question: 'ماذا قال النبي ﷺ لأهل مكة يوم الفتح؟',
            questionEn: 'What did the Prophet ﷺ say to people of Mecca on Conquest day?',
            options: ['اذهبوا فأنتم الطلقاء', 'سأقتلكم جميعاً', 'ادفعوا الجزية', 'اخرجوا منها'],
            optionsEn: ['Go, for you are free', 'I will kill you all', 'Pay Jizya', 'Get out of it'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'عفا عنهم وقال: اذهبوا فأنتم الطلقاء.',
            explanationEn: 'He forgave them and said: "Go, for you are free."'
        },
        // Caliphs (Khulafa Rashideen)
        {
            id: 23,
            question: 'من هو أول الخلفاء الراشدين؟',
            questionEn: 'Who is the first Rightly Guided Caliph?',
            options: ['أبو بكر الصديق', 'عمر بن الخطاب', 'عثمان بن عفان', 'علي بن أبي طالب'],
            optionsEn: ['Abu Bakr As-Siddiq', 'Umar bin Al-Khattab', 'Uthman bin Affan', 'Ali bin Abi Talib'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'تولى الخلافة بعد وفاة النبي ﷺ.',
            explanationEn: 'He took the Caliphate after the Prophet\'s ﷺ death.'
        },
        {
            id: 24,
            question: 'بماذا لقب عمر بن الخطاب؟',
            questionEn: 'What was the title of Umar bin Al-Khattab?',
            options: ['الفاروق', 'الصديق', 'ذو النورين', 'سيف الله'],
            optionsEn: ['Al-Farooq', 'As-Siddiq', 'Dhun-Nurayn', 'Sword of Allah'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'لقبه النبي ﷺ بالفاروق لأنه فرق بين الحق والباطل.',
            explanationEn: 'The Prophet ﷺ titled him Al-Farooq because he distinguished between truth and falsehood.'
        },
        {
            id: 25,
            question: 'من هو الخليفة الذي جمع القرآن في مصحف واحد؟',
            questionEn: 'Who is the Caliph who compiled Quran in one Mushaf?',
            options: ['عثمان بن عفان', 'أبو بكر', 'عمر', 'علي'],
            optionsEn: ['Uthman bin Affan', 'Abu Bakr', 'Umar', 'Ali'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'جمع عثمان الناس على مصحف واحد درءاً للفتنة.',
            explanationEn: 'Uthman united people on one Mushaf to prevent fitnah.'
        },
        {
            id: 26,
            question: 'من هو الخليفة الرابع وابن عم النبي ﷺ؟',
            questionEn: 'Who is the fourth Caliph and Prophet\'s cousin?',
            options: ['علي بن أبي طالب', 'عثمان', 'عمر', 'أبو بكر'],
            optionsEn: ['Ali bin Abi Talib', 'Uthman', 'Umar', 'Abu Bakr'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'هو علي بن أبي طالب رضي الله عنه.',
            explanationEn: 'He is Ali bin Abi Talib (RA).'
        },
        {
            id: 27,
            question: 'كم استمرت الخلافة الراشدة؟',
            questionEn: 'How long did the Rashidun Caliphate last?',
            options: ['30 سنة', '40 سنة', '10 سنوات', '100 سنة'],
            optionsEn: ['30 years', '40 years', '10 years', '100 years'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'قال النبي ﷺ: الخلافة في أمتي ثلاثون سنة.',
            explanationEn: 'The Prophet ﷺ said: "The Caliphate in my Ummah is thirty years."'
        },
        // Other Events & Figures
        {
            id: 28,
            question: 'من هو سيف الله المسلول؟',
            questionEn: 'Who is the Drawn Sword of Allah?',
            options: ['خالد بن الوليد', 'أبو عبيدة', 'سعد بن أبي وقاص', 'حمزة'],
            optionsEn: ['Khalid bin Walid', 'Abu Ubaidah', 'Saad bin Abi Waqqas', 'Hamza'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'لقبه النبي ﷺ بسيف الله المسلول لشجاعته.',
            explanationEn: 'The Prophet ﷺ titled him the Drawn Sword of Allah for his bravery.'
        },
        {
            id: 29,
            question: 'من هو مؤذن الرسول ﷺ؟',
            questionEn: 'Who is the Muazzin of the Messenger ﷺ?',
            options: ['بلال بن رباح', 'عبد الله بن أم مكتوم', 'أبو محذورة', 'سعد'],
            optionsEn: ['Bilal bin Rabah', 'Abdullah bin Umm Maktum', 'Abu Mahdhurah', 'Saad'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'بلال هو أول من أذن في الإسلام.',
            explanationEn: 'Bilal was the first to call Adhan in Islam.'
        },
        {
            id: 30,
            question: 'ما هي حجة الوداع؟',
            questionEn: 'What is the Farewell Pilgrimage?',
            options: ['الحجة الوحيدة التي حجها النبي ﷺ', 'أول حجة', 'آخر غزوة', 'عمرة'],
            optionsEn: ['The only Hajj Prophet ﷺ performed', 'First Hajj', 'Last Battle', 'Umrah'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'حج النبي ﷺ حجة واحدة ودع فيها الناس.',
            explanationEn: 'The Prophet ﷺ performed one Hajj in which he bid farewell to the people.'
        },
        {
            id: 31,
            question: 'متى توفي النبي ﷺ؟',
            questionEn: 'When did the Prophet ﷺ die?',
            options: ['12 ربيع الأول سنة 11 هـ', '1 رمضان', '10 ذو الحجة', '1 محرم'],
            optionsEn: ['12 Rabi Al-Awwal 11 AH', '1 Ramadan', '10 Dhul-Hijjah', '1 Muharram'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'توفي يوم الاثنين 12 ربيع الأول سنة 11 هجرية.',
            explanationEn: 'He died on Monday, 12 Rabi Al-Awwal, 11 AH.'
        },
        {
            id: 32,
            question: 'أين دفن النبي ﷺ؟',
            questionEn: 'Where was the Prophet ﷺ buried?',
            options: ['في حجرة عائشة بالمدينة', 'في مكة', 'في البقيع', 'في القدس'],
            optionsEn: ['In Aisha\'s room in Medina', 'In Mecca', 'In Baqi', 'In Jerusalem'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'دفن حيث قبض في حجرة زوجته عائشة رضي الله عنها.',
            explanationEn: 'He was buried where he died in the room of his wife Aisha (RA).'
        },
        {
            id: 33,
            question: 'من هن أمهات المؤمنين؟',
            questionEn: 'Who are the Mothers of the Believers?',
            options: ['زوجات النبي ﷺ', 'بنات النبي', 'الصحابياب', 'نساء الأنصار'],
            optionsEn: ['Wives of the Prophet ﷺ', 'Daughters of Prophet', 'Female Companions', 'Women of Ansar'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'وأزواجه أمهاتهم.',
            explanationEn: 'And his wives are their mothers.'
        },
        {
            id: 34,
            question: 'من هي أول زوجات النبي ﷺ؟',
            questionEn: 'Who was the first wife of the Prophet ﷺ?',
            options: ['خديجة بنت خويلد', 'عائشة', 'سودة', 'حفصة'],
            optionsEn: ['Khadija bint Khuwaylid', 'Aisha', 'Sawda', 'Hafsa'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'تزوجها قبل النبوة ولم يتزوج عليها حتى ماتت.',
            explanationEn: 'He married her before Prophethood and did not marry anyone else until she died.'
        },
        {
            id: 35,
            question: 'من هي الزوجة التي برأها الله من فوق سبع سماوات؟',
            questionEn: 'Who is the wife Allah exonerated from above seven heavens?',
            options: ['عائشة بنت أبي بكر', 'حفصة', 'زينب', 'أم سلمة'],
            optionsEn: ['Aisha bint Abu Bakr', 'Hafsa', 'Zainab', 'Umm Salamah'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'نزلت آيات سورة النور في براءتها (حادثة الإفك).',
            explanationEn: 'Verses of Surah An-Nur were revealed for her exoneration (Incident of Ifk).'
        },
        // More History
        {
            id: 36,
            question: 'ما هي عاصمة الخلافة الأموية؟',
            questionEn: 'What was the capital of the Umayyad Caliphate?',
            options: ['دمشق', 'بغداد', 'المدينة', 'القاهرة'],
            optionsEn: ['Damascus', 'Baghdad', 'Medina', 'Cairo'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'اتخذ معاوية بن أبي سفيان دمشق عاصمة له.',
            explanationEn: 'Muawiyah bin Abi Sufyan made Damascus his capital.'
        },
        {
            id: 37,
            question: 'ما هي عاصمة الخلافة العباسية؟',
            questionEn: 'What was the capital of the Abbasid Caliphate?',
            options: ['بغداد', 'دمشق', 'الكوفة', 'مكة'],
            optionsEn: ['Baghdad', 'Damascus', 'Kufa', 'Mecca'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'بنى أبو جعفر المنصور بغداد واتخذها عاصمة.',
            explanationEn: 'Abu Ja\'far Al-Mansur built Baghdad and made it the capital.'
        },
        {
            id: 38,
            question: 'من هو القائد الذي فتح الأندلس؟',
            questionEn: 'Who is the commander who conquered Andalusia?',
            options: ['طارق بن زياد', 'صلاح الدين', 'خالد بن الوليد', 'عمرو بن العاص'],
            optionsEn: ['Tariq bin Ziyad', 'Salahuddin', 'Khalid bin Walid', 'Amr bin Al-Aas'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'عبر المضيق وفتح الأندلس سنة 92 هـ.',
            explanationEn: 'He crossed the strait and conquered Andalusia in 92 AH.'
        },
        {
            id: 39,
            question: 'من هو محرر القدس من الصليبيين؟',
            questionEn: 'Who liberated Jerusalem from Crusaders?',
            options: ['صلاح الدين الأيوبي', 'نور الدين زنكي', 'الظاهر بيبرس', 'قطز'],
            optionsEn: ['Salahuddin Al-Ayyubi', 'Nuruddin Zanki', 'Baibars', 'Qutuz'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'حررها بعد معركة حطين سنة 583 هـ.',
            explanationEn: 'He liberated it after the Battle of Hattin in 583 AH.'
        },
        {
            id: 40,
            question: 'ما هي المعركة التي أوقفت التتار (المغول)؟',
            questionEn: 'What battle stopped the Tatars (Mongols)?',
            options: ['عين جالوت', 'حطين', 'القادسية', 'اليرموك'],
            optionsEn: ['Ain Jalut', 'Hattin', 'Qadisiyah', 'Yarmouk'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'انتصر المسلمون بقيادة قطز في عين جالوت.',
            explanationEn: 'Muslims led by Qutuz won at Ain Jalut.'
        },
        {
            id: 41,
            question: 'من هو أول مولود للمهاجرين في المدينة؟',
            questionEn: 'Who was the first born of the Muhajirun in Medina?',
            options: ['عبد الله بن الزبير', 'النعمان بن بشير', 'الحسن', 'الحسين'],
            optionsEn: ['Abdullah bin Az-Zubair', 'An-Nu\'man bin Bashir', 'Al-Hasan', 'Al-Hussein'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'فرح المسلمون بولادته وكبروا.',
            explanationEn: 'Muslims rejoiced at his birth and said Takbir.'
        },
        {
            id: 42,
            question: 'من هو أول مولود للأنصار في المدينة؟',
            questionEn: 'Who was the first born of the Ansar in Medina?',
            options: ['النعمان بن بشير', 'عبد الله بن الزبير', 'سعد بن معاذ', 'زيد'],
            optionsEn: ['An-Nu\'man bin Bashir', 'Abdullah bin Az-Zubair', 'Saad bin Mu\'adh', 'Zaid'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'هو النعمان بن بشير رضي الله عنه.',
            explanationEn: 'He is An-Nu\'man bin Bashir (RA).'
        },
        {
            id: 43,
            question: 'ما هو أول مسجد بني في الإسلام؟',
            questionEn: 'What is the first mosque built in Islam?',
            options: ['مسجد قباء', 'المسجد النبوي', 'المسجد الحرام', 'مسجد الجمعة'],
            optionsEn: ['Quba Mosque', 'Prophet\'s Mosque', 'Sacred Mosque', 'Jumu\'ah Mosque'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'أسس النبي ﷺ مسجد قباء أول وصوله للمدينة.',
            explanationEn: 'The Prophet ﷺ founded Quba Mosque upon his first arrival in Medina.'
        },
        {
            id: 44,
            question: 'ما فضل الصلاة في مسجد قباء؟',
            questionEn: 'What is the virtue of praying in Quba Mosque?',
            options: ['كأجر عمرة', 'كأجر حجة', 'بألف صلاة', 'بمائة صلاة'],
            optionsEn: ['Like reward of Umrah', 'Like reward of Hajj', '1000 prayers', '100 prayers'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'من تطهر في بيته ثم أتى مسجد قباء فصلى فيه صلاة كان له كأجر عمرة.',
            explanationEn: 'Whoever purifies himself in his house then comes to Quba Mosque and prays in it, he will have a reward like Umrah.'
        },
        {
            id: 45,
            question: 'كم تعادل الصلاة في المسجد الحرام؟',
            questionEn: 'How much is prayer in the Sacred Mosque worth?',
            options: ['100,000 صلاة', '1,000 صلاة', '500 صلاة', '50 صلاة'],
            optionsEn: ['100,000 prayers', '1,000 prayers', '500 prayers', '50 prayers'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'صلاة في المسجد الحرام بمائة ألف صلاة.',
            explanationEn: 'A prayer in the Sacred Mosque is worth one hundred thousand prayers.'
        },
        {
            id: 46,
            question: 'كم تعادل الصلاة في المسجد النبوي؟',
            questionEn: 'How much is prayer in the Prophet\'s Mosque worth?',
            options: ['1,000 صلاة', '100,000 صلاة', '500 صلاة', '100 صلاة'],
            optionsEn: ['1,000 prayers', '100,000 prayers', '500 prayers', '100 prayers'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'صلاة في مسجدي هذا خير من ألف صلاة فيما سواه إلا المسجد الحرام.',
            explanationEn: 'A prayer in this mosque of mine is better than a thousand prayers elsewhere except the Sacred Mosque.'
        },
        {
            id: 47,
            question: 'كم تعادل الصلاة في المسجد الأقصى؟',
            questionEn: 'How much is prayer in Al-Aqsa Mosque worth?',
            options: ['500 صلاة (أو 250)', '1,000 صلاة', '100,000 صلاة', '50 صلاة'],
            optionsEn: ['500 prayers (or 250)', '1,000 prayers', '100,000 prayers', '50 prayers'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'ورد في الحديث أنها بخمسمائة صلاة (وفي روايات 250).',
            explanationEn: 'It is mentioned in Hadith that it is worth 500 prayers (and in some narrations 250).'
        },
        {
            id: 48,
            question: 'من هو الصحابي الذي اهتز له عرش الرحمن عند موته؟',
            questionEn: 'Which Companion did the Throne of the Most Merciful shake for upon his death?',
            options: ['سعد بن معاذ', 'سعد بن أبي وقاص', 'حمزة', 'عمر'],
            optionsEn: ['Saad bin Mu\'adh', 'Saad bin Abi Waqqas', 'Hamza', 'Umar'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'اهتز العرش لموت سعد بن معاذ رضي الله عنه.',
            explanationEn: 'The Throne shook for the death of Saad bin Mu\'adh (RA).'
        },
        {
            id: 49,
            question: 'من هو الصحابي الذي تستحي منه الملائكة؟',
            questionEn: 'Which Companion do the angels feel shy of?',
            options: ['عثمان بن عفان', 'أبو بكر', 'عمر', 'علي'],
            optionsEn: ['Uthman bin Affan', 'Abu Bakr', 'Umar', 'Ali'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'قال النبي ﷺ: ألا أستحي من رجل تستحي منه الملائكة.',
            explanationEn: 'The Prophet ﷺ said: "Should I not be shy of a man from whom the angels are shy?"'
        },
        {
            id: 50,
            question: 'من هو أمين هذه الأمة؟',
            questionEn: 'Who is the Trustworthy One (Amin) of this Ummah?',
            options: ['أبو عبيدة بن الجراح', 'أبو بكر', 'عمر', 'علي'],
            optionsEn: ['Abu Ubaidah bin Al-Jarrah', 'Abu Bakr', 'Umar', 'Ali'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'لكل أمة أمين وأمين هذه الأمة أبو عبيدة.',
            explanationEn: 'Every nation has a trustworthy one, and the trustworthy one of this Ummah is Abu Ubaidah.'
        },
        {
            id: 51,
            question: 'من هو حواري رسول الله ﷺ؟',
            questionEn: 'Who is the Disciple (Hawari) of the Messenger of Allah ﷺ?',
            options: ['الزبير بن العوام', 'طلحة', 'سعد', 'علي'],
            optionsEn: ['Az-Zubair bin Al-Awwam', 'Talha', 'Saad', 'Ali'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'إن لكل نبي حوارياً وحواري الزبير.',
            explanationEn: 'Indeed, every Prophet has a disciple, and my disciple is Az-Zubair.'
        },
        {
            id: 52,
            question: 'من هو ترجمان القرآن؟',
            questionEn: 'Who is the Interpreter of the Quran?',
            options: ['عبد الله بن عباس', 'عبد الله بن مسعود', 'أبي بن كعب', 'زيد بن ثابت'],
            optionsEn: ['Abdullah bin Abbas', 'Abdullah bin Masud', 'Ubay bin Kaab', 'Zaid bin Thabit'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'دعا له النبي ﷺ بالفقه في الدين وتعليم التأويل.',
            explanationEn: 'The Prophet ﷺ prayed for him to have understanding in religion and knowledge of interpretation.'
        },
        {
            id: 53,
            question: 'من هو الصحابي الذي أشار بجمع القرآن؟',
            questionEn: 'Which Companion suggested compiling the Quran?',
            options: ['عمر بن الخطاب', 'أبو بكر', 'عثمان', 'علي'],
            optionsEn: ['Umar bin Al-Khattab', 'Abu Bakr', 'Uthman', 'Ali'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'أشار على أبي بكر بجمع القرآن بعد استشهاد القراء في اليمامة.',
            explanationEn: 'He suggested to Abu Bakr to compile the Quran after the reciters were martyred in Yamama.'
        },
        {
            id: 54,
            question: 'من كلف بجمع القرآن في عهد أبي بكر وعثمان؟',
            questionEn: 'Who was tasked with compiling the Quran during Abu Bakr and Uthman\'s time?',
            options: ['زيد بن ثابت', 'علي', 'معاذ', 'أبي'],
            optionsEn: ['Zaid bin Thabit', 'Ali', 'Mu\'adh', 'Ubay'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'كان من كتاب الوحي وشهد العرضة الأخيرة.',
            explanationEn: 'He was one of the scribes of revelation and witnessed the final review.'
        },
        {
            id: 55,
            question: 'ما هي الغزوة التي كسرت فيها رباعية النبي ﷺ؟',
            questionEn: 'In which battle was the Prophet\'s ﷺ tooth broken?',
            options: ['غزوة أحد', 'غزوة بدر', 'غزوة حنين', 'غزوة الخندق'],
            optionsEn: ['Battle of Uhud', 'Battle of Badr', 'Battle of Hunayn', 'Battle of Trench'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'أصيب النبي ﷺ في وجهه وكسرت رباعيته في أحد.',
            explanationEn: 'The Prophet ﷺ was injured in his face and his tooth was broken in Uhud.'
        },
        {
            id: 56,
            question: 'من هو قائد جيش المسلمين في القادسية؟',
            questionEn: 'Who was the commander of the Muslim army in Qadisiyah?',
            options: ['سعد بن أبي وقاص', 'خالد بن الوليد', 'أبو عبيدة', 'المثنى'],
            optionsEn: ['Saad bin Abi Waqqas', 'Khalid bin Walid', 'Abu Ubaidah', 'Al-Muthanna'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'انتصر سعد على الفرس في معركة القادسية.',
            explanationEn: 'Saad defeated the Persians in the Battle of Qadisiyah.'
        },
        {
            id: 57,
            question: 'من هو قائد جيش المسلمين في اليرموك؟',
            questionEn: 'Who was the commander of the Muslim army in Yarmouk?',
            options: ['خالد بن الوليد (ثم أبو عبيدة)', 'سعد', 'عمرو بن العاص', 'شرحبيل'],
            optionsEn: ['Khalid bin Walid (then Abu Ubaidah)', 'Saad', 'Amr bin Al-Aas', 'Shurahbil'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'كانت معركة فاصلة ضد الروم.',
            explanationEn: 'It was a decisive battle against the Romans.'
        },
        {
            id: 58,
            question: 'من هو فاتح مصر؟',
            questionEn: 'Who is the conqueror of Egypt?',
            options: ['عمرو بن العاص', 'خالد بن الوليد', 'سعد', 'عقبة بن نافع'],
            optionsEn: ['Amr bin Al-Aas', 'Khalid bin Walid', 'Saad', 'Uqba bin Nafi'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'فتح مصر في عهد عمر بن الخطاب.',
            explanationEn: 'He conquered Egypt during the reign of Umar bin Al-Khattab.'
        },
        {
            id: 59,
            question: 'من هو مؤسس الدولة الأموية؟',
            questionEn: 'Who is the founder of the Umayyad State?',
            options: ['معاوية بن أبي سفيان', 'يزيد', 'عبد الملك', 'مروان'],
            optionsEn: ['Muawiyah bin Abi Sufyan', 'Yazid', 'Abdul-Malik', 'Marwan'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'أسس الدولة الأموية عام 41 هـ (عام الجماعة).',
            explanationEn: 'He founded the Umayyad State in 41 AH (Year of Unity).'
        },
        {
            id: 60,
            question: 'من هو خامس الخلفاء الراشدين (مجازاً) لعدله؟',
            questionEn: 'Who is called the fifth Rightly Guided Caliph (figuratively) for his justice?',
            options: ['عمر بن عبد العزيز', 'معاوية', 'هارون الرشيد', 'المأمون'],
            optionsEn: ['Umar bin Abdul-Aziz', 'Muawiyah', 'Harun Ar-Rashid', 'Al-Ma\'mun'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'اشتهر بالعدل والزهد ورد المظالم.',
            explanationEn: 'He was famous for justice, asceticism, and returning rights.'
        },
        {
            id: 61,
            question: 'من هو العالم المسلم الذي أسس علم الجبر؟',
            questionEn: 'Who is the Muslim scholar who founded Algebra?',
            options: ['الخوارزمي', 'ابن سينا', 'الرازي', 'ابن الهيثم'],
            optionsEn: ['Al-Khwarizmi', 'Ibn Sina', 'Al-Razi', 'Ibn Al-Haytham'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'كتابه "الجبر والمقابلة" هو أساس علم الجبر.',
            explanationEn: 'His book "Al-Jabr wal-Muqabala" is the foundation of Algebra.'
        },
        {
            id: 62,
            question: 'من هو أمير المؤمنين في الحديث؟',
            questionEn: 'Who is the Commander of the Faithful in Hadith?',
            options: ['الإمام البخاري', 'الإمام مسلم', 'أبو داود', 'الترمذي'],
            optionsEn: ['Imam Al-Bukhari', 'Imam Muslim', 'Abu Dawood', 'At-Tirmidhi'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'صحيح البخاري هو أصح كتاب بعد كتاب الله.',
            explanationEn: 'Sahih Al-Bukhari is the most authentic book after the Book of Allah.'
        },
        {
            id: 63,
            question: 'ما هي أطول سورة في القرآن؟',
            questionEn: 'What is the longest Surah in the Quran?',
            options: ['سورة البقرة', 'سورة آل عمران', 'سورة النساء', 'سورة المائدة'],
            optionsEn: ['Surah Al-Baqarah', 'Surah Ali Imran', 'Surah An-Nisa', 'Surah Al-Ma\'idah'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'عدد آياتها 286 آية.',
            explanationEn: 'It has 286 verses.'
        },
        {
            id: 64,
            question: 'ما هي أقصر سورة في القرآن؟',
            questionEn: 'What is the shortest Surah in the Quran?',
            options: ['سورة الكوثر', 'سورة الإخلاص', 'سورة العصر', 'سورة الناس'],
            optionsEn: ['Surah Al-Kawthar', 'Surah Al-Ikhlas', 'Surah Al-Asr', 'Surah An-Nas'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'عدد آياتها 3 آيات.',
            explanationEn: 'It has 3 verses.'
        },
        {
            id: 65,
            question: 'كم عدد أجزاء القرآن الكريم؟',
            questionEn: 'How many Juz (parts) are in the Quran?',
            options: ['30 جزءاً', '60 جزءاً', '114 جزءاً', '20 جزءاً'],
            optionsEn: ['30 Juz', '60 Juz', '114 Juz', '20 Juz'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'القرآن مقسم إلى 30 جزءاً.',
            explanationEn: 'The Quran is divided into 30 parts.'
        },
        {
            id: 66,
            question: 'من هو النبي الذي ابنه كافر؟',
            questionEn: 'Who is the Prophet whose son was a disbeliever?',
            options: ['نوح عليه السلام', 'إبراهيم', 'محمد ﷺ', 'يعقوب'],
            optionsEn: ['Nuh (AS)', 'Ibrahim', 'Muhammad ﷺ', 'Yaqub'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'نادى نوح ابنه وكان في معزل يا بني اركب معنا.',
            explanationEn: 'Nuh called his son who was apart, "O my son, come aboard with us."'
        },
        {
            id: 67,
            question: 'من هو النبي الذي أبوه كافر؟',
            questionEn: 'Who is the Prophet whose father was a disbeliever?',
            options: ['إبراهيم عليه السلام', 'نوح', 'إسماعيل', 'يوسف'],
            optionsEn: ['Ibrahim (AS)', 'Nuh', 'Ismail', 'Yusuf'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'أبوه آزر كان يعبد الأصنام.',
            explanationEn: 'His father Azar worshipped idols.'
        },
        {
            id: 68,
            question: 'من هو عم النبي ﷺ الذي نصر النبي ولم يسلم؟',
            questionEn: 'Who is the Prophet\'s uncle who supported him but didn\'t accept Islam?',
            options: ['أبو طالب', 'أبو لهب', 'العباس', 'حمزة'],
            optionsEn: ['Abu Talib', 'Abu Lahab', 'Al-Abbas', 'Hamza'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'دافع عن النبي ﷺ وحماه لكنه مات على دين قومه.',
            explanationEn: 'He defended and protected the Prophet ﷺ but died on the religion of his people.'
        },
        {
            id: 69,
            question: 'من هو عم النبي ﷺ الذي نزلت فيه سورة تتبت يدا؟',
            questionEn: 'Who is the Prophet\'s uncle about whom "Perish the hands" was revealed?',
            options: ['أبو لهب', 'أبو طالب', 'أبو جهل', 'العباس'],
            optionsEn: ['Abu Lahab', 'Abu Talib', 'Abu Jahl', 'Al-Abbas'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'تتبت يدا أبي لهب وتب.',
            explanationEn: 'Perish the two hands of Abu Lahab, and perish he.'
        },
        {
            id: 70,
            question: 'ما هي البيعة التي بايع فيها الصحابة النبي ﷺ تحت الشجرة؟',
            questionEn: 'What is the pledge where Companions pledged to Prophet ﷺ under the tree?',
            options: ['بيعة الرضوان', 'بيعة العقبة الأولى', 'بيعة العقبة الثانية', 'بيعة الحرب'],
            optionsEn: ['Pledge of Ridwan', 'First Pledge of Aqaba', 'Second Pledge of Aqaba', 'War Pledge'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'لقد رضي الله عن المؤمنين إذ يبايعونك تحت الشجرة.',
            explanationEn: 'Certainly was Allah pleased with the believers when they pledged allegiance to you under the tree.'
        },
        {
            id: 71,
            question: 'من هو الصحابي الذي دافع عن النبي ﷺ في أحد حتى شلت يده؟',
            questionEn: 'Who is the Companion who defended Prophet ﷺ in Uhud until his hand was paralyzed?',
            options: ['طلحة بن عبيد الله', 'الزبير', 'سعد', 'علي'],
            optionsEn: ['Talha bin Ubaidullah', 'Az-Zubair', 'Saad', 'Ali'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'سمي طلحة الخير وطلحة الفياض.',
            explanationEn: 'He was called Talha the Good and Talha the Generous.'
        },
        {
            id: 72,
            question: 'من هو الصحابي الذي لقب بذي النورين؟',
            questionEn: 'Who is the Companion titled Dhun-Nurayn (Possessor of Two Lights)?',
            options: ['عثمان بن عفان', 'علي', 'أبو بكر', 'عمر'],
            optionsEn: ['Uthman bin Affan', 'Ali', 'Abu Bakr', 'Umar'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'لأنه تزوج ابنتي النبي ﷺ رقية ثم أم كلثوم.',
            explanationEn: 'Because he married two daughters of the Prophet ﷺ: Ruqayyah then Umm Kulthum.'
        },
        {
            id: 73,
            question: 'من هو الصحابي الذي نام في فراش النبي ﷺ ليلة الهجرة؟',
            questionEn: 'Who is the Companion who slept in Prophet\'s ﷺ bed on Migration night?',
            options: ['علي بن أبي طالب', 'أبو بكر', 'عمر', 'عثمان'],
            optionsEn: ['Ali bin Abi Talib', 'Abu Bakr', 'Umar', 'Uthman'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'فدى النبي ﷺ بنفسه.',
            explanationEn: 'He ransomed the Prophet ﷺ with himself.'
        },
        {
            id: 74,
            question: 'من هو الصحابي الذي لقب بأسد الله؟',
            questionEn: 'Who is the Companion titled Lion of Allah?',
            options: ['حمزة بن عبد المطلب', 'علي', 'خالد', 'عمر'],
            optionsEn: ['Hamza bin Abdul-Muttalib', 'Ali', 'Khalid', 'Umar'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'حمزة رضي الله عنه أسد الله وأسد رسوله.',
            explanationEn: 'Hamza (RA) is the Lion of Allah and Lion of His Messenger.'
        },
        {
            id: 75,
            question: 'من هو الصحابي الذي لقب بأمين السماء؟',
            questionEn: 'Who is the angel titled Trustworthy of Heaven?',
            options: ['جبريل عليه السلام', 'ميكائيل', 'إسرافيل', 'ملك الموت'],
            optionsEn: ['Jibril (AS)', 'Mikail', 'Israfil', 'Angel of Death'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'نزل به الروح الأمين.',
            explanationEn: 'The Trustworthy Spirit has brought it down.'
        }
    ]
};
