import { QuizLevel } from '../quizTypes';

export const level6: QuizLevel = {
    id: 6,
    titleAr: 'الصلاة',
    titleEn: 'Prayer (Salah)',
    description: 'تعلم أحكام وكيفية الصلاة وأهميتها',
    descriptionEn: 'Learn rules, how to pray, and its importance',
    requiredScore: 70,
    icon: '🕌',
    questions: [
        // General Prayer Knowledge
        {
            id: 1,
            question: 'كم عدد الصلوات المفروضة في اليوم والليلة؟',
            questionEn: 'How many obligatory prayers are there in a day and night?',
            options: ['5 صلوات', '3 صلوات', '4 صلوات', '6 صلوات'],
            optionsEn: ['5 prayers', '3 prayers', '4 prayers', '6 prayers'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'فرض الله علينا خمس صلوات في اليوم والليلة.',
            explanationEn: 'Allah obligated five prayers upon us in the day and night.'
        },
        {
            id: 2,
            question: 'ما هي أول صلاة يصليها المسلم في اليوم؟',
            questionEn: 'What is the first prayer a Muslim prays in the day?',
            options: ['الفجر', 'الظهر', 'العصر', 'المغرب'],
            optionsEn: ['Fajr', 'Dhuhr', 'Asr', 'Maghrib'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'صلاة الفجر هي أول صلاة وتبدأ بطلوع الفجر الصادق.',
            explanationEn: 'Fajr prayer is the first prayer and begins at the true dawn.'
        },
        {
            id: 3,
            question: 'ما هي الصلاة الوسطى؟',
            questionEn: 'What is the middle prayer (Salat al-Wusta)?',
            options: ['العصر', 'الظهر', 'المغرب', 'العشاء'],
            optionsEn: ['Asr', 'Dhuhr', 'Maghrib', 'Isha'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'الصلاة الوسطى هي صلاة العصر كما ورد في الحديث.',
            explanationEn: 'The middle prayer is the Asr prayer as mentioned in the Hadith.'
        },
        {
            id: 4,
            question: 'ما هو الركن الثاني من أركان الإسلام؟',
            questionEn: 'What is the second pillar of Islam?',
            options: ['الصلاة', 'الزكاة', 'الصوم', 'الحج'],
            optionsEn: ['Prayer (Salah)', 'Zakat', 'Fasting', 'Hajj'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'الصلاة هي الركن الثاني بعد الشهادتين.',
            explanationEn: 'Prayer is the second pillar after the Shahada.'
        },
        {
            id: 5,
            question: 'في أي اتجاه نصلي؟',
            questionEn: 'In which direction do we pray?',
            options: ['القبلة (الكعبة)', 'الشرق', 'الغرب', 'الشمال'],
            optionsEn: ['Qibla (Kaaba)', 'East', 'West', 'North'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'نستقبل القبلة وهي الكعبة المشرفة في مكة المكرمة.',
            explanationEn: 'We face the Qibla, which is the honorable Kaaba in Mecca.'
        },
        // Wudu (Ablution)
        {
            id: 6,
            question: 'ماذا يجب علينا فعله قبل الصلاة؟',
            questionEn: 'What must we do before prayer?',
            options: ['الوضوء', 'الأكل', 'النوم', 'اللعب'],
            optionsEn: ['Wudu (Ablution)', 'Eat', 'Sleep', 'Play'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'لا تقبل صلاة بغير طهور (وضوء).',
            explanationEn: 'Prayer is not accepted without purification (Wudu).'
        },
        {
            id: 7,
            question: 'كم مرة نغسل الوجه في الوضوء؟',
            questionEn: 'How many times do we wash the face in Wudu?',
            options: ['3 مرات', 'مرة واحدة', '5 مرات', 'لا نغسله'],
            optionsEn: ['3 times', 'Once', '5 times', 'Don\'t wash it'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'السنة غسل الأعضاء ثلاثاً، والواجب مرة واحدة.',
            explanationEn: 'The Sunnah is to wash the limbs three times, and the obligatory is once.'
        },
        {
            id: 8,
            question: 'ماذا نمسح في الوضوء؟',
            questionEn: 'What do we wipe in Wudu?',
            options: ['الرأس والأذنين', 'الوجه', 'اليدين', 'الرجلين'],
            optionsEn: ['Head and ears', 'Face', 'Hands', 'Feet'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'نمسح الرأس والأذنين مرة واحدة.',
            explanationEn: 'We wipe the head and ears once.'
        },
        {
            id: 9,
            question: 'هل النوم العميق ينقض الوضوء؟',
            questionEn: 'Does deep sleep break Wudu?',
            options: ['نعم', 'لا', 'أحياناً', 'فقط في الليل'],
            optionsEn: ['Yes', 'No', 'Sometimes', 'Only at night'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'النوم العميق الذي يزول معه الإدراك ينقض الوضوء.',
            explanationEn: 'Deep sleep where awareness is lost breaks Wudu.'
        },
        {
            id: 10,
            question: 'ماذا نقول بعد الانتهاء من الوضوء؟',
            questionEn: 'What do we say after finishing Wudu?',
            options: ['أشهد أن لا إله إلا الله...', 'الحمد لله', 'سبحان الله', 'الله أكبر'],
            optionsEn: ['Ashhadu an la ilaha illallah...', 'Alhamdulillah', 'SubhanAllah', 'Allahu Akbar'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'من قال الشهادة بعد الوضوء فتحت له أبواب الجنة.',
            explanationEn: 'Whoever says the Shahada after Wudu, the gates of Paradise are opened for him.'
        },
        // Prayer Actions
        {
            id: 11,
            question: 'ما هي تكبيرة الإحرام؟',
            questionEn: 'What is Takbirat al-Ihram?',
            options: ['قول "الله أكبر" في بداية الصلاة', 'قول "سمع الله لمن حمده"', 'التسليم', 'الركوع'],
            optionsEn: ['Saying "Allahu Akbar" at start', 'Saying "Sami Allahu..."', 'Tasleem', 'Ruku'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'تكبيرة الإحرام هي قول "الله أكبر" للدخول في الصلاة.',
            explanationEn: 'Takbirat al-Ihram is saying "Allahu Akbar" to enter the prayer.'
        },
        {
            id: 12,
            question: 'ماذا نقرأ في كل ركعة؟',
            questionEn: 'What do we read in every Rak\'ah?',
            options: ['سورة الفاتحة', 'سورة الإخلاص', 'آية الكرسي', 'التشهد'],
            optionsEn: ['Surah Al-Fatiha', 'Surah Al-Ikhlas', 'Ayat al-Kursi', 'Tashahhud'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'لا صلاة لمن لم يقرأ بفاتحة الكتاب.',
            explanationEn: 'There is no prayer for the one who does not recite the Opening of the Book (Al-Fatiha).'
        },
        {
            id: 13,
            question: 'ماذا نقول في الركوع؟',
            questionEn: 'What do we say in Ruku (bowing)?',
            options: ['سبحان ربي العظيم', 'سبحان ربي الأعلى', 'سمع الله لمن حمده', 'الله أكبر'],
            optionsEn: ['Subhana Rabbiyal Azeem', 'Subhana Rabbiyal A\'la', 'Sami Allahu...', 'Allahu Akbar'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'نقول في الركوع: سبحان ربي العظيم (3 مرات).',
            explanationEn: 'We say in Ruku: Glory be to my Lord the Great (3 times).'
        },
        {
            id: 14,
            question: 'ماذا نقول في السجود؟',
            questionEn: 'What do we say in Sujud (prostration)?',
            options: ['سبحان ربي الأعلى', 'سبحان ربي العظيم', 'رب اغفر لي', 'التحيات'],
            optionsEn: ['Subhana Rabbiyal A\'la', 'Subhana Rabbiyal Azeem', 'Rabbighfir li', 'At-Tahiyyat'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'نقول في السجود: سبحان ربي الأعلى (3 مرات).',
            explanationEn: 'We say in Sujud: Glory be to my Lord the Most High (3 times).'
        },
        {
            id: 15,
            question: 'ماذا نقول بين السجدتين؟',
            questionEn: 'What do we say between the two prostrations?',
            options: ['رب اغفر لي', 'سبحان الله', 'الحمد لله', 'الله أكبر'],
            optionsEn: ['Rabbighfir li', 'SubhanAllah', 'Alhamdulillah', 'Allahu Akbar'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'نقول: رب اغفر لي، رب اغفر لي.',
            explanationEn: 'We say: My Lord forgive me, My Lord forgive me.'
        },
        {
            id: 16,
            question: 'متى نقرأ التشهد الأخير؟',
            questionEn: 'When do we read the final Tashahhud?',
            options: ['في آخر ركعة قبل السلام', 'في الركعة الأولى', 'بعد الفاتحة', 'في السجود'],
            optionsEn: ['In last Rak\'ah before Salam', 'In first Rak\'ah', 'After Fatiha', 'In Sujud'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'نقرأ التشهد والصلاة الإبراهيمية في الجلوس الأخير.',
            explanationEn: 'We recite Tashahhud and Salawat Ibrahimiyyah in the final sitting.'
        },
        {
            id: 17,
            question: 'كيف ننهي الصلاة؟',
            questionEn: 'How do we end the prayer?',
            options: ['بالتسليم (السلام عليكم ورحمة الله)', 'بالقيام', 'بالسجود', 'بالكلام'],
            optionsEn: ['With Tasleem', 'Standing up', 'Prostrating', 'Talking'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'تحليل الصلاة التسليم.',
            explanationEn: 'The exiting of prayer is the Tasleem.'
        },
        // Specific Prayers
        {
            id: 18,
            question: 'كم عدد ركعات صلاة الفجر؟',
            questionEn: 'How many Rak\'ahs is Fajr prayer?',
            options: ['ركعتان', '4 ركعات', '3 ركعات', 'ركعة واحدة'],
            optionsEn: ['2 Rak\'ahs', '4 Rak\'ahs', '3 Rak\'ahs', '1 Rak\'ah'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'صلاة الفجر ركعتان جهريتان.',
            explanationEn: 'Fajr prayer is two Rak\'ahs recited aloud.'
        },
        {
            id: 19,
            question: 'كم عدد ركعات صلاة الظهر؟',
            questionEn: 'How many Rak\'ahs is Dhuhr prayer?',
            options: ['4 ركعات', '2 ركعات', '3 ركعات', '5 ركعات'],
            optionsEn: ['4 Rak\'ahs', '2 Rak\'ahs', '3 Rak\'ahs', '5 Rak\'ahs'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'صلاة الظهر أربع ركعات سرية.',
            explanationEn: 'Dhuhr prayer is four Rak\'ahs recited silently.'
        },
        {
            id: 20,
            question: 'كم عدد ركعات صلاة المغرب؟',
            questionEn: 'How many Rak\'ahs is Maghrib prayer?',
            options: ['3 ركعات', '4 ركعات', '2 ركعات', '5 ركعات'],
            optionsEn: ['3 Rak\'ahs', '4 Rak\'ahs', '2 Rak\'ahs', '5 Rak\'ahs'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'صلاة المغرب ثلاث ركعات (أول ركعتين جهرية).',
            explanationEn: 'Maghrib prayer is three Rak\'ahs (first two aloud).'
        },
        {
            id: 21,
            question: 'ما هي صلاة الجمعة؟',
            questionEn: 'What is Jumu\'ah prayer?',
            options: ['صلاة بديلة للظهر يوم الجمعة', 'صلاة العصر', 'صلاة إضافية', 'سنة'],
            optionsEn: ['Substitute for Dhuhr on Friday', 'Asr prayer', 'Extra prayer', 'Sunnah'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'صلاة الجمعة ركعتان جهريتان وتجب على الرجال بدلاً من الظهر.',
            explanationEn: 'Jumu\'ah prayer is two Rak\'ahs aloud and is obligatory for men instead of Dhuhr.'
        },
        {
            id: 22,
            question: 'ما هي صلاة الوتر؟',
            questionEn: 'What is Witr prayer?',
            options: ['صلاة تختم صلاة الليل', 'صلاة الفجر', 'صلاة الظهر', 'صلاة العيد'],
            optionsEn: ['Prayer ending night prayers', 'Fajr', 'Dhuhr', 'Eid'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'الوتر سنة مؤكدة تختم بها صلاة الليل وأقلها ركعة.',
            explanationEn: 'Witr is a confirmed Sunnah to end night prayers, minimum is one Rak\'ah.'
        },
        // Prayer Conditions & Invalidators
        {
            id: 23,
            question: 'ما هو ستر العورة في الصلاة؟',
            questionEn: 'What is covering the Awrah in prayer?',
            options: ['شرط لصحة الصلاة', 'سنة', 'مستحب', 'غير مهم'],
            optionsEn: ['Condition for validity', 'Sunnah', 'Recommended', 'Not important'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'ستر العورة شرط من شروط صحة الصلاة.',
            explanationEn: 'Covering the Awrah is a condition for the validity of prayer.'
        },
        {
            id: 24,
            question: 'هل يجوز الكلام العادي في الصلاة؟',
            questionEn: 'Is normal talking allowed in prayer?',
            options: ['لا، يبطل الصلاة', 'نعم، قليلاً', 'نعم، للضرورة', 'نعم'],
            optionsEn: ['No, invalidates prayer', 'Yes, a little', 'Yes, if necessary', 'Yes'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'الكلام العمد لغير مصلحة الصلاة يبطلها.',
            explanationEn: 'Intentional talking not for the benefit of prayer invalidates it.'
        },
        {
            id: 25,
            question: 'ماذا تفعل إذا نسيت ركعة؟',
            questionEn: 'What do you do if you forget a Rak\'ah?',
            options: ['تأتي بها وتسجد للسهو', 'تعيد الصلاة', 'تكمل ولا شيء عليك', 'تستغفر'],
            optionsEn: ['Perform it and do Sujud Sahw', 'Repeat prayer', 'Continue, nothing on you', 'Seek forgiveness'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'يجب أن تأتي بالركعة الناقصة ثم تسجد للسهو.',
            explanationEn: 'You must perform the missing Rak\'ah then do the prostration of forgetfulness.'
        },
        {
            id: 26,
            question: 'هل الضحك يبطل الصلاة؟',
            questionEn: 'Does laughing invalidate prayer?',
            options: ['نعم، إذا ظهر صوت', 'لا', 'فقط الابتسامة', 'أحياناً'],
            optionsEn: ['Yes, if sound is made', 'No', 'Only smiling', 'Sometimes'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'الضحك بصوت (القهقهة) يبطل الصلاة.',
            explanationEn: 'Laughing with sound (guffawing) invalidates prayer.'
        },
        // Adhan & Iqamah
        {
            id: 27,
            question: 'ما هو الأذان؟',
            questionEn: 'What is Adhan?',
            options: ['الإعلام بدخول وقت الصلاة', 'الإقامة للصلاة', 'الدعاء', 'القرآن'],
            optionsEn: ['Announcement of prayer time', 'Iqamah', 'Dua', 'Quran'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'الأذان هو النداء للصلاة عند دخول وقتها.',
            explanationEn: 'Adhan is the call to prayer when its time enters.'
        },
        {
            id: 28,
            question: 'ما هي الإقامة؟',
            questionEn: 'What is Iqamah?',
            options: ['الإعلام بالقيام للصلاة', 'الأذان', 'الخطبة', 'التسبيح'],
            optionsEn: ['Announcement to stand for prayer', 'Adhan', 'Sermon', 'Tasbih'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'الإقامة هي الإعلام بالقيام لأداء الصلاة المفروضة.',
            explanationEn: 'Iqamah is the announcement to stand up to perform the obligatory prayer.'
        },
        {
            id: 29,
            question: 'ماذا يزاد في أذان الفجر؟',
            questionEn: 'What is added in Fajr Adhan?',
            options: ['الصلاة خير من النوم', 'حي على خير العمل', 'الله أكبر', 'لا إله إلا الله'],
            optionsEn: ['Prayer is better than sleep', 'Come to best action', 'Allahu Akbar', 'La ilaha illallah'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'يزاد في أذان الفجر: الصلاة خير من النوم (مرتين).',
            explanationEn: 'Added in Fajr Adhan: Prayer is better than sleep (twice).'
        },
        // Sunnah Prayers
        {
            id: 30,
            question: 'ما هي السنن الرواتب؟',
            questionEn: 'What are Sunan al-Rawatib?',
            options: ['صلوات مسنونة قبل أو بعد الفريضة', 'صلاة العيد', 'صلاة الجنازة', 'قيام الليل'],
            optionsEn: ['Sunnah prayers before/after Fard', 'Eid prayer', 'Funeral prayer', 'Night prayer'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'هي السنن التابعة للصلوات المفروضة (12 ركعة في اليوم).',
            explanationEn: 'They are Sunnahs attached to obligatory prayers (12 Rak\'ahs daily).'
        },
        {
            id: 31,
            question: 'كم عدد ركعات سنة الفجر؟',
            questionEn: 'How many Rak\'ahs is Sunnah of Fajr?',
            options: ['ركعتان قبل الفرض', '4 ركعات', 'ركعتان بعد الفرض', 'لا يوجد'],
            optionsEn: ['2 before Fard', '4 Rak\'ahs', '2 after Fard', 'None'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'ركعتا الفجر خير من الدنيا وما فيها.',
            explanationEn: 'The two (Sunnah) Rak\'ahs of Fajr are better than the world and what is in it.'
        },
        {
            id: 32,
            question: 'ما هي صلاة الضحى؟',
            questionEn: 'What is Duha prayer?',
            options: ['صلاة الأوابين بعد شروق الشمس', 'صلاة الظهر', 'صلاة الليل', 'صلاة العصر'],
            optionsEn: ['Prayer of repentant after sunrise', 'Dhuhr', 'Night prayer', 'Asr'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'صلاة الضحى تصلى بعد ارتفاع الشمس وتسمى صلاة الأوابين.',
            explanationEn: 'Duha prayer is performed after the sun rises high and is called the prayer of the repentant.'
        },
        // Congregational Prayer
        {
            id: 33,
            question: 'ما فضل صلاة الجماعة؟',
            questionEn: 'What is the virtue of congregational prayer?',
            options: ['تفضل صلاة الفذ بـ 27 درجة', 'مثل صلاة الفرد', 'أقل أجراً', 'مكروهة'],
            optionsEn: ['27 times better than alone', 'Same as alone', 'Less reward', 'Disliked'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'صلاة الجماعة تفضل صلاة الفذ بسبع وعشرين درجة.',
            explanationEn: 'Congregational prayer is twenty-seven degrees better than individual prayer.'
        },
        {
            id: 34,
            question: 'من هو الإمام؟',
            questionEn: 'Who is the Imam?',
            options: ['من يؤم الناس في الصلاة', 'المؤذن', 'المصلين', 'الخطيب'],
            optionsEn: ['One who leads prayer', 'Muazzin', 'Followers', 'Speaker'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'الإمام هو الذي يقتدي به المصلون في صلاتهم.',
            explanationEn: 'The Imam is the one whom the worshippers follow in their prayer.'
        },
        {
            id: 35,
            question: 'ماذا يفعل المأموم؟',
            questionEn: 'What does the Ma\'mum (follower) do?',
            options: ['يتابع الإمام ولا يسبقه', 'يسبق الإمام', 'يخالف الإمام', 'يصلي وحده'],
            optionsEn: ['Follows Imam, doesn\'t precede', 'Precedes Imam', 'Differs from Imam', 'Prays alone'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'إنما جعل الإمام ليؤتم به، فلا تختلفوا عليه.',
            explanationEn: 'The Imam is appointed only to be followed, so do not differ from him.'
        },
        // Advanced Questions
        {
            id: 36,
            question: 'ما هي صلاة الكسوف؟',
            questionEn: 'What is Kusuf prayer?',
            options: ['صلاة عند ذهاب ضوء الشمس', 'صلاة عند المطر', 'صلاة العيد', 'صلاة الليل'],
            optionsEn: ['Prayer during solar eclipse', 'Rain prayer', 'Eid prayer', 'Night prayer'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'صلاة الكسوف سنة مؤكدة تصلى عند كسوف الشمس.',
            explanationEn: 'Kusuf prayer is a confirmed Sunnah performed during a solar eclipse.'
        },
        {
            id: 37,
            question: 'ما هي صلاة الاستسقاء؟',
            questionEn: 'What is Istisqa prayer?',
            options: ['طلب المطر من الله', 'طلب الرزق', 'طلب الشفاء', 'طلب العلم'],
            optionsEn: ['Asking Allah for rain', 'Asking for provision', 'Asking for cure', 'Asking for knowledge'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'صلاة الاستسقاء هي طلب السقيا (المطر) من الله عند الجدب.',
            explanationEn: 'Istisqa prayer is asking Allah for rain during drought.'
        },
        {
            id: 38,
            question: 'ما هي صلاة الاستخارة؟',
            questionEn: 'What is Istikhara prayer?',
            options: ['طلب الخيرة من الله في أمر مباح', 'طلب المغفرة', 'طلب الرزق', 'صلاة الفجر'],
            optionsEn: ['Seeking Allah\'s guidance in permissible matter', 'Seeking forgiveness', 'Seeking provision', 'Fajr'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'يصليها المسلم عندما يحتار في أمر ليختار الله له الأفضل.',
            explanationEn: 'A Muslim prays it when confused about a matter so Allah chooses the best for him.'
        },
        {
            id: 39,
            question: 'ما هي صلاة المسافر (القصر)؟',
            questionEn: 'What is the traveler\'s prayer (Qasr)?',
            options: ['تقصير الصلاة الرباعية إلى ركعتين', 'ترك الصلاة', 'جمع الصلوات فقط', 'زيادة الركعات'],
            optionsEn: ['Shortening 4-Rak\'ah prayers to 2', 'Leaving prayer', 'Joining only', 'Increasing Rak\'ahs'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'يجوز للمسافر قصر الصلاة الرباعية (الظهر، العصر، العشاء) إلى ركعتين.',
            explanationEn: 'It is permissible for a traveler to shorten 4-Rak\'ah prayers (Dhuhr, Asr, Isha) to 2 Rak\'ahs.'
        },
        {
            id: 40,
            question: 'ما هو الجمع في الصلاة؟',
            questionEn: 'What is Jam\' (joining) in prayer?',
            options: ['أداء صلاتين في وقت إحداهما', 'أداء كل الصلوات مرة واحدة', 'ترك الصلاة', 'صلاة الجماعة'],
            optionsEn: ['Performing two prayers at one time', 'Performing all prayers at once', 'Leaving prayer', 'Congregational prayer'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'يجوز للمسافر والمريض جمع الظهر مع العصر، والمغرب مع العشاء.',
            explanationEn: 'It is permissible for travelers and sick to join Dhuhr with Asr, and Maghrib with Isha.'
        },
        {
            id: 41,
            question: 'ما هي صلاة الخوف؟',
            questionEn: 'What is the Fear Prayer (Salat al-Khauf)?',
            options: ['صلاة تصلى في الحرب بطريقة خاصة', 'صلاة عند الخوف من الظلام', 'صلاة الاستعاذة', 'صلاة الليل'],
            optionsEn: ['Prayer in war with special method', 'Prayer when afraid of dark', 'Refuge prayer', 'Night prayer'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'صلاة الخوف مشروعة في القتال ولها صفات متعددة.',
            explanationEn: 'Fear prayer is prescribed during battle and has multiple forms.'
        },
        {
            id: 42,
            question: 'ما حكم تارك الصلاة تكاسلاً؟',
            questionEn: 'What is the ruling on one who leaves prayer out of laziness?',
            options: ['على خطر عظيم وكبيرة من الكبائر', 'لا شيء عليه', 'مكروه', 'مباح'],
            optionsEn: ['In great danger and major sin', 'Nothing on him', 'Disliked', 'Permissible'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'ترك الصلاة من أعظم الذنوب والعهد الذي بيننا وبينهم الصلاة.',
            explanationEn: 'Leaving prayer is one of the greatest sins; the covenant between us and them is prayer.'
        },
        {
            id: 43,
            question: 'ما هي تحية المسجد؟',
            questionEn: 'What is Tahiyyat al-Masjid?',
            options: ['ركعتان قبل الجلوس في المسجد', 'السلام على الناس', 'قول سبحان الله', 'صلاة الفجر'],
            optionsEn: ['2 Rak\'ahs before sitting in mosque', 'Greeting people', 'Saying SubhanAllah', 'Fajr'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'إذا دخل أحدكم المسجد فلا يجلس حتى يصلي ركعتين.',
            explanationEn: 'If one of you enters the mosque, let him not sit until he prays two Rak\'ahs.'
        },
        {
            id: 44,
            question: 'هل تجوز الصلاة في المقبرة؟',
            questionEn: 'Is prayer permissible in a graveyard?',
            options: ['لا، إلا صلاة الجنازة', 'نعم', 'نعم، إذا كانت نظيفة', 'أحياناً'],
            optionsEn: ['No, except funeral prayer', 'Yes', 'Yes, if clean', 'Sometimes'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'الأرض كلها مسجد إلا المقبرة والحمام.',
            explanationEn: 'The whole earth is a mosque except for the graveyard and the bathroom.'
        },
        {
            id: 45,
            question: 'ما هي سترة المصلي؟',
            questionEn: 'What is the Sutrah of the praying person?',
            options: ['حاجز يضعه المصلي أمامه', 'ملابس الصلاة', 'سجادة الصلاة', 'غطاء الرأس'],
            optionsEn: ['Barrier placed in front', 'Prayer clothes', 'Prayer mat', 'Head cover'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'السترة هي ما يجعله المصلي أمامه لمنع المرور بين يديه.',
            explanationEn: 'Sutrah is what the praying person places in front to prevent passing before him.'
        },
        {
            id: 46,
            question: 'ما حكم المرور بين يدي المصلي؟',
            questionEn: 'What is the ruling on passing in front of a praying person?',
            options: ['حرام (إثم عظيم)', 'مكروه', 'مباح', 'جائز'],
            optionsEn: ['Forbidden (great sin)', 'Disliked', 'Permissible', 'Allowed'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'لو يعلم المار بين يدي المصلي ماذا عليه لكان أن يقف أربعين خيراً له.',
            explanationEn: 'If the one passing in front of a praying person knew what was upon him, waiting for forty would be better.'
        },
        {
            id: 47,
            question: 'ما هي مبطلات الصلاة؟',
            questionEn: 'What invalidates prayer?',
            options: ['الأكل والشرب والكلام والحدث', 'التفكير', 'الحركة البسيطة', 'إغماض العين'],
            optionsEn: ['Eating, drinking, talking, Hadath', 'Thinking', 'Slight movement', 'Closing eyes'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'الأكل والشرب والكلام العمد وانتقاض الوضوء يبطل الصلاة.',
            explanationEn: 'Eating, drinking, intentional talking, and breaking Wudu invalidate prayer.'
        },
        {
            id: 48,
            question: 'ما هو التيمم؟',
            questionEn: 'What is Tayammum?',
            options: ['التطهر بالتراب عند فقد الماء', 'الوضوء بالماء', 'الغسل', 'المسح على الخفين'],
            optionsEn: ['Purification with dust when no water', 'Wudu with water', 'Ghusl', 'Wiping socks'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'التيمم هو مسح الوجه واليدين بالصعيد الطيب (التراب) بدلاً من الوضوء.',
            explanationEn: 'Tayammum is wiping the face and hands with clean earth instead of Wudu.'
        },
        {
            id: 49,
            question: 'متى يجوز التيمم؟',
            questionEn: 'When is Tayammum permissible?',
            options: ['عند فقد الماء أو العجز عن استعماله', 'إذا كنت مستعجلاً', 'في السفر دائماً', 'في البرد فقط'],
            optionsEn: ['Lack of water or inability to use', 'If in a hurry', 'Always in travel', 'Only in cold'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'فلم تجدوا ماء فتيمموا صعيداً طيباً.',
            explanationEn: 'And if you do not find water, then seek clean earth.'
        },
        {
            id: 50,
            question: 'ما هي أوقات النهي عن الصلاة؟',
            questionEn: 'What are the forbidden times for prayer?',
            options: ['بعد الفجر حتى الشروق، وعند الزوال، وبعد العصر حتى الغروب', 'في الليل', 'وقت الظهر', 'يوم الجمعة'],
            optionsEn: ['After Fajr til sunrise, zenith, after Asr til sunset', 'At night', 'Dhuhr time', 'Friday'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'نهى النبي ﷺ عن الصلاة في هذه الأوقات الثلاثة (إلا الفرائض أو ذوات الأسباب).',
            explanationEn: 'The Prophet ﷺ forbade prayer at these three times (except obligatory or specific reason prayers).'
        },
        {
            id: 51,
            question: 'ما هي صلاة العيد؟',
            questionEn: 'What is Eid prayer?',
            options: ['ركعتان بسبع تكبيرات في الأولى وخمس في الثانية', 'أربع ركعات', 'مثل الجمعة', 'ركعة واحدة'],
            optionsEn: ['2 Rak\'ahs with 7 Takbirs then 5', '4 Rak\'ahs', 'Like Jumu\'ah', '1 Rak\'ah'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'صلاة العيد ركعتان، يكبر في الأولى سبعاً وفي الثانية خمساً.',
            explanationEn: 'Eid prayer is two Rak\'ahs, with seven Takbirs in the first and five in the second.'
        },
        {
            id: 52,
            question: 'هل للأذان شروط؟',
            questionEn: 'Are there conditions for Adhan?',
            options: ['دخول الوقت، والنية، والذكورة، والترتيب', 'لا شروط', 'الوضوء فقط', 'أن يكون في المسجد'],
            optionsEn: ['Time entry, intention, male, order', 'No conditions', 'Only Wudu', 'In mosque'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'من شروط الأذان دخول الوقت وأن يكون المؤذن ذكراً عاقلاً.',
            explanationEn: 'Conditions include time entry and the Muazzin being a sane male.'
        },
        {
            id: 53,
            question: 'ما حكم الصلاة في الثوب المغصوب؟',
            questionEn: 'Ruling on praying in stolen clothes?',
            options: ['لا تصح (عند الجمهور)', 'تصح مع الإثم', 'تصح', 'مكروهة'],
            optionsEn: ['Invalid (majority)', 'Valid with sin', 'Valid', 'Disliked'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'الصلاة في الثوب المغصوب باطلة عند الحنابلة وصحيحة مع الإثم عند الجمهور.',
            explanationEn: 'Prayer in stolen clothes is invalid according to Hanbalis and valid with sin according to the majority.'
        },
        {
            id: 54,
            question: 'ما هو الخشوع في الصلاة؟',
            questionEn: 'What is Khushu\' in prayer?',
            options: ['حضور القلب وسكون الجوارح', 'البكاء فقط', 'إغماض العينين', 'القراءة بصوت جميل'],
            optionsEn: ['Presence of heart and stillness', 'Only crying', 'Closing eyes', 'Beautiful voice'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'قد أفلح المؤمنون الذين هم في صلاتهم خاشعون.',
            explanationEn: 'Successful are the believers who are humble in their prayers.'
        },
        {
            id: 55,
            question: 'ما حكم رفع البصر إلى السماء في الصلاة؟',
            questionEn: 'Ruling on looking up to the sky in prayer?',
            options: ['حرام (وعيد شديد)', 'مكروه', 'مباح', 'سنة'],
            optionsEn: ['Forbidden (severe warning)', 'Disliked', 'Permissible', 'Sunnah'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'لينتهين أقوام عن رفع أبصارهم إلى السماء في الصلاة أو لتخطفن أبصارهم.',
            explanationEn: 'People must stop looking up to the sky in prayer or their sight will be snatched away.'
        },
        {
            id: 56,
            question: 'ما هي جلسة الاستراحة؟',
            questionEn: 'What is Jalsat al-Istirahah?',
            options: ['جلسة خفيفة بعد السجدة الثانية في الركعة الأولى والثالثة', 'التشهد', 'الجلوس بين السجدتين', 'بعد السلام'],
            optionsEn: ['Light sitting after 2nd Sujud in 1st/3rd Rak\'ah', 'Tashahhud', 'Between Sujuds', 'After Salam'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'هي جلسة يسيرة قبل القيام للركعة الثانية أو الرابعة.',
            explanationEn: 'It is a brief sitting before standing up for the second or fourth Rak\'ah.'
        },
        {
            id: 57,
            question: 'ما حكم الصلاة بالحذاء؟',
            questionEn: 'Ruling on praying with shoes?',
            options: ['جائزة إذا كانت طاهرة', 'حرام', 'مكروهة', 'واجبة'],
            optionsEn: ['Permissible if clean', 'Forbidden', 'Disliked', 'Obligatory'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'خالفوا اليهود فإنهم لا يصلون في نعالهم ولا خفافهم.',
            explanationEn: 'Differ from the Jews, for they do not pray in their shoes or leather socks.'
        },
        {
            id: 58,
            question: 'ما هو الدعاء المستجاب في الصلاة؟',
            questionEn: 'Which Dua is answered in prayer?',
            options: ['في السجود وقبل التسليم', 'في القيام', 'في الركوع', 'بداية الصلاة'],
            optionsEn: ['In Sujud and before Tasleem', 'In standing', 'In Ruku', 'Start of prayer'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'أقرب ما يكون العبد من ربه وهو ساجد فأكثروا الدعاء.',
            explanationEn: 'The closest a servant is to his Lord is when he is prostrating, so increase supplication.'
        },
        {
            id: 59,
            question: 'ما حكم تسوية الصفوف؟',
            questionEn: 'Ruling on straightening rows?',
            options: ['واجبة (أو سنة مؤكدة)', 'مستحبة', 'غير مهمة', 'مكروهة'],
            optionsEn: ['Obligatory (or confirmed Sunnah)', 'Recommended', 'Not important', 'Disliked'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'سووا صفوفكم فإن تسوية الصفوف من تمام الصلاة.',
            explanationEn: 'Straighten your rows, for straightening rows is part of the perfection of prayer.'
        },
        {
            id: 60,
            question: 'ماذا يفعل من فاتته صلاة ونام عنها؟',
            questionEn: 'What does one do if he sleeps through a prayer?',
            options: ['يصليها إذا ذكرها', 'لا يصليها', 'يصليها في اليوم التالي', 'يتصدق'],
            optionsEn: ['Pray it when he remembers', 'Don\'t pray', 'Pray next day', 'Give charity'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'من نام عن صلاة أو نسيها فليصلها إذا ذكرها.',
            explanationEn: 'Whoever sleeps through a prayer or forgets it, let him pray it when he remembers.'
        },
        {
            id: 61,
            question: 'ما هي الصلاة التي ليس فيها ركوع ولا سجود؟',
            questionEn: 'Which prayer has no Ruku or Sujud?',
            options: ['صلاة الجنازة', 'صلاة العيد', 'صلاة الكسوف', 'صلاة الوتر'],
            optionsEn: ['Funeral prayer', 'Eid prayer', 'Kusuf prayer', 'Witr prayer'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'صلاة الجنازة عبارة عن قيام وتكبيرات ودعاء فقط.',
            explanationEn: 'Funeral prayer consists of standing, Takbirs, and supplication only.'
        },
        {
            id: 62,
            question: 'كم عدد تكبيرات صلاة الجنازة؟',
            questionEn: 'How many Takbirs in Funeral prayer?',
            options: ['4 تكبيرات', '7 تكبيرات', '5 تكبيرات', '3 تكبيرات'],
            optionsEn: ['4 Takbirs', '7 Takbirs', '5 Takbirs', '3 Takbirs'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'يكبر أربع تكبيرات: الفاتحة، الصلاة على النبي، الدعاء للميت، الدعاء للمسلمين.',
            explanationEn: 'He says four Takbirs: Fatiha, Salawat, Dua for deceased, Dua for Muslims.'
        },
        {
            id: 63,
            question: 'ما حكم الصلاة خلف المذياع أو التلفاز؟',
            questionEn: 'Ruling on praying behind radio or TV?',
            options: ['لا تصح', 'تصح', 'تصح مع الكراهة', 'تصح للمريض'],
            optionsEn: ['Invalid', 'Valid', 'Valid with dislike', 'Valid for sick'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'لا تصح الصلاة بالاقتداء عبر المذياع أو التلفاز لانقطاع الاتصال.',
            explanationEn: 'Prayer following radio or TV is invalid due to disconnection.'
        },
        {
            id: 64,
            question: 'ما هو المسح على الخفين؟',
            questionEn: 'What is wiping over socks (Khuffain)?',
            options: ['رخصة بدلاً من غسل الرجلين', 'واجب', 'مكروه', 'بدعة'],
            optionsEn: ['Concession instead of washing feet', 'Obligatory', 'Disliked', 'Innovation'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'يجوز المسح على الخفين يوماً وليلة للمقيم وثلاثة للمسافر.',
            explanationEn: 'It is permissible to wipe over socks for one day/night for resident and three for traveler.'
        },
        {
            id: 65,
            question: 'ما هي شروط المسح على الخفين؟',
            questionEn: 'Conditions for wiping over socks?',
            options: ['لبسهما على طهارة، وسترهما للكعبين', 'أن يكونا جديدين', 'أن يكونا من جلد', 'اللون الأسود'],
            optionsEn: ['Worn on purity, covering ankles', 'New', 'Leather', 'Black color'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'يشترط لبسهما على طهارة كاملة وأن يسترا محل الفرض.',
            explanationEn: 'It is conditioned to wear them on full purity and they must cover the obligatory area.'
        },
        {
            id: 66,
            question: 'ما حكم الصلاة في الثوب النجس؟',
            questionEn: 'Ruling on praying in impure clothes?',
            options: ['لا تصح', 'تصح', 'تصح للضرورة', 'مكروهة'],
            optionsEn: ['Invalid', 'Valid', 'Valid if necessary', 'Disliked'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'طهارة الثوب والبدن والمكان شرط لصحة الصلاة.',
            explanationEn: 'Purity of clothes, body, and place is a condition for prayer validity.'
        },
        {
            id: 67,
            question: 'ماذا يفعل من شك في عدد الركعات؟',
            questionEn: 'What if one doubts the number of Rak\'ahs?',
            options: ['يبني على اليقين (الأقل)', 'يبني على الأكثر', 'يعيد الصلاة', 'يسأل من بجانبه'],
            optionsEn: ['Build on certainty (the lesser)', 'Build on more', 'Repeat prayer', 'Ask neighbor'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'إذا شك أحدكم فلم يدر كم صلى فليطرح الشك وليبن على ما استيقن.',
            explanationEn: 'If one doubts and doesn\'t know how much he prayed, cast aside doubt and build on certainty.'
        },
        {
            id: 68,
            question: 'ما هو سجود السهو؟',
            questionEn: 'What is Sujud Sahw?',
            options: ['سجدتان لجبر النقص أو الزيادة أو الشك', 'سجدة واحدة', 'ثلاث سجدات', 'دعاء'],
            optionsEn: ['2 prostrations for lack/excess/doubt', '1 prostration', '3 prostrations', 'Dua'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'سجود السهو سجدتان قبل السلام أو بعده.',
            explanationEn: 'Sujud Sahw is two prostrations before or after Tasleem.'
        },
        {
            id: 69,
            question: 'ما حكم قراءة السورة بعد الفاتحة؟',
            questionEn: 'Ruling on reading Surah after Fatiha?',
            options: ['سنة', 'واجب', 'ركن', 'شرط'],
            optionsEn: ['Sunnah', 'Obligatory', 'Pillar', 'Condition'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'قراءة سورة بعد الفاتحة سنة في الركعتين الأوليين.',
            explanationEn: 'Reading a Surah after Fatiha is Sunnah in the first two Rak\'ahs.'
        },
        {
            id: 70,
            question: 'ما حكم الجهر في الصلاة الجهرية؟',
            questionEn: 'Ruling on reciting aloud in loud prayers?',
            options: ['سنة', 'واجب', 'ركن', 'مكروه'],
            optionsEn: ['Sunnah', 'Obligatory', 'Pillar', 'Disliked'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'الجهر في موضعه سنة للإمام والمنفرد.',
            explanationEn: 'Reciting aloud in its place is Sunnah for the Imam and individual.'
        },
        {
            id: 71,
            question: 'ما حكم التأمين (قول آمين)؟',
            questionEn: 'Ruling on saying Ameen?',
            options: ['سنة', 'واجب', 'بدعة', 'مكروه'],
            optionsEn: ['Sunnah', 'Obligatory', 'Innovation', 'Disliked'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'إذا أمن الإمام فأمنوا.',
            explanationEn: 'If the Imam says Ameen, then say Ameen.'
        },
        {
            id: 72,
            question: 'ما حكم وضع اليد اليمنى على اليسرى؟',
            questionEn: 'Ruling on placing right hand over left?',
            options: ['سنة', 'واجب', 'ركن', 'مكروه'],
            optionsEn: ['Sunnah', 'Obligatory', 'Pillar', 'Disliked'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'من السنة وضع اليد اليمنى على اليسرى على الصدر في القيام.',
            explanationEn: 'It is Sunnah to place the right hand over the left on the chest while standing.'
        },
        {
            id: 73,
            question: 'ما حكم رفع اليدين عند التكبير؟',
            questionEn: 'Ruling on raising hands at Takbir?',
            options: ['سنة في 4 مواضع', 'واجب', 'ركن', 'مكروه'],
            optionsEn: ['Sunnah in 4 places', 'Obligatory', 'Pillar', 'Disliked'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'ترفع اليدين عند الإحرام، والركوع، والرفع منه، والقيام للثالثة.',
            explanationEn: 'Hands are raised at Ihram, Ruku, rising from it, and standing for the third.'
        },
        {
            id: 74,
            question: 'ما حكم الطمأنينة في الصلاة؟',
            questionEn: 'Ruling on tranquility (Tuma\'ninah)?',
            options: ['ركن لا تصح الصلاة بدونه', 'سنة', 'واجب', 'مستحب'],
            optionsEn: ['Pillar, invalid without it', 'Sunnah', 'Obligatory', 'Recommended'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'ارجع فصل فإنك لم تصل (للمسيء صلاته لعدم الطمأنينة).',
            explanationEn: 'Go back and pray, for you have not prayed (to the one who prayed badly due to lack of tranquility).'
        },
        {
            id: 75,
            question: 'ما حكم الصلاة في السيارة؟',
            questionEn: 'Ruling on praying in a car?',
            options: ['تصح للنافلة، وللفريضة عند الضرورة القصوى', 'لا تصح أبداً', 'تصح دائماً', 'مكروهة'],
            optionsEn: ['Valid for Nafl, Fard only extreme necessity', 'Never valid', 'Always valid', 'Disliked'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'تصح النافلة على الراحلة، أما الفريضة فلا بد من النزول إلا لضرورة.',
            explanationEn: 'Nafl is valid on a mount/vehicle, but for Fard one must get down unless necessary.'
        }
    ]
};
