import { QuizLevel } from '../quizTypes';

export const level5: QuizLevel = {
    id: 5,
    titleAr: 'الآداب والأدعية',
    titleEn: 'Manners & Duas',
    description: 'تعلم الآداب الإسلامية والأدعية اليومية المهمة',
    descriptionEn: 'Learn important Islamic manners and daily Duas',
    requiredScore: 70,
    questions: [
        // Etiquette of Eating & Drinking
        {
            id: 1,
            question: 'ماذا نقول قبل الأكل؟',
            questionEn: 'What do we say before eating?',
            options: ['بسم الله', 'الحمد لله', 'الله أكبر', 'سبحان الله'],
            optionsEn: ['Bismillah', 'Alhamdulillah', 'Allahu Akbar', 'SubhanAllah'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'نقول "بسم الله" قبل البدء في الطعام.',
            explanationEn: 'We say "Bismillah" before starting to eat.'
        },
        {
            id: 2,
            question: 'بأي يد نأكل؟',
            questionEn: 'With which hand do we eat?',
            options: ['باليد اليمنى', 'باليد اليسرى', 'بأي يد', 'بكلتا اليدين'],
            optionsEn: ['Right hand', 'Left hand', 'Any hand', 'Both hands'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'أمرنا النبي ﷺ بالأكل باليمين.',
            explanationEn: 'The Prophet ﷺ commanded us to eat with the right hand.'
        },
        {
            id: 3,
            question: 'ماذا نقول بعد الانتهاء من الأكل؟',
            questionEn: 'What do we say after finishing eating?',
            options: ['الحمد لله', 'بسم الله', 'أستغفر الله', 'ما شاء الله'],
            optionsEn: ['Alhamdulillah', 'Bismillah', 'Astaghfirullah', 'MashaAllah'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'نحمد الله على نعمة الطعام بعد الانتهاء منه.',
            explanationEn: 'We praise Allah (Alhamdulillah) for the blessing of food after finishing.'
        },
        {
            id: 4,
            question: 'إذا نسينا التسمية في أول الطعام، ماذا نقول؟',
            questionEn: 'If we forget to say Bismillah at the start, what do we say?',
            options: ['بسم الله أوله وآخره', 'بسم الله', 'الحمد لله', 'لا شيء'],
            optionsEn: ['Bismillahi awwalahu wa akhirahu', 'Bismillah', 'Alhamdulillah', 'Nothing'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'إذا نسي أحدكم فليقل: بسم الله أوله وآخره.',
            explanationEn: 'If one of you forgets, let him say: Bismillahi awwalahu wa akhirahu (In the name of Allah at the beginning and at the end).'
        },
        {
            id: 5,
            question: 'هل يجوز النفخ في الطعام الساخن؟',
            questionEn: 'Is it permissible to blow on hot food?',
            options: ['لا، يكره ذلك', 'نعم، لتبريده', 'نعم، إذا كنت جائعاً', 'لا بأس به'],
            optionsEn: ['No, it is disliked', 'Yes, to cool it', 'Yes, if hungry', 'It is fine'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'نهى النبي ﷺ عن النفخ في الطعام والشراب.',
            explanationEn: 'The Prophet ﷺ forbade blowing into food and drink.'
        },
        {
            id: 6,
            question: 'من أين نأكل من الصحن؟',
            questionEn: 'From where should we eat in the plate?',
            options: ['من ما يلينا (أمامنا)', 'من وسط الصحن', 'من أمام غيرنا', 'من أي مكان'],
            optionsEn: ['From what is in front of us', 'From the middle', 'From in front of others', 'From anywhere'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'قال النبي ﷺ: "يا غلام، سم الله، وكل بيمينك، وكل مما يليك".',
            explanationEn: 'The Prophet ﷺ said: "O boy, say Bismillah, eat with your right hand, and eat from what is in front of you."'
        },
        {
            id: 7,
            question: 'هل يجوز عيب الطعام (ذمه)؟',
            questionEn: 'Is it permissible to criticize food?',
            options: ['لا، لا نعيب الطعام أبداً', 'نعم، إذا لم يعجبنا', 'نعم، إذا كان مالحاً', 'أحياناً'],
            optionsEn: ['No, never criticize food', 'Yes, if we don\'t like it', 'Yes, if it\'s salty', 'Sometimes'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'ما عاب النبي ﷺ طعاماً قط، إن اشتهاه أكله وإن كرهه تركه.',
            explanationEn: 'The Prophet ﷺ never criticized food; if he liked it, he ate it, and if he disliked it, he left it.'
        },
        // Etiquette of Sleeping
        {
            id: 8,
            question: 'ماذا نقول قبل النوم؟',
            questionEn: 'What do we say before sleeping?',
            options: ['باسمك اللهم أموت وأحيا', 'الحمد لله الذي أحيانا', 'سبحان الله', 'الله أكبر'],
            optionsEn: ['Bismika Allahumma amutu wa ahya', 'Alhamdulillahilladhi ahyana', 'SubhanAllah', 'Allahu Akbar'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'دعاء النوم: باسمك اللهم أموت وأحيا.',
            explanationEn: 'Sleep Dua: In Your name, O Allah, I die and I live.'
        },
        {
            id: 9,
            question: 'على أي جانب يسن النوم؟',
            questionEn: 'On which side is it Sunnah to sleep?',
            options: ['الجانب الأيمن', 'الجانب الأيسر', 'على البطن', 'على الظهر'],
            optionsEn: ['Right side', 'Left side', 'Stomach', 'Back'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'من السنة النوم على الشق الأيمن.',
            explanationEn: 'It is Sunnah to sleep on the right side.'
        },
        {
            id: 10,
            question: 'ماذا نقول عند الاستيقاظ من النوم؟',
            questionEn: 'What do we say when waking up?',
            options: ['الحمد لله الذي أحيانا بعدما أماتنا وإليه النشور', 'باسمك اللهم أموت وأحيا', 'سبحان الله', 'أستغفر الله'],
            optionsEn: ['Alhamdulillahilladhi ahyana ba\'dama amatana...', 'Bismika Allahumma...', 'SubhanAllah', 'Astaghfirullah'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'دعاء الاستيقاظ: الحمد لله الذي أحيانا بعدما أماتنا وإليه النشور.',
            explanationEn: 'Waking up Dua: All praise is due to Allah who gave us life after He had caused us to die and unto Him is the resurrection.'
        },
        {
            id: 11,
            question: 'ماذا نفعل قبل النوم؟',
            questionEn: 'What should we do before sleeping?',
            options: ['نتوضأ وننفض الفراش', 'نأكل كثيراً', 'نلعب', 'نصرخ'],
            optionsEn: ['Perform Wudu and dust the bed', 'Eat a lot', 'Play', 'Scream'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'من السنة الوضوء قبل النوم ونفض الفراش.',
            explanationEn: 'It is Sunnah to perform Wudu before sleep and dust the bed.'
        },
        {
            id: 12,
            question: 'ما هي آية الكرسي؟',
            questionEn: 'What is Ayat al-Kursi?',
            options: ['أعظم آية في القرآن، تقرأ قبل النوم', 'أقصر آية', 'أطول سورة', 'سورة الفاتحة'],
            optionsEn: ['Greatest verse, read before sleep', 'Shortest verse', 'Longest Surah', 'Surah Al-Fatiha'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'آية الكرسي هي أعظم آية وتحفظ المسلم عند النوم.',
            explanationEn: 'Ayat al-Kursi is the greatest verse and protects the Muslim during sleep.'
        },
        // Etiquette of Bathroom
        {
            id: 13,
            question: 'بأي قدم ندخل الخلاء (الحمام)؟',
            questionEn: 'With which foot do we enter the bathroom?',
            options: ['اليسرى', 'اليمنى', 'أي قدم', 'القفز'],
            optionsEn: ['Left', 'Right', 'Any foot', 'Jump'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'ندخل الخلاء بالقدم اليسرى.',
            explanationEn: 'We enter the bathroom with the left foot.'
        },
        {
            id: 14,
            question: 'بأي قدم نخرج من الخلاء؟',
            questionEn: 'With which foot do we exit the bathroom?',
            options: ['اليمنى', 'اليسرى', 'أي قدم', 'القفز'],
            optionsEn: ['Right', 'Left', 'Any foot', 'Jump'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'نخرج من الخلاء بالقدم اليمنى.',
            explanationEn: 'We exit the bathroom with the right foot.'
        },
        {
            id: 15,
            question: 'ماذا نقول قبل دخول الخلاء؟',
            questionEn: 'What do we say before entering the bathroom?',
            options: ['اللهم إني أعوذ بك من الخبث والخبائث', 'غفرانك', 'بسم الله', 'الحمد لله'],
            optionsEn: ['Allahumma inni a\'udhu bika minal khubuthi wal khaba\'ith', 'Ghufranak', 'Bismillah', 'Alhamdulillah'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'دعاء الدخول: اللهم إني أعوذ بك من الخبث والخبائث.',
            explanationEn: 'Entering Dua: O Allah, I seek refuge with You from male and female devils.'
        },
        {
            id: 16,
            question: 'ماذا نقول عند الخروج من الخلاء؟',
            questionEn: 'What do we say when exiting the bathroom?',
            options: ['غفرانك', 'الحمد لله', 'شكراً', 'سبحان الله'],
            optionsEn: ['Ghufranak', 'Alhamdulillah', 'Thanks', 'SubhanAllah'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'نقول "غفرانك" عند الخروج.',
            explanationEn: 'We say "Ghufranak" (I seek Your forgiveness) upon exiting.'
        },
        // Etiquette of Greeting
        {
            id: 17,
            question: 'ما هي تحية الإسلام؟',
            questionEn: 'What is the Islamic greeting?',
            options: ['السلام عليكم ورحمة الله وبركاته', 'صباح الخير', 'مرحباً', 'أهلاً'],
            optionsEn: ['As-salamu alaykum wa rahmatullahi wa barakatuh', 'Good morning', 'Hello', 'Hi'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'تحية الإسلام هي السلام عليكم ورحمة الله وبركاته.',
            explanationEn: 'The Islamic greeting is As-salamu alaykum wa rahmatullahi wa barakatuh.'
        },
        {
            id: 18,
            question: 'كم حسنة لمن قال "السلام عليكم ورحمة الله وبركاته"؟',
            questionEn: 'How many rewards for saying "As-salamu alaykum wa rahmatullahi wa barakatuh"?',
            options: ['30 حسنة', '10 حسنات', '20 حسنة', '50 حسنة'],
            optionsEn: ['30 rewards', '10 rewards', '20 rewards', '50 rewards'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'السلام عليكم (10)، ورحمة الله (20)، وبركاته (30).',
            explanationEn: 'As-salamu alaykum (10), wa rahmatullah (20), wa barakatuh (30).'
        },
        {
            id: 19,
            question: 'من يبدأ بالسلام؟',
            questionEn: 'Who should start the greeting?',
            options: ['الراكب على الماشي، والصغير على الكبير', 'الكبير على الصغير', 'الماشي على الراكب', 'لا يهم'],
            optionsEn: ['Rider to walker, young to old', 'Old to young', 'Walker to rider', 'Doesn\'t matter'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'يسلم الراكب على الماشي، والماشي على القاعد، والقليل على الكثير، والصغير على الكبير.',
            explanationEn: 'The rider greets the walker, the walker greets the sitter, the few greet the many, and the young greet the old.'
        },
        {
            id: 20,
            question: 'هل يجوز الإشارة باليد فقط عند السلام؟',
            questionEn: 'Is it permissible to only wave without speaking when greeting?',
            options: ['لا، يجب التلفظ بالسلام', 'نعم، يكفي', 'نعم، للأصدقاء فقط', 'نعم، للأقارب'],
            optionsEn: ['No, must utter the Salam', 'Yes, it\'s enough', 'Yes, for friends only', 'Yes, for relatives'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'لا نكتفي بالإشارة، بل يجب التلفظ بالسلام، ويمكن الجمع بينهما للبعيد.',
            explanationEn: 'We should not just wave; we must utter the Salam. We can combine both if the person is far.'
        },
        // Etiquette with Parents
        {
            id: 21,
            question: 'ما حكم بر الوالدين؟',
            questionEn: 'What is the ruling on kindness to parents?',
            options: ['واجب', 'مستحب', 'مباح', 'مكروه'],
            optionsEn: ['Obligatory (Wajib)', 'Recommended', 'Permissible', 'Disliked'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'بر الوالدين واجب عظيم قرنه الله بعبادته.',
            explanationEn: 'Kindness to parents is a great obligation that Allah linked with worshipping Him.'
        },
        {
            id: 22,
            question: 'ماذا نقول للوالدين عند الغضب؟',
            questionEn: 'What do we say to parents when angry?',
            options: ['لا نقول لهما "أف"', 'نصرخ', 'نجادل', 'نخاصم'],
            optionsEn: ['Do not say "Uff"', 'Scream', 'Argue', 'Fight'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'قال الله تعالى: "فلا تقل لهما أف ولا تنهرهما".',
            explanationEn: 'Allah Almighty said: "Do not say to them \'Uff\' and do not repel them."'
        },
        {
            id: 23,
            question: 'كيف نتحدث مع الوالدين؟',
            questionEn: 'How do we speak to parents?',
            options: ['بصوت منخفض وأدب', 'بصوت عالٍ', 'بأوامر', 'بتكبر'],
            optionsEn: ['Softly and politely', 'Loudly', 'With orders', 'Arrogantly'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'وقل لهما قولاً كريماً واخفض لهما جناح الذل من الرحمة.',
            explanationEn: 'And speak to them a noble word and lower to them the wing of humility out of mercy.'
        },
        {
            id: 24,
            question: 'ماذا نفعل إذا طلب الوالدان شيئاً؟',
            questionEn: 'What do we do if parents ask for something?',
            options: ['نسارع في تلبيته', 'نؤجله', 'نرفض', 'نتذمر'],
            optionsEn: ['Hurry to fulfill it', 'Delay it', 'Refuse', 'Complain'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'طاعة الوالدين واجبة في غير معصية الله.',
            explanationEn: 'Obedience to parents is obligatory in matters that are not disobedience to Allah.'
        },
        // Etiquette of Sneezing
        {
            id: 25,
            question: 'ماذا نقول عند العطس؟',
            questionEn: 'What do we say when sneezing?',
            options: ['الحمد لله', 'يرحمك الله', 'سبحان الله', 'أستغفر الله'],
            optionsEn: ['Alhamdulillah', 'YarhamukAllah', 'SubhanAllah', 'Astaghfirullah'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'إذا عطس أحدكم فليقل الحمد لله.',
            explanationEn: 'If one of you sneezes, let him say Alhamdulillah.'
        },
        {
            id: 26,
            question: 'ماذا يقول من سمع العاطس يحمد الله؟',
            questionEn: 'What does the one who hears the sneezer praise Allah say?',
            options: ['يرحمك الله', 'يهديكم الله', 'الحمد لله', 'شكراً'],
            optionsEn: ['YarhamukAllah', 'Yahdikumullah', 'Alhamdulillah', 'Thanks'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'إذا حمد الله فشمته (قل له يرحمك الله).',
            explanationEn: 'If he praises Allah, then respond to him (say YarhamukAllah).'
        },
        {
            id: 27,
            question: 'ماذا يرد العاطس على من شمتة؟',
            questionEn: 'What does the sneezer reply to the one who responded?',
            options: ['يهديكم الله ويصلح بالكم', 'شكراً', 'وأنت كذلك', 'مع السلامة'],
            optionsEn: ['Yahdikumullah wa yuslih balakum', 'Thanks', 'You too', 'Bye'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'يقول: يهديكم الله ويصلح بالكم.',
            explanationEn: 'He says: May Allah guide you and improve your condition.'
        },
        {
            id: 28,
            question: 'ماذا نفعل عند العطس؟',
            questionEn: 'What do we do when sneezing?',
            options: ['نغطي وجهنا ونخفض صوتنا', 'نرفع صوتنا', 'نعطس في وجه الآخرين', 'لا شيء'],
            optionsEn: ['Cover face and lower voice', 'Raise voice', 'Sneeze in others\' faces', 'Nothing'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'كان النبي ﷺ إذا عطس غطى وجهه بيده أو بثوبه وغض بها صوته.',
            explanationEn: 'The Prophet ﷺ used to cover his face with his hand or garment and lower his voice when sneezing.'
        },
        // Daily Duas
        {
            id: 29,
            question: 'ما هو دعاء الخروج من المنزل؟',
            questionEn: 'What is the Dua for leaving the house?',
            options: ['بسم الله توكلت على الله ولا حول ولا قوة إلا بالله', 'بسم الله ولجنا', 'الحمد لله', 'سبحان الله'],
            optionsEn: ['Bismillah tawakkaltu ala Allah...', 'Bismillah walajna', 'Alhamdulillah', 'SubhanAllah'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'من قالها كفي ووقي وهدي وتنحى عنه الشيطان.',
            explanationEn: 'Whoever says it is sufficed, protected, guided, and Shaytan moves away from him.'
        },
        {
            id: 30,
            question: 'ما هو دعاء دخول المنزل؟',
            questionEn: 'What is the Dua for entering the house?',
            options: ['بسم الله ولجنا وبسم الله خرجنا وعلى ربنا توكلنا', 'بسم الله توكلت على الله', 'الحمد لله', 'السلام عليكم'],
            optionsEn: ['Bismillah walajna wa bismillah kharajna...', 'Bismillah tawakkaltu...', 'Alhamdulillah', 'As-salamu alaykum'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'يسن ذكر الله عند الدخول والسلام على الأهل.',
            explanationEn: 'It is Sunnah to mention Allah upon entering and greet the family.'
        },
        {
            id: 31,
            question: 'ما هو دعاء دخول المسجد؟',
            questionEn: 'What is the Dua for entering the mosque?',
            options: ['اللهم افتح لي أبواب رحمتك', 'اللهم إني أسألك من فضلك', 'غفرانك', 'بسم الله'],
            optionsEn: ['Allahumma iftah li abwaba rahmatik', 'Allahumma inni as\'aluka min fadlik', 'Ghufranak', 'Bismillah'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'عند الدخول نقول: اللهم افتح لي أبواب رحمتك.',
            explanationEn: 'Upon entering we say: O Allah, open for me the doors of Your mercy.'
        },
        {
            id: 32,
            question: 'ما هو دعاء الخروج من المسجد؟',
            questionEn: 'What is the Dua for leaving the mosque?',
            options: ['اللهم إني أسألك من فضلك', 'اللهم افتح لي أبواب رحمتك', 'غفرانك', 'الحمد لله'],
            optionsEn: ['Allahumma inni as\'aluka min fadlik', 'Allahumma iftah li...', 'Ghufranak', 'Alhamdulillah'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'عند الخروج نقول: اللهم إني أسألك من فضلك.',
            explanationEn: 'Upon leaving we say: O Allah, I ask You from Your bounty.'
        },
        {
            id: 33,
            question: 'ماذا نقول عند سماع الديك؟',
            questionEn: 'What do we say when hearing a rooster?',
            options: ['نسأل الله من فضله', 'نتعوذ من الشيطان', 'نسبح', 'نكبر'],
            optionsEn: ['Ask Allah for His bounty', 'Seek refuge from Shaytan', 'Glorify Allah', 'Say Allahu Akbar'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'إذا سمعتم صياح الديكة فاسألوا الله من فضله فإنها رأت ملكاً.',
            explanationEn: 'If you hear the crowing of roosters, ask Allah for His bounty, for they have seen an angel.'
        },
        {
            id: 34,
            question: 'ماذا نقول عند سماع نباح الكلب؟',
            questionEn: 'What do we say when hearing a dog bark?',
            options: ['نتعوذ بالله من الشيطان الرجيم', 'نسبح', 'نحمد الله', 'نسأل الله من فضله'],
            optionsEn: ['Seek refuge in Allah from Shaytan', 'Glorify Allah', 'Praise Allah', 'Ask for bounty'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'إذا سمعتم نباح الكلاب فتعوذوا بالله من الشيطان فإنها ترى ما لا ترون.',
            explanationEn: 'If you hear the barking of dogs, seek refuge in Allah from Shaytan, for they see what you do not see.'
        },
        {
            id: 35,
            question: 'ماذا نقول لمن صنع لنا معروفاً؟',
            questionEn: 'What do we say to someone who does us a favor?',
            options: ['جزاك الله خيراً', 'شكراً', 'عفواً', 'أحسنت'],
            optionsEn: ['JazakAllahu Khairan', 'Thanks', 'Welcome', 'Well done'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'من قال لأخيه جزاك الله خيراً فقد أبلغ في الثناء.',
            explanationEn: 'Whoever says to his brother "JazakAllahu Khairan" has expressed the utmost praise.'
        },
        {
            id: 36,
            question: 'ما هو دعاء ركوب الدابة (أو السيارة)؟',
            questionEn: 'What is the Dua for riding (or driving)?',
            options: ['سبحان الذي سخر لنا هذا وما كنا له مقرنين', 'بسم الله مجريها', 'الحمد لله', 'الله أكبر'],
            optionsEn: ['Subhanalladhi sakhara lana hadha...', 'Bismillah majreeha', 'Alhamdulillah', 'Allahu Akbar'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'دعاء الركوب: سبحان الذي سخر لنا هذا وما كنا له مقرنين وإنا إلى ربنا لمنقلبون.',
            explanationEn: 'Riding Dua: Glory be to Him who has subjected this to us, and we could not have otherwise subdued it.'
        },
        {
            id: 37,
            question: 'ماذا نقول عند الغضب؟',
            questionEn: 'What do we say when angry?',
            options: ['أعوذ بالله من الشيطان الرجيم', 'اللعنة', 'تباً', 'أف'],
            optionsEn: ['A\'udhu billahi minash-shaytanir-rajim', 'Curse', 'Darn', 'Uff'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'الغضب من الشيطان، فنتعوذ بالله منه ليذهب الغضب.',
            explanationEn: 'Anger is from Shaytan, so we seek refuge in Allah from him to remove the anger.'
        },
        {
            id: 38,
            question: 'ماذا نقول عند رؤية المبتلى (المريض أو المعاق)؟',
            questionEn: 'What do we say when seeing an afflicted person?',
            options: ['الحمد لله الذي عافاني مما ابتلاك به', 'سبحان الله', 'مسكين', 'لماذا هو هكذا'],
            optionsEn: ['Alhamdulillahilladhi afani...', 'SubhanAllah', 'Poor guy', 'Why is he like this'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'الحمد لله الذي عافاني مما ابتلاك به وفضلني على كثير ممن خلق تفضيلاً.',
            explanationEn: 'Praise be to Allah who has spared me from what He has afflicted you with and preferred me greatly above much of what He has created.'
        },
        {
            id: 39,
            question: 'ما هو كفارة المجلس؟',
            questionEn: 'What is the expiation of the gathering (Kaffaratul Majlis)?',
            options: ['سبحانك اللهم وبحمدك أشهد أن لا إله إلا أنت أستغفرك وأتوب إليك', 'الحمد لله', 'مع السلامة', 'إلى اللقاء'],
            optionsEn: ['Subhanaka Allahumma wa bihamdika...', 'Alhamdulillah', 'Bye', 'See you'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'يقولها المسلم عند القيام من المجلس ليغفر الله له ما كان فيه من لغو.',
            explanationEn: 'A Muslim says it when standing up from a gathering so Allah forgives any idle talk that occurred.'
        },
        {
            id: 40,
            question: 'ماذا نقول عند لبس الثوب الجديد؟',
            questionEn: 'What do we say when wearing new clothes?',
            options: ['اللهم لك الحمد أنت كسوتنيه', 'بسم الله', 'جميل', 'شكراً'],
            optionsEn: ['Allahumma lakal hamd anta kasawtanihi', 'Bismillah', 'Nice', 'Thanks'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'اللهم لك الحمد أنت كسوتنيه، أسألك من خيره وخير ما صنع له.',
            explanationEn: 'O Allah, praise be to You, You have clothed me with it. I ask You for its good and the good of what it was made for.'
        },
        {
            id: 41,
            question: 'ما حكم إماطة الأذى عن الطريق؟',
            questionEn: 'What is the ruling on removing harmful objects from the road?',
            options: ['صدقة', 'واجب', 'مكروه', 'حرام'],
            optionsEn: ['Charity (Sadaqah)', 'Obligatory', 'Disliked', 'Forbidden'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'إماطة الأذى عن الطريق صدقة وشعبة من شعب الإيمان.',
            explanationEn: 'Removing harmful objects from the road is charity and a branch of faith.'
        },
        {
            id: 42,
            question: 'ماذا نقول عند زيارة المريض؟',
            questionEn: 'What do we say when visiting the sick?',
            options: ['لا بأس طهور إن شاء الله', 'سلامتك', 'الله يشفيك', 'كيف حالك'],
            optionsEn: ['La ba\'s tahur inshaAllah', 'Get well soon', 'Allah cure you', 'How are you'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'كان النبي ﷺ يقول للمريض: لا بأس طهور إن شاء الله.',
            explanationEn: 'The Prophet ﷺ used to say to the sick: No harm, purification (from sins) if Allah wills.'
        },
        {
            id: 43,
            question: 'ما هو حق المسلم على المسلم؟',
            questionEn: 'What are the rights of a Muslim upon another Muslim?',
            options: ['خمس (أو ست)', 'ثلاث', 'عشرة', 'واحدة'],
            optionsEn: ['Five (or Six)', 'Three', 'Ten', 'One'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'حق المسلم على المسلم خمس: رد السلام، وعيادة المريض، واتباع الجنائز، وإجابة الدعوة، وتشميت العاطس.',
            explanationEn: 'The rights are five: returning Salam, visiting the sick, following funerals, accepting invitations, and responding to the sneezer.'
        },
        {
            id: 44,
            question: 'ماذا نقول عند دخول السوق؟',
            questionEn: 'What do we say when entering the market?',
            options: ['لا إله إلا الله وحده لا شريك له...', 'بسم الله', 'السلام عليكم', 'يا رب'],
            optionsEn: ['La ilaha illallah wahdahu la sharika lah...', 'Bismillah', 'As-salamu alaykum', 'Oh Lord'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'من قال دعاء السوق كتب الله له ألف ألف حسنة ومحا عنه ألف ألف سيئة.',
            explanationEn: 'Whoever says the market Dua, Allah writes for him a million good deeds and erases a million bad deeds.'
        },
        {
            id: 45,
            question: 'ماذا نفعل قبل قراءة القرآن؟',
            questionEn: 'What do we do before reading Quran?',
            options: ['نستعيذ بالله من الشيطان الرجيم', 'نأكل', 'ننام', 'نتكلم'],
            optionsEn: ['Seek refuge in Allah from Shaytan', 'Eat', 'Sleep', 'Talk'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'فإذا قرأت القرآن فاستعذ بالله من الشيطان الرجيم.',
            explanationEn: 'So when you recite the Quran, seek refuge in Allah from the accursed Satan.'
        },
        {
            id: 46,
            question: 'هل يجوز التجسس على الآخرين؟',
            questionEn: 'Is spying on others permissible?',
            options: ['لا، حرام', 'نعم، للمعرفه', 'نعم، للتسلية', 'أحياناً'],
            optionsEn: ['No, forbidden', 'Yes, to know', 'Yes, for fun', 'Sometimes'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'قال الله تعالى: "ولا تجسسوا".',
            explanationEn: 'Allah Almighty said: "And do not spy."'
        },
        {
            id: 47,
            question: 'ما حكم الغيبة؟',
            questionEn: 'What is the ruling on backbiting (Ghibah)?',
            options: ['حرام، كأكل لحم الأخ ميتاً', 'مكروه', 'مباح', 'جائز'],
            optionsEn: ['Forbidden, like eating dead brother\'s flesh', 'Disliked', 'Permissible', 'Allowed'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'ولا يغتب بعضكم بعضاً أيحب أحدكم أن يأكل لحم أخيه ميتاً فكرهتموه.',
            explanationEn: 'And do not backbite each other. Would one of you like to eat the flesh of his dead brother? You would detest it.'
        },
        {
            id: 48,
            question: 'ما هي النميمة؟',
            questionEn: 'What is Namimah (tale-bearing)?',
            options: ['نقل الكلام بين الناس للإفساد', 'الكذب', 'السرقة', 'الضرب'],
            optionsEn: ['Transferring speech to cause corruption', 'Lying', 'Stealing', 'Hitting'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'النميمة هي نقل الكلام بين الناس على جهة الإفساد، وهي من الكبائر.',
            explanationEn: 'Namimah is transferring speech between people to cause trouble, and it is a major sin.'
        },
        {
            id: 49,
            question: 'ماذا نقول عند هبوب الريح؟',
            questionEn: 'What do we say when the wind blows?',
            options: ['اللهم إني أسألك خيرها وخير ما فيها', 'سبحان الله', 'يا لطيف', 'نخاف'],
            optionsEn: ['Allahumma inni as\'aluka khairaha...', 'SubhanAllah', 'Ya Latif', 'We fear'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'كان النبي ﷺ يسأل الله خيرها وخير ما أرسلت به ويتعوذ من شرها.',
            explanationEn: 'The Prophet ﷺ used to ask Allah for its good and the good sent with it, and seek refuge from its evil.'
        },
        {
            id: 50,
            question: 'ماذا نقول عند سماع الرعد؟',
            questionEn: 'What do we say when hearing thunder?',
            options: ['سبحان الذي يسبح الرعد بحمده والملائكة من خيفته', 'الله أكبر', 'يا رب', 'نصرخ'],
            optionsEn: ['Subhanalladhi yusabbihur-ra\'du bihamdihi...', 'Allahu Akbar', 'Oh Lord', 'Scream'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'كان ابن الزبير يترك الحديث ويقول هذا الدعاء عند سماع الرعد.',
            explanationEn: 'Ibn Al-Zubayr would stop talking and say this Dua when hearing thunder.'
        },
        {
            id: 51,
            question: 'ماذا نقول عند نزول المطر؟',
            questionEn: 'What do we say when it rains?',
            options: ['اللهم صيباً نافعاً', 'مطر مطر', 'الحمد لله', 'سبحان الله'],
            optionsEn: ['Allahumma sayyiban nafi\'an', 'Rain Rain', 'Alhamdulillah', 'SubhanAllah'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'كان النبي ﷺ يقول: اللهم صيباً نافعاً.',
            explanationEn: 'The Prophet ﷺ used to say: O Allah, make it a beneficial downpour.'
        },
        {
            id: 52,
            question: 'ماذا نقول للمسافر؟',
            questionEn: 'What do we say to a traveler?',
            options: ['أستودع الله دينك وأمانتك وخواتيم عملك', 'مع السلامة', 'رافقتك السلامة', 'إلى اللقاء'],
            optionsEn: ['Astawdi\'ullaha dinaka...', 'Bye', 'Safe travels', 'See you'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'هذا هو الدعاء المأثور لوداع المسافر.',
            explanationEn: 'This is the narrated Dua for bidding farewell to a traveler.'
        },
        {
            id: 53,
            question: 'ماذا يقول المسافر للمقيم؟',
            questionEn: 'What does the traveler say to the resident?',
            options: ['أستودعكم الله الذي لا تضيع ودائعه', 'مع السلامة', 'باي', 'سأشتاق لكم'],
            optionsEn: ['Astawdi\'ukumullaha...', 'Bye', 'Bye', 'I will miss you'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'يقول المسافر: أستودعكم الله الذي لا تضيع ودائعه.',
            explanationEn: 'The traveler says: I entrust you to Allah whose deposits are not lost.'
        },
        {
            id: 54,
            question: 'ماذا نقول عند رؤية الهلال؟',
            questionEn: 'What do we say when seeing the crescent moon?',
            options: ['اللهم أهله علينا بالأمن والإيمان', 'هلال خير', 'رمضان كريم', 'جميل'],
            optionsEn: ['Allahumma ahillahu alayna bil-amni wal-iman', 'Good crescent', 'Ramadan Kareem', 'Beautiful'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'كان النبي ﷺ يدعو بالبركة والإيمان عند رؤية الهلال.',
            explanationEn: 'The Prophet ﷺ used to pray for blessings and faith upon seeing the crescent.'
        },
        {
            id: 55,
            question: 'ماذا نقول قبل الجماع (للمتزوجين)؟',
            questionEn: 'What is said before intimacy (for married couples)?',
            options: ['بسم الله اللهم جنبنا الشيطان وجنب الشيطان ما رزقتنا', 'بسم الله', 'الحمد لله', 'لا شيء'],
            optionsEn: ['Bismillah Allahumma jannibnash-shaytan...', 'Bismillah', 'Alhamdulillah', 'Nothing'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'من قالها ورزق ولداً لم يضره الشيطان أبداً.',
            explanationEn: 'Whoever says it and is granted a child, Shaytan will never harm him.'
        },
        {
            id: 56,
            question: 'ماذا نفعل إذا تثاءبنا؟',
            questionEn: 'What do we do if we yawn?',
            options: ['نكظم ما استطعنا ونضع يدنا على فمنا', 'نفتح فمنا واسعاً', 'نصدر صوتاً', 'لا شيء'],
            optionsEn: ['Suppress it and cover mouth', 'Open mouth wide', 'Make noise', 'Nothing'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'التثاؤب من الشيطان، فإذا تثاءب أحدكم فليرده ما استطاع.',
            explanationEn: 'Yawning is from Shaytan, so if one of you yawns, let him suppress it as much as possible.'
        },
        {
            id: 57,
            question: 'هل يجوز الكذب للمزاح؟',
            questionEn: 'Is lying permissible for joking?',
            options: ['لا، لا يجوز', 'نعم، ليضحك الناس', 'نعم، كذبة بيضاء', 'أحياناً'],
            optionsEn: ['No, not permissible', 'Yes, to make people laugh', 'Yes, white lie', 'Sometimes'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'ويل للذي يحدث فيكذب ليضحك به القوم، ويل له ويل له.',
            explanationEn: 'Woe to the one who speaks and lies to make people laugh, woe to him, woe to him.'
        },
        {
            id: 58,
            question: 'ماذا نقول عند الفزع أو الخوف؟',
            questionEn: 'What do we say when scared or startled?',
            options: ['لا إله إلا الله', 'يا ماما', 'يا إلهي', 'النجدة'],
            optionsEn: ['La ilaha illallah', 'Mommy', 'Oh my God', 'Help'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'ذكر الله يطرد الخوف ويجلب الطمأنينة.',
            explanationEn: 'Remembering Allah drives away fear and brings tranquility.'
        },
        {
            id: 59,
            question: 'ماذا نقول عند التعجب؟',
            questionEn: 'What do we say when amazed?',
            options: ['سبحان الله / الله أكبر', 'واو', 'يا لهوي', 'عجيب'],
            optionsEn: ['SubhanAllah / Allahu Akbar', 'Wow', 'Oh my', 'Strange'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'كان النبي ﷺ يسبح أو يكبر عند التعجب.',
            explanationEn: 'The Prophet ﷺ used to glorify Allah (SubhanAllah) or magnify Him (Allahu Akbar) when amazed.'
        },
        {
            id: 60,
            question: 'ماذا نقول لمن أحسن إلينا؟',
            questionEn: 'What do we say to someone who is good to us?',
            options: ['جزاك الله خيراً', 'شكراً', 'ثانك يو', 'ميرسي'],
            optionsEn: ['JazakAllahu Khairan', 'Thanks', 'Thank you', 'Merci'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'جزاك الله خيراً هي أفضل مكافأة بالدعاء.',
            explanationEn: 'JazakAllahu Khairan is the best reward through supplication.'
        },
        {
            id: 61,
            question: 'ماذا نقول عند المصيبة؟',
            questionEn: 'What do we say during a calamity?',
            options: ['إنا لله وإنا إليه راجعون', 'لماذا يا رب', 'يا ويلي', 'حرام'],
            optionsEn: ['Inna lillahi wa inna ilayhi raji\'un', 'Why God', 'Oh woe', 'Unfair'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'الذين إذا أصابتهم مصيبة قالوا إنا لله وإنا إليه راجعون.',
            explanationEn: 'Who, when disaster strikes them, say, "Indeed we belong to Allah, and indeed to Him we will return."'
        },
        {
            id: 62,
            question: 'ماذا نقول عند ذبح الأضحية؟',
            questionEn: 'What do we say when slaughtering a sacrifice?',
            options: ['بسم الله والله أكبر', 'بسم الله', 'الله أكبر', 'الحمد لله'],
            optionsEn: ['Bismillah Wallahu Akbar', 'Bismillah', 'Allahu Akbar', 'Alhamdulillah'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'نسمي الله ونكبر عند الذبح.',
            explanationEn: 'We mention Allah\'s name and magnify Him when slaughtering.'
        },
        {
            id: 63,
            question: 'ماذا نقول في سجود التلاوة؟',
            questionEn: 'What do we say in Sujud at-Tilawah?',
            options: ['سجد وجهي للذي خلقه وصوره وشق سمعه وبصره', 'سبحان ربي الأعلى', 'سبحان الله', 'الله أكبر'],
            optionsEn: ['Sajada wajhi lilladhi khalaqahu...', 'Subhana Rabbiyal A\'la', 'SubhanAllah', 'Allahu Akbar'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'هذا هو الدعاء المأثور لسجود التلاوة.',
            explanationEn: 'This is the narrated Dua for the prostration of recitation.'
        },
        {
            id: 64,
            question: 'ماذا نقول عند زيارة القبور؟',
            questionEn: 'What do we say when visiting graves?',
            options: ['السلام عليكم أهل الديار من المؤمنين والمسلمين...', 'مرحباً', 'كيف حالكم', 'وداعاً'],
            optionsEn: ['As-salamu alaykum ahlad-diyar...', 'Hello', 'How are you', 'Goodbye'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'نسلم عليهم وندعو لهم ولنا بالعافية.',
            explanationEn: 'We greet them and pray for their and our well-being.'
        },
        {
            id: 65,
            question: 'ماذا نقول عند الانتهاء من الوضوء؟',
            questionEn: 'What do we say after finishing Wudu?',
            options: ['أشهد أن لا إله إلا الله... اللهم اجعلني من التوابين...', 'الحمد لله', 'نعيماً', 'شكراً'],
            optionsEn: ['Ashhadu an la ilaha illallah... Allahummaj\'alni minat-tawwabin...', 'Alhamdulillah', 'Na\'eeman', 'Thanks'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'من قالها فتحت له أبواب الجنة الثمانية.',
            explanationEn: 'Whoever says it, the eight gates of Paradise are opened for him.'
        },
        {
            id: 66,
            question: 'ماذا نقول عند سماع الأذان؟',
            questionEn: 'What do we say when hearing the Adhan?',
            options: ['نقول مثل ما يقول المؤذن', 'نسكت فقط', 'نتكلم', 'نقرأ القرآن'],
            optionsEn: ['Repeat what the Muazzin says', 'Just stay silent', 'Talk', 'Read Quran'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'نردد خلف المؤذن إلا في الحيعلتين نقول "لا حول ولا قوة إلا بالله".',
            explanationEn: 'We repeat after the Muazzin, except for Hayya alas-Salah/Falah, we say "La hawla wa la quwwata illa billah".'
        },
        {
            id: 67,
            question: 'ماذا نقول بعد الأذان؟',
            questionEn: 'What do we say after the Adhan?',
            options: ['اللهم رب هذه الدعوة التامة...', 'الحمد لله', 'سبحان الله', 'الله أكبر'],
            optionsEn: ['Allahumma Rabba hadhihid-da\'watit-tammah...', 'Alhamdulillah', 'SubhanAllah', 'Allahu Akbar'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'من قالها حلت له شفاعة النبي ﷺ.',
            explanationEn: 'Whoever says it will be granted the intercession of the Prophet ﷺ.'
        },
        {
            id: 68,
            question: 'ماذا نقول في الصباح؟',
            questionEn: 'What do we say in the morning?',
            options: ['أصبحنا وأصبح الملك لله', 'مساء الخير', 'تصبح على خير', 'مرحباً'],
            optionsEn: ['Asbahna wa asbahal mulku lillah', 'Good evening', 'Good night', 'Hello'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'من أذكار الصباح: أصبحنا وأصبح الملك لله.',
            explanationEn: 'From morning Adhkar: We have entered the morning and the dominion belongs to Allah.'
        },
        {
            id: 69,
            question: 'ماذا نقول في المساء؟',
            questionEn: 'What do we say in the evening?',
            options: ['أمسينا وأمسى الملك لله', 'صباح الخير', 'أهلاً', 'نعيماً'],
            optionsEn: ['Amsayna wa amsal mulku lillah', 'Good morning', 'Hello', 'Na\'eeman'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'من أذكار المساء: أمسينا وأمسى الملك لله.',
            explanationEn: 'From evening Adhkar: We have entered the evening and the dominion belongs to Allah.'
        },
        {
            id: 70,
            question: 'ماذا نقول عند الهم والحزن؟',
            questionEn: 'What do we say when anxious or sad?',
            options: ['اللهم إني عبدك ابن عبدك... (دعاء الهم)', 'أبكي', 'أصرخ', 'أنام'],
            optionsEn: ['Allahumma inni abduk... (Dua for anxiety)', 'Cry', 'Scream', 'Sleep'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'دعاء تفريج الهم والحزن الذي علمه النبي ﷺ لأصحابه.',
            explanationEn: 'The Dua for relieving anxiety and sorrow that the Prophet ﷺ taught his companions.'
        },
        {
            id: 71,
            question: 'ماذا نقول عند قضاء الدين؟',
            questionEn: 'What do we say when paying off debt?',
            options: ['اللهم اكفني بحلالك عن حرامك...', 'شكراً', 'الحمد لله', 'مبروك'],
            optionsEn: ['Allahummakfini bihalalika an haramik...', 'Thanks', 'Alhamdulillah', 'Congrats'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'دعاء قضاء الدين: اللهم اكفني بحلالك عن حرامك وأغنني بفضلك عمن سواك.',
            explanationEn: 'Debt payment Dua: O Allah, suffice me with Your lawful against Your prohibited, and make me independent of all those besides You.'
        },
        {
            id: 72,
            question: 'ماذا نقول لمن قال "إني أحبك في الله"؟',
            questionEn: 'What do we say to someone who says "I love you for the sake of Allah"?',
            options: ['أحبك الذي أحببتني له', 'شكراً', 'وأنا أيضاً', 'جيد'],
            optionsEn: ['Ahabbakal-ladhi ahbabtani lah', 'Thanks', 'Me too', 'Good'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'نقول: أحبك الذي أحببتني له.',
            explanationEn: 'We say: May He for Whose sake you love me, love you.'
        },
        {
            id: 73,
            question: 'ماذا نقول عند رؤية باكورة الثمر (أول الثمر)؟',
            questionEn: 'What do we say when seeing the first fruit?',
            options: ['اللهم بارك لنا في ثمرنا', 'جميل', 'لذيذ', 'الحمد لله'],
            optionsEn: ['Allahumma barik lana fi thamarina', 'Beautiful', 'Delicious', 'Alhamdulillah'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'كان النبي ﷺ يدعو بالبركة عند رؤية أول الثمر.',
            explanationEn: 'The Prophet ﷺ used to pray for blessings when seeing the first fruit.'
        },
        {
            id: 74,
            question: 'ماذا نقول إذا تعار (استيقظ) من الليل؟',
            questionEn: 'What do we say if we wake up suddenly at night?',
            options: ['لا إله إلا الله وحده لا شريك له... (ثم يدعو)', 'نعود للنوم', 'نشرب ماء', 'نخاف'],
            optionsEn: ['La ilaha illallah wahdahu... (then pray)', 'Go back to sleep', 'Drink water', 'Fear'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'من قالها ثم دعا استجيب له، فإن توضأ وصلى قبلت صلاته.',
            explanationEn: 'Whoever says it and then prays, it is answered; if he performs Wudu and prays, his prayer is accepted.'
        },
        {
            id: 75,
            question: 'ماذا نقول عند النظر في المرآة؟',
            questionEn: 'What do we say when looking in the mirror?',
            options: ['اللهم كما حسنت خلقي فحسن خلقي', 'أنا جميل', 'ما شاء الله', 'الحمد لله'],
            optionsEn: ['Allahumma kama hassanta khalqi fahassin khuluqi', 'I am beautiful', 'MashaAllah', 'Alhamdulillah'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'ندعو الله بتحسين الأخلاق كما حسن الخلقة.',
            explanationEn: 'We pray to Allah to beautify our character as He beautified our creation.'
        },
        {
            id: 76,
            question: 'ماذا نقول عند طنين الأذن؟',
            questionEn: 'What do we say when ears ring?',
            options: ['ذكر الله من ذكرني بخير', 'لا شيء', 'مزعج', 'نضرب الأذن'],
            optionsEn: ['May Allah mention who mentioned me with good', 'Nothing', 'Annoying', 'Hit ear'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'ورد في بعض الآثار: ذكر الله من ذكرني بخير.',
            explanationEn: 'It is reported in some traditions: May Allah mention who mentioned me with good.'
        },
        {
            id: 77,
            question: 'ماذا نقول عند استصعاب أمر؟',
            questionEn: 'What do we say when facing a difficulty?',
            options: ['اللهم لا سهل إلا ما جعلته سهلاً', 'يا رب', 'صعب جداً', 'مستحيل'],
            optionsEn: ['Allahumma la sahla illa ma ja\'altahu sahlan', 'Oh Lord', 'Very hard', 'Impossible'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'اللهم لا سهل إلا ما جعلته سهلاً وأنت تجعل الحزن إذا شئت سهلاً.',
            explanationEn: 'O Allah, there is no ease except in that which You have made easy, and You make the difficulty, if You wish, easy.'
        },
        {
            id: 78,
            question: 'ماذا نقول عند التهنئة بالمولود؟',
            questionEn: 'What do we say when congratulating for a newborn?',
            options: ['بورك لك في الموهوب وشكرت الواهب...', 'مبروك', 'يتربى في عزك', 'جميل'],
            optionsEn: ['Barakallahu laka fil-mawhub...', 'Congrats', 'Raise in glory', 'Beautiful'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'بورك لك في الموهوب وشكرت الواهب وبلغ أشده ورزقت بره.',
            explanationEn: 'May Allah bless you in His gift to you, may you give thanks to the Giver, may he reach maturity, and may you be granted his righteousness.'
        },
        {
            id: 79,
            question: 'ماذا نقول عند رؤية ما يعجبنا؟',
            questionEn: 'What do we say when seeing something we like?',
            options: ['ما شاء الله لا قوة إلا بالله', 'واو', 'رائع', 'أريده'],
            optionsEn: ['MashaAllah la quwwata illa billah', 'Wow', 'Awesome', 'I want it'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'لعدم إصابة العين نقول ما شاء الله لا قوة إلا بالله.',
            explanationEn: 'To prevent the evil eye, we say MashaAllah la quwwata illa billah.'
        },
        {
            id: 80,
            question: 'ماذا نقول في ختام المجلس؟',
            questionEn: 'What do we say at the end of a gathering?',
            options: ['سبحانك اللهم وبحمدك...', 'مع السلامة', 'باي', 'تصبحون على خير'],
            optionsEn: ['Subhanaka Allahumma wa bihamdika...', 'Bye', 'Bye', 'Good night'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'كفارة المجلس تمحو ما كان فيه من لغو.',
            explanationEn: 'The expiation of the gathering erases any idle talk that occurred in it.'
        }

    ]
};
