import { QuizLevel } from '../quizTypes';

export const level2: QuizLevel = {
    id: 2,
    titleAr: 'معاني الكلمات',
    titleEn: 'Word Meanings',
    description: 'تعلم معاني الكلمات الإسلامية الأساسية',
    descriptionEn: 'Learn meanings of basic Islamic words',
    icon: '📖',
    requiredScore: 70,
    questions: [
        // Basic Islamic Terms (1-20)
        {
            id: 201,
            question: 'ما معنى كلمة "الإسلام"؟',
            questionEn: 'What is the meaning of "Islam"?',
            options: ['الاستسلام لله', 'القراءة', 'الصيام', 'السفر'],
            optionsEn: ['Submission to Allah', 'Reading', 'Fasting', 'Traveling'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'الإسلام يعني الاستسلام والخضوع لأمر الله.',
            explanationEn: 'Islam means submission and surrender to the will of Allah.'
        },
        {
            id: 202,
            question: 'ما معنى "الله أكبر"؟',
            questionEn: 'What does "Allahu Akbar" mean?',
            options: ['الله أعظم من كل شيء', 'الله يحبنا', 'الله يرانا', 'الله خالقنا'],
            optionsEn: ['Allah is the Greatest', 'Allah loves us', 'Allah sees us', 'Allah is our Creator'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'الله أكبر تعني أن الله أعظم وأجل من أي شيء في الوجود.',
            explanationEn: 'Allahu Akbar means Allah is Greater than anything in existence.'
        },
        {
            id: 203,
            question: 'ما معنى "الحمد لله"؟',
            questionEn: 'What does "Alhamdulillah" mean?',
            options: ['الشكر والثناء لله', 'أستغفر الله', 'الله موجود', 'سبحان الله'],
            optionsEn: ['Praise be to Allah', 'I seek forgiveness', 'Allah exists', 'Glory to Allah'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'نقول الحمد لله لشكر الله على نعمه.',
            explanationEn: 'We say Alhamdulillah to praise and thank Allah for His blessings.'
        },
        {
            id: 204,
            question: 'ما معنى "سبحان الله"؟',
            questionEn: 'What does "SubhanAllah" mean?',
            options: ['تنزيه الله عن كل نقص', 'الله كريم', 'الله رحيم', 'الله قوي'],
            optionsEn: ['Glory be to Allah', 'Allah is Generous', 'Allah is Merciful', 'Allah is Strong'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'سبحان الله تعني تنزيه الله وتقديسه عن كل عيب ونقص.',
            explanationEn: 'SubhanAllah means declaring Allah perfect and free from any imperfection.'
        },
        {
            id: 205,
            question: 'ما معنى "أستغفر الله"؟',
            questionEn: 'What does "Astaghfirullah" mean?',
            options: ['أطلب المغفرة من الله', 'أحب الله', 'أشكر الله', 'أذكر الله'],
            optionsEn: ['I seek forgiveness from Allah', 'I love Allah', 'I thank Allah', 'I remember Allah'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'نقول أستغفر الله لطلب العفو والمغفرة من الله.',
            explanationEn: 'We say Astaghfirullah to ask Allah for forgiveness.'
        },
        {
            id: 206,
            question: 'ما معنى "لا إله إلا الله"؟',
            questionEn: 'What does "La ilaha illa Allah" mean?',
            options: ['لا معبود بحق إلا الله', 'الله موجود', 'الله في السماء', 'الله خلقنا'],
            optionsEn: ['There is no god but Allah', 'Allah exists', 'Allah is in heaven', 'Allah created us'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'هي كلمة التوحيد وتعني أنه لا يستحق العبادة إلا الله.',
            explanationEn: 'It is the statement of Tawheed, meaning none deserves worship except Allah.'
        },
        {
            id: 207,
            question: 'ما معنى "محمد رسول الله"؟',
            questionEn: 'What does "Muhammad Rasulullah" mean?',
            options: ['محمد مبعوث من الله', 'محمد رجل صالح', 'محمد قائد', 'محمد صديق'],
            optionsEn: ['Muhammad is the Messenger of Allah', 'Muhammad is a good man', 'Muhammad is a leader', 'Muhammad is a friend'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'تعني أن الله أرسل محمداً صلى الله عليه وسلم لتبليغ الدين.',
            explanationEn: 'It means Allah sent Muhammad (PBUH) to convey the religion.'
        },
        {
            id: 208,
            question: 'ما معنى "بسم الله"؟',
            questionEn: 'What does "Bismillah" mean?',
            options: ['أبدأ باسم الله', 'الله معي', 'يا الله', 'شكراً لله'],
            optionsEn: ['In the name of Allah', 'Allah is with me', 'Oh Allah', 'Thanks to Allah'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'نقول بسم الله عند البدء في أي عمل لطلب البركة.',
            explanationEn: 'We say Bismillah when starting any action to seek blessings.'
        },
        {
            id: 209,
            question: 'ما معنى "جزاك الله خيراً"؟',
            questionEn: 'What does "JazakAllahu Khairan" mean?',
            options: ['أعطاك الله خيراً', 'شكراً', 'أهلاً بك', 'مع السلامة'],
            optionsEn: ['May Allah reward you with good', 'Thank you', 'Welcome', 'Goodbye'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'دعاء للمسلم بأن يثيبه الله خيراً كثيراً.',
            explanationEn: 'A prayer for a Muslim that Allah may reward them with abundant good.'
        },
        {
            id: 210,
            question: 'ما معنى "بارك الله فيك"؟',
            questionEn: 'What does "BarakAllahu Feek" mean?',
            options: ['أنزل الله عليك البركة', 'أحبك الله', 'نصرك الله', 'حفظك الله'],
            optionsEn: ['May Allah bless you', 'Allah loves you', 'Allah helps you', 'Allah protects you'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'دعاء بالزيادة والنماء في الخير.',
            explanationEn: 'A prayer for increase and growth in goodness.'
        },
        // Quranic Words (21-40)
        {
            id: 211,
            question: 'ما معنى "الصراط" في الفاتحة؟',
            questionEn: 'What does "As-Sirat" mean in Al-Fatiha?',
            options: ['الطريق', 'الجسر', 'الباب', 'السور'],
            optionsEn: ['The Path', 'The Bridge', 'The Door', 'The Wall'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'الصراط المستقيم هو الطريق الواضح الذي لا اعوجاج فيه.',
            explanationEn: 'The Straight Path is the clear way without deviation.'
        },
        {
            id: 212,
            question: 'ما معنى "الكوثر"؟',
            questionEn: 'What does "Al-Kawthar" mean?',
            options: ['الخير الكثير ونهر في الجنة', 'المال الكثير', 'الأولاد', 'العمل الصالح'],
            optionsEn: ['Abundant good and a river in Paradise', 'Much money', 'Children', 'Good deeds'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'الكوثر هو الخير الكثير الذي أعطاه الله لنبيه، ومنه النهر في الجنة.',
            explanationEn: 'Al-Kawthar is the abundant good Allah gave His Prophet, including the river in Paradise.'
        },
        {
            id: 213,
            question: 'ما معنى "الفلق"؟',
            questionEn: 'What does "Al-Falaq" mean?',
            options: ['الصبح', 'الليل', 'الشمس', 'القمر'],
            optionsEn: ['The Daybreak', 'The Night', 'The Sun', 'The Moon'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'الفلق هو الصبح عندما ينشق النور من الظلام.',
            explanationEn: 'Al-Falaq is the daybreak when light splits from darkness.'
        },
        {
            id: 214,
            question: 'ما معنى "الناس" في سورة الناس؟',
            questionEn: 'What does "An-Nas" mean?',
            options: ['البشر', 'الجن', 'الملائكة', 'الحيوانات'],
            optionsEn: ['Mankind', 'Jinn', 'Angels', 'Animals'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'الناس هم البشر جميعاً.',
            explanationEn: 'An-Nas refers to all of mankind.'
        },
        {
            id: 215,
            question: 'ما معنى "الصمد"؟',
            questionEn: 'What does "As-Samad" mean?',
            options: ['الذي يقصده الخلائق في حوائجهم', 'القوي', 'العليم', 'الخالق'],
            optionsEn: ['The One whom all creation needs', 'The Strong', 'The All-Knowing', 'The Creator'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'الصمد هو السيد الذي تصمد إليه الخلائق وتلجأ إليه في حاجاتها.',
            explanationEn: 'As-Samad is the Master whom all creatures turn to for their needs.'
        },
        {
            id: 216,
            question: 'ما معنى "غاسق" في سورة الفلق؟',
            questionEn: 'What does "Ghasiq" mean in Surah Al-Falaq?',
            options: ['الليل إذا أظلم', 'القمر', 'الشيطان', 'العدو'],
            optionsEn: ['The night when it darkens', 'The Moon', 'The Devil', 'The Enemy'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'غاسق إذا وقب يعني الليل إذا دخل ظلامه.',
            explanationEn: 'Ghasiq idha waqab means the night when its darkness spreads.'
        },
        {
            id: 217,
            question: 'ما معنى "مسد" في سورة المسد؟',
            questionEn: 'What does "Masad" mean in Surah Al-Masad?',
            options: ['ليف قوي خشن', 'حديد', 'نار', 'حجارة'],
            optionsEn: ['Strong rough fiber', 'Iron', 'Fire', 'Stones'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'حبل من مسد أي حبل مفتول من ليف قوي.',
            explanationEn: 'A rope of Masad means a twisted rope of strong fiber.'
        },
        {
            id: 218,
            question: 'ما معنى "الإخلاص"؟',
            questionEn: 'What does "Al-Ikhlas" mean?',
            options: ['توحيد الله وتصفيته من الشرك', 'الصدق', 'الأمانة', 'الحب'],
            optionsEn: ['Sincerity and pure Monotheism', 'Honesty', 'Trust', 'Love'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'سورة الإخلاص سميت بذلك لأنها تخلص العبد من الشرك.',
            explanationEn: 'Surah Al-Ikhlas is named so because it purifies the servant from polytheism.'
        },
        {
            id: 219,
            question: 'ما معنى "العصر"؟',
            questionEn: 'What does "Al-Asr" mean?',
            options: ['الزمن أو وقت العصر', 'العصير', 'الضغط', 'العمل'],
            optionsEn: ['Time or the afternoon', 'Juice', 'Pressure', 'Work'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'أقسم الله بالعصر وهو الدهر أو وقت صلاة العصر.',
            explanationEn: 'Allah swore by Al-Asr, which is time or the time of Asr prayer.'
        },
        {
            id: 220,
            question: 'ما معنى "أبتر" في سورة الكوثر؟',
            questionEn: 'What does "Abtar" mean in Surah Al-Kawthar?',
            options: ['مقطوع الذكر والخير', 'قصير', 'ضعيف', 'مريض'],
            optionsEn: ['Cut off from good and memory', 'Short', 'Weak', 'Sick'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'إن شانئك هو الأبتر أي مبغضك هو المقطوع من كل خير.',
            explanationEn: 'Indeed, your enemy is the one cut off from all good.'
        },
        // Prayer Words (41-55)
        {
            id: 221,
            question: 'ما معنى "الركوع"؟',
            questionEn: 'What does "Ruku" mean?',
            options: ['الانحناء تعظيماً لله', 'السجود', 'الوقوف', 'الجلوس'],
            optionsEn: ['Bowing in glorification of Allah', 'Prostration', 'Standing', 'Sitting'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'الركوع هو الانحناء في الصلاة مع وضع اليدين على الركبتين.',
            explanationEn: 'Ruku is bowing in prayer with hands on knees.'
        },
        {
            id: 222,
            question: 'ما معنى "السجود"؟',
            questionEn: 'What does "Sujud" mean?',
            options: ['وضع الجبهة على الأرض', 'الانحناء', 'رفع اليدين', 'التسليم'],
            optionsEn: ['Placing forehead on ground', 'Bowing', 'Raising hands', 'Salutation'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'السجود هو وضع سبعة أعضاء على الأرض خضوعاً لله.',
            explanationEn: 'Sujud is placing seven body parts on the ground in submission to Allah.'
        },
        {
            id: 223,
            question: 'ما معنى "القبلة"؟',
            questionEn: 'What does "Qibla" mean?',
            options: ['اتجاه الكعبة', 'المسجد', 'السجادة', 'الوضوء'],
            optionsEn: ['Direction of Kaaba', 'Mosque', 'Rug', 'Wudu'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'القبلة هي الاتجاه الذي نتوجه إليه في الصلاة (الكعبة).',
            explanationEn: 'Qibla is the direction we face in prayer (the Kaaba).'
        },
        {
            id: 224,
            question: 'ما معنى "الوضوء"؟',
            questionEn: 'What does "Wudu" mean?',
            options: ['الطهارة بالماء للصلاة', 'الاستحمام', 'غسل اليدين', 'تنظيف الأسنان'],
            optionsEn: ['Ablution for prayer', 'Bathing', 'Washing hands', 'Brushing teeth'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'الوضوء هو غسل أعضاء محددة بنية الطهارة للصلاة.',
            explanationEn: 'Wudu is washing specific body parts with the intention of purification for prayer.'
        },
        {
            id: 225,
            question: 'ما معنى "الأذان"؟',
            questionEn: 'What does "Adhan" mean?',
            options: ['الإعلام بدخول وقت الصلاة', 'الدعاء', 'قراءة القرآن', 'الخطبة'],
            optionsEn: ['Call to prayer', 'Supplication', 'Reading Quran', 'Sermon'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'الأذان هو النداء للصلاة عند دخول وقتها.',
            explanationEn: 'Adhan is the call to prayer when its time begins.'
        },
        {
            id: 226,
            question: 'ما معنى "الإقامة"؟',
            questionEn: 'What does "Iqamah" mean?',
            options: ['الإعلام بالقيام للصلاة', 'الجلوس', 'الخروج', 'النوم'],
            optionsEn: ['Call to start prayer', 'Sitting', 'Leaving', 'Sleeping'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'الإقامة هي الإعلام ببدء الصلاة فعلياً.',
            explanationEn: 'Iqamah is the announcement that the prayer is about to start.'
        },
        {
            id: 227,
            question: 'ما معنى "التشهد"؟',
            questionEn: 'What does "Tashahhud" mean?',
            options: ['التحيات والشهادتين', 'الفاتحة', 'التسبيح', 'التكبير'],
            optionsEn: ['Testimony of Faith in prayer', 'Al-Fatiha', 'Tasbeeh', 'Takbeer'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'التشهد هو ما يقرأ في جلوس الصلاة وفيه الشهادتين.',
            explanationEn: 'Tashahhud is recited while sitting in prayer and contains the testimony of faith.'
        },
        {
            id: 228,
            question: 'ما معنى "التسليم"؟',
            questionEn: 'What does "Tasleem" mean?',
            options: ['قول السلام عليكم لختم الصلاة', 'المصافحة', 'التحية', 'الاستسلام'],
            optionsEn: ['Saying Salam to end prayer', 'Handshake', 'Greeting', 'Surrender'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'التسليم هو قول السلام عليكم ورحمة الله لإنهاء الصلاة.',
            explanationEn: 'Tasleem is saying As-Salamu Alaykum to conclude the prayer.'
        },
        {
            id: 229,
            question: 'ما معنى "الخشوع"؟',
            questionEn: 'What does "Khushu" mean?',
            options: ['حضور القلب والسكون', 'البكاء', 'إغماض العين', 'الصوت الجميل'],
            optionsEn: ['Humility and focus', 'Crying', 'Closing eyes', 'Beautiful voice'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'الخشوع هو سكون الجوارح وحضور القلب بين يدي الله.',
            explanationEn: 'Khushu is the calmness of limbs and presence of heart before Allah.'
        },
        {
            id: 230,
            question: 'ما معنى "النية"؟',
            questionEn: 'What does "Niyyah" mean?',
            options: ['قصد العمل لله', 'التفكير', 'الكلام', 'السر'],
            optionsEn: ['Intention for Allah', 'Thinking', 'Speaking', 'Secret'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'النية هي عزم القلب على فعل العبادة تقرباً لله.',
            explanationEn: 'Niyyah is the heart\'s resolve to perform worship for Allah.'
        },
        // General Islamic Terms (56-70)
        {
            id: 231,
            question: 'ما معنى "الزكاة"؟',
            questionEn: 'What does "Zakat" mean?',
            options: ['النماء والتطهير (صدقة واجبة)', 'الهدية', 'الضريبة', 'التوفير'],
            optionsEn: ['Purification and growth (Obligatory charity)', 'Gift', 'Tax', 'Saving'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'الزكاة لغة النماء، وهي حق واجب في المال.',
            explanationEn: 'Zakat means growth linguistically, and it is an obligatory right in wealth.'
        },
        {
            id: 232,
            question: 'ما معنى "الصوم"؟',
            questionEn: 'What does "Sawm" mean?',
            options: ['الإمساك عن المفطرات', 'الجوع', 'العطش', 'الحمية'],
            optionsEn: ['Abstaining from food/drink', 'Hunger', 'Thirst', 'Diet'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'الصوم هو الإمساك عن الطعام والشراب بنية من الفجر للمغرب.',
            explanationEn: 'Sawm is abstaining from food and drink with intention from dawn to sunset.'
        },
        {
            id: 233,
            question: 'ما معنى "الحج"؟',
            questionEn: 'What does "Hajj" mean?',
            options: ['قصد مكة لأداء المناسك', 'السفر', 'الزيارة', 'السياحة'],
            optionsEn: ['Pilgrimage to Makkah', 'Travel', 'Visit', 'Tourism'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'الحج هو قصد بيت الله الحرام لأداء مناسك مخصوصة.',
            explanationEn: 'Hajj is intending the Sacred House of Allah to perform specific rituals.'
        },
        {
            id: 234,
            question: 'ما معنى "العمرة"؟',
            questionEn: 'What does "Umrah" mean?',
            options: ['زيارة البيت الحرام', 'البناء', 'الحياة', 'الإعمار'],
            optionsEn: ['Visit to Sacred House', 'Building', 'Life', 'Construction'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'العمرة هي زيارة الكعبة للطواف والسعي.',
            explanationEn: 'Umrah is visiting the Kaaba for Tawaf and Sa\'i.'
        },
        {
            id: 235,
            question: 'ما معنى "الجهاد"؟',
            questionEn: 'What does "Jihad" mean?',
            options: ['بذل الجهد في سبيل الله', 'القتال فقط', 'السفر', 'العمل الشاق'],
            optionsEn: ['Striving in cause of Allah', 'Fighting only', 'Travel', 'Hard work'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'الجهاد هو بذل الجهد والطاقة لنصرة دين الله.',
            explanationEn: 'Jihad is exerting effort and energy to support Allah\'s religion.'
        },
        {
            id: 236,
            question: 'ما معنى "التقوى"؟',
            questionEn: 'What does "Taqwa" mean?',
            options: ['الخوف من الله والعمل بطاعته', 'القوة', 'الشجاعة', 'الذكاء'],
            optionsEn: ['God-consciousness/Piety', 'Strength', 'Bravery', 'Intelligence'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'التقوى هي أن تجعل بينك وبين عذاب الله وقاية بفعل الأوامر واجتناب النواهي.',
            explanationEn: 'Taqwa is placing a barrier between you and Allah\'s punishment by obeying Him.'
        },
        {
            id: 237,
            question: 'ما معنى "الإحسان"؟',
            questionEn: 'What does "Ihsan" mean?',
            options: ['أن تعبد الله كأنك تراه', 'الصدقة', 'مساعدة الناس', 'العمل الجيد'],
            optionsEn: ['Worshipping Allah as if you see Him', 'Charity', 'Helping people', 'Good work'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'الإحسان هو أعلى مراتب الدين، أن تعبد الله كأنك تراه.',
            explanationEn: 'Ihsan is the highest level of faith, to worship Allah as if you see Him.'
        },
        {
            id: 238,
            question: 'ما معنى "البر"؟',
            questionEn: 'What does "Birr" mean?',
            options: ['الخير الواسع والطاعة', 'القمح', 'الأرض', 'الصدق'],
            optionsEn: ['Righteousness and piety', 'Wheat', 'Land', 'Honesty'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'البر هو اسم جامع لكل أنواع الخير.',
            explanationEn: 'Birr is a comprehensive term for all kinds of goodness.'
        },
        {
            id: 239,
            question: 'ما معنى "الصلة" في صلة الرحم؟',
            questionEn: 'What does "Silah" mean in Silat Ar-Rahim?',
            options: ['الوصل والإحسان للأقارب', 'الاتصال الهاتفي', 'الزيارة فقط', 'المال'],
            optionsEn: ['Connecting and kindness to relatives', 'Phone call', 'Visiting only', 'Money'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'صلة الرحم هي الإحسان إلى الأقارب وتفقدهم.',
            explanationEn: 'Silat Ar-Rahim is being kind to relatives and checking on them.'
        },
        {
            id: 240,
            question: 'ما معنى "الدعاء"؟',
            questionEn: 'What does "Dua" mean?',
            options: ['طلب الحاجة من الله', 'النداء', 'الصراخ', 'الكلام'],
            optionsEn: ['Supplication to Allah', 'Calling', 'Shouting', 'Talking'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'الدعاء هو التوجه إلى الله بالطلب والرجاء.',
            explanationEn: 'Dua is turning to Allah with requests and hope.'
        },
        // More Words (71-75)
        {
            id: 241,
            question: 'ما معنى "الآية"؟',
            questionEn: 'What does "Ayah" mean?',
            options: ['العلامة والجملة من القرآن', 'المعجزة فقط', 'القصة', 'الحرف'],
            optionsEn: ['Sign and verse of Quran', 'Miracle only', 'Story', 'Letter'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'الآية هي العلامة، وتطلق على جمل القرآن.',
            explanationEn: 'Ayah means a sign, and refers to the verses of the Quran.'
        },
        {
            id: 242,
            question: 'ما معنى "السورة"؟',
            questionEn: 'What does "Surah" mean?',
            options: ['مجموعة من الآيات لها اسم', 'الكتاب', 'الصفحة', 'الجزء'],
            optionsEn: ['Chapter of Quran', 'Book', 'Page', 'Part'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'السورة هي قطعة من القرآن لها بداية ونهاية واسم خاص.',
            explanationEn: 'Surah is a section of the Quran with a start, end, and specific name.'
        },
        {
            id: 243,
            question: 'ما معنى "التوحيد"؟',
            questionEn: 'What does "Tawheed" mean?',
            options: ['إفراد الله بالعبادة', 'الوحدة', 'الاجتماع', 'القوة'],
            optionsEn: ['Monotheism (Oneness of Allah)', 'Unity', 'Gathering', 'Strength'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'التوحيد هو الاعتقاد بأن الله واحد لا شريك له.',
            explanationEn: 'Tawheed is the belief that Allah is One with no partners.'
        },
        {
            id: 244,
            question: 'ما معنى "الشرك"؟',
            questionEn: 'What does "Shirk" mean?',
            options: ['عبادة غير الله مع الله', 'المشاركة', 'التعاون', 'الظلم'],
            optionsEn: ['Polytheism (Associating partners with Allah)', 'Sharing', 'Cooperation', 'Injustice'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'الشرك هو جعل شريك لله في العبادة.',
            explanationEn: 'Shirk is setting up a partner with Allah in worship.'
        },
        {
            id: 245,
            question: 'ما معنى "النفاق"؟',
            questionEn: 'What does "Nifaq" mean?',
            options: ['إظهار الإسلام وإبطان الكفر', 'الكذب', 'الخيانة', 'السرقة'],
            optionsEn: ['Hypocrisy (Showing Islam, hiding disbelief)', 'Lying', 'Betrayal', 'Stealing'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'النفاق هو أن يظهر الإنسان الخير ويبطن الشر.',
            explanationEn: 'Nifaq is when a person shows good but conceals evil.'
        },
        // Names of Allah (76-85)
        {
            id: 246,
            question: 'ما معنى "الرحمن"؟',
            questionEn: 'What does "Ar-Rahman" mean?',
            options: ['ذو الرحمة الواسعة لجميع الخلق', 'الملك', 'الخالق', 'الرزاق'],
            optionsEn: ['The Most Gracious (Mercy for all)', 'The King', 'The Creator', 'The Provider'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'الرحمن هو الذي وسعت رحمته كل شيء.',
            explanationEn: 'Ar-Rahman is the One whose mercy encompasses everything.'
        },
        {
            id: 247,
            question: 'ما معنى "الرحيم"؟',
            questionEn: 'What does "Ar-Raheem" mean?',
            options: ['الراحم بالمؤمنين خاصة', 'القوي', 'العليم', 'البصير'],
            optionsEn: ['The Most Merciful (Specially to believers)', 'The Strong', 'The All-Knowing', 'The All-Seeing'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'الرحيم هو الذي يرحم عباده المؤمنين يوم القيامة.',
            explanationEn: 'Ar-Raheem is the One who has special mercy for believers on Judgment Day.'
        },
        {
            id: 248,
            question: 'ما معنى "الملك"؟',
            questionEn: 'What does "Al-Malik" mean?',
            options: ['المالك لكل شيء والحاكم', 'الغني', 'الكريم', 'الودود'],
            optionsEn: ['The King and Owner of everything', 'The Rich', 'The Generous', 'The Loving'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'الملك هو الذي يملك كل شيء ويتصرف فيه كيف يشاء.',
            explanationEn: 'Al-Malik is the Owner of everything and governs it as He wills.'
        },
        {
            id: 249,
            question: 'ما معنى "القدوس"؟',
            questionEn: 'What does "Al-Quddus" mean?',
            options: ['المنزه عن كل نقص وعيب', 'القديم', 'القادر', 'القهار'],
            optionsEn: ['The Pure/Holy (Free from imperfection)', 'The Ancient', 'The Capable', 'The Subduer'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'القدوس هو الطاهر المنزه عن كل العيوب والنقائص.',
            explanationEn: 'Al-Quddus is the Pure One, free from all flaws and imperfections.'
        },
        {
            id: 250,
            question: 'ما معنى "السلام"؟',
            questionEn: 'What does "As-Salam" mean?',
            options: ['السالم من كل نقص وناشر السلام', 'التحية', 'الهدوء', 'النوم'],
            optionsEn: ['The Source of Peace/Perfection', 'Greeting', 'Calm', 'Sleep'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'السلام هو الذي سلم من كل عيب وسلم خلقه من ظلمه.',
            explanationEn: 'As-Salam is the One free from defects and from whom creation is safe.'
        },
        {
            id: 251,
            question: 'ما معنى "المؤمن"؟',
            questionEn: 'What does "Al-Mu\'min" mean?',
            options: ['المصدق لرسله والمانح للأمن', 'المسلم', 'المصلي', 'الصائم'],
            optionsEn: ['The Giver of Security/Faith', 'The Muslim', 'The Praying One', 'The Fasting One'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'المؤمن هو الذي أمن خلقه من عذابه وصدق رسله.',
            explanationEn: 'Al-Mu\'min is the One who grants security and verifies His messengers.'
        },
        {
            id: 252,
            question: 'ما معنى "المهيمن"؟',
            questionEn: 'What does "Al-Muhaymin" mean?',
            options: ['المسيطر والرقيب على كل شيء', 'الكبير', 'العالي', 'البعيد'],
            optionsEn: ['The Guardian/Overseer', 'The Big', 'The High', 'The Far'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'المهيمن هو الرقيب الحافظ لكل شيء.',
            explanationEn: 'Al-Muhaymin is the Watcher and Guardian over everything.'
        },
        {
            id: 253,
            question: 'ما معنى "العزيز"؟',
            questionEn: 'What does "Al-Aziz" mean?',
            options: ['القوي الذي لا يغلب', 'الحبيب', 'القريب', 'المجيب'],
            optionsEn: ['The All-Mighty (Unconquerable)', 'The Beloved', 'The Near', 'The Responsive'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'العزيز هو القوي الغالب الذي لا يقهره شيء.',
            explanationEn: 'Al-Aziz is the Mighty One whom nothing can overcome.'
        },
        {
            id: 254,
            question: 'ما معنى "الجبار"؟',
            questionEn: 'What does "Al-Jabbar" mean?',
            options: ['الذي يجبر الكسر ويقهر الجبابرة', 'الظالم', 'الكبير', 'الطويل'],
            optionsEn: ['The Compeller/Restorer', 'The Unjust', 'The Big', 'The Tall'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'الجبار هو الذي يجبر قلوب المنكسرين ويقهر الظالمين.',
            explanationEn: 'Al-Jabbar is the One who mends broken hearts and subdues tyrants.'
        },
        {
            id: 255,
            question: 'ما معنى "المتكبر"؟',
            questionEn: 'What does "Al-Mutakabbir" mean?',
            options: ['المتعالي عن صفات الخلق', 'المغرور', 'السيء', 'الغاضب'],
            optionsEn: ['The Supreme/Majestic', 'The Arrogant', 'The Bad', 'The Angry'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'المتكبر هو العظيم الذي تكبر عن ظلم عباده وعن صفات النقص.',
            explanationEn: 'Al-Mutakabbir is the Supreme One, above all imperfection and injustice.'
        },
        // Islamic Months & Times (86-95)
        {
            id: 256,
            question: 'ما معنى "محرم"؟',
            questionEn: 'What does "Muharram" mean?',
            options: ['الحرام (شهر محرم القتال فيه)', 'الممنوع', 'الجديد', 'الأول'],
            optionsEn: ['Forbidden/Sacred (Month)', 'Prohibited', 'New', 'First'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'سمي محرماً لأن القتال فيه كان محرماً.',
            explanationEn: 'It was named Muharram because fighting was forbidden in it.'
        },
        {
            id: 257,
            question: 'ما معنى "رمضان"؟',
            questionEn: 'What does "Ramadan" mean?',
            options: ['شدة الحر (رمضاء)', 'المطر', 'الربيع', 'الخير'],
            optionsEn: ['Scorching Heat', 'Rain', 'Spring', 'Goodness'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'قيل سمي رمضان لشدة الحر فيه وقت تسميته.',
            explanationEn: 'It is said it was named Ramadan due to the intense heat when it was named.'
        },
        {
            id: 258,
            question: 'ما معنى "شوال"؟',
            questionEn: 'What does "Shawwal" mean?',
            options: ['الارتفاع (تشول الإبل)', 'النقصان', 'الزيادة', 'البركة'],
            optionsEn: ['Uplift/Carry', 'Decrease', 'Increase', 'Blessing'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'سمي شوالاً لأن الإبل كانت تشول بأذنابها أي ترفعها.',
            explanationEn: 'Named Shawwal because camels used to raise (shawwala) their tails.'
        },
        {
            id: 259,
            question: 'ما معنى "ذي الحجة"؟',
            questionEn: 'What does "Dhul-Hijjah" mean?',
            options: ['صاحب الحج', 'صاحب المال', 'صاحب العلم', 'صاحب البيت'],
            optionsEn: ['Possessor of Hajj', 'Possessor of Wealth', 'Possessor of Knowledge', 'Possessor of House'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'سمي بذلك لأن الحج يقع فيه.',
            explanationEn: 'Named so because Hajj takes place in it.'
        },
        {
            id: 260,
            question: 'ما معنى "الفجر"؟',
            questionEn: 'What does "Fajr" mean?',
            options: ['انفجار النور والصبح', 'الليل', 'الظهر', 'العصر'],
            optionsEn: ['Dawn/Daybreak', 'Night', 'Noon', 'Afternoon'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'الفجر هو وقت انفجار النور وانشقاق الظلام.',
            explanationEn: 'Fajr is the time when light bursts forth and darkness splits.'
        },
        {
            id: 261,
            question: 'ما معنى "الضحى"؟',
            questionEn: 'What does "Duha" mean?',
            options: ['وقت ارتفاع الشمس', 'وقت الغروب', 'منتصف الليل', 'الفجر'],
            optionsEn: ['Forenoon (Sun rising high)', 'Sunset', 'Midnight', 'Dawn'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'الضحى هو الوقت الذي يليه شروق الشمس وارتفاعها.',
            explanationEn: 'Duha is the time following sunrise when the sun is high.'
        },
        {
            id: 262,
            question: 'ما معنى "الجمعة"؟',
            questionEn: 'What does "Jumu\'ah" mean?',
            options: ['الاجتماع', 'التفرق', 'الراحة', 'العمل'],
            optionsEn: ['Gathering/Congregation', 'Separation', 'Rest', 'Work'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'سميت الجمعة لاجتماع الناس فيها للصلاة.',
            explanationEn: 'Named Jumu\'ah because people gather in it for prayer.'
        },
        {
            id: 263,
            question: 'ما معنى "عيد"؟',
            questionEn: 'What does "Eid" mean?',
            options: ['ما يعود ويتكرر بالفرح', 'الجديد', 'الطعام', 'الملابس'],
            optionsEn: ['Festivity that returns', 'New', 'Food', 'Clothes'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'العيد هو كل يوم فيه جمع، وسمي عيداً لأنه يعود كل سنة.',
            explanationEn: 'Eid is a day of gathering, named so because it returns every year.'
        },
        {
            id: 264,
            question: 'ما معنى "القدر" في ليلة القدر؟',
            questionEn: 'What does "Qadr" mean in Laylatul Qadr?',
            options: ['الشرف والتقدير', 'الطبخ', 'الظلام', 'النور'],
            optionsEn: ['Decree/Honor/Power', 'Cooking', 'Darkness', 'Light'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'ليلة القدر تعني ليلة الشرف أو ليلة التقدير التي تقدر فيها الأرزاق.',
            explanationEn: 'Laylatul Qadr means the Night of Honor or Decree where sustenance is decided.'
        },
        {
            id: 265,
            question: 'ما معنى "عاشوراء"؟',
            questionEn: 'What does "Ashura" mean?',
            options: ['اليوم العاشر من محرم', 'اليوم الأول', 'اليوم الخامس', 'اليوم الأخير'],
            optionsEn: ['The 10th day of Muharram', 'First day', 'Fifth day', 'Last day'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'عاشوراء هو اليوم العاشر من شهر محرم.',
            explanationEn: 'Ashura is the tenth day of the month of Muharram.'
        },
        // Prophets' Titles (96-105)
        {
            id: 266,
            question: 'ما معنى "خليل الله"؟',
            questionEn: 'What does "Khalilullah" mean?',
            options: ['صديق الله المقرب (لقب إبراهيم)', 'رسول الله', 'عبد الله', 'نبي الله'],
            optionsEn: ['Friend of Allah (Title of Ibrahim)', 'Messenger of Allah', 'Servant of Allah', 'Prophet of Allah'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'الخليل هو الصديق الخالص الذي تخللت محبته القلب.',
            explanationEn: 'Khalil is the close friend whose love has penetrated the heart.'
        },
        {
            id: 267,
            question: 'ما معنى "كليم الله"؟',
            questionEn: 'What does "Kalimullah" mean?',
            options: ['الذي كلمه الله (لقب موسى)', 'الذي رأى الله', 'الذي سمع الله', 'الذي أحب الله'],
            optionsEn: ['One who spoke to Allah (Title of Musa)', 'One who saw Allah', 'One who heard Allah', 'One who loved Allah'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'كليم الله هو لقب موسى عليه السلام لأنه كلم الله تكليماً.',
            explanationEn: 'Kalimullah is the title of Musa (AS) because he spoke directly to Allah.'
        },
        {
            id: 268,
            question: 'ما معنى "روح الله"؟',
            questionEn: 'What does "Ruhullah" mean?',
            options: ['لقب عيسى عليه السلام', 'لقب آدم', 'لقب نوح', 'لقب محمد'],
            optionsEn: ['Title of Isa (Jesus)', 'Title of Adam', 'Title of Nuh', 'Title of Muhammad'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'عيسى عليه السلام سمي روح الله لأنه خلق بنفخة من الروح بأمر الله.',
            explanationEn: 'Isa (AS) is called Ruhullah because he was created by a spirit from Allah.'
        },
        {
            id: 269,
            question: 'ما معنى "الصديق"؟',
            questionEn: 'What does "As-Siddiq" mean?',
            options: ['كثير الصدق والتصديق (لقب أبي بكر)', 'الصادق', 'الصديق', 'الصدوق'],
            optionsEn: ['The Truthful/Believer (Title of Abu Bakr)', 'Honest', 'Friend', 'Truthful'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'الصديق هو المبالغ في الصدق والتصديق، وهو لقب أبي بكر رضي الله عنه.',
            explanationEn: 'As-Siddiq is one who is extremely truthful and believing, title of Abu Bakr (RA).'
        },
        {
            id: 270,
            question: 'ما معنى "الفاروق"؟',
            questionEn: 'What does "Al-Farooq" mean?',
            options: ['الذي يفرق بين الحق والباطل (لقب عمر)', 'الفرق', 'الفريق', 'الفراق'],
            optionsEn: ['Distinguisher between Truth and Falsehood', 'Difference', 'Team', 'Separation'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'الفاروق هو الذي يفرق بين الحق والباطل، لقب عمر بن الخطاب.',
            explanationEn: 'Al-Farooq is the one who distinguishes truth from falsehood, title of Umar (RA).'
        },
        {
            id: 271,
            question: 'ما معنى "ذو النورين"؟',
            questionEn: 'What does "Dhun-Nurayn" mean?',
            options: ['صاحب النورين (لقب عثمان)', 'صاحب المصباحين', 'صاحب العينين', 'صاحب الوجهين'],
            optionsEn: ['Possessor of Two Lights (Title of Uthman)', 'Owner of two lamps', 'Owner of two eyes', 'Two-faced'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'لقب عثمان بن عفان لزواجه من ابنتي الرسول صلى الله عليه وسلم.',
            explanationEn: 'Title of Uthman bin Affan for marrying two daughters of the Prophet (PBUH).'
        },
        {
            id: 272,
            question: 'ما معنى "سيف الله المسلول"؟',
            questionEn: 'What does "Saifullah Al-Maslul" mean?',
            options: ['لقب خالد بن الوليد', 'لقب علي بن أبي طالب', 'لقب حمزة', 'لقب عمر'],
            optionsEn: ['Title of Khalid bin Walid', 'Title of Ali', 'Title of Hamza', 'Title of Umar'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'لقب أطلقه الرسول على خالد بن الوليد لشدة بأسه في القتال.',
            explanationEn: 'Title given by the Prophet to Khalid bin Walid for his fierceness in battle.'
        },
        {
            id: 273,
            question: 'ما معنى "أمين الأمة"؟',
            questionEn: 'What does "Amin Al-Ummah" mean?',
            options: ['لقب أبي عبيدة بن الجراح', 'لقب عثمان', 'لقب علي', 'لقب بلال'],
            optionsEn: ['Title of Abu Ubaidah bin Al-Jarrah', 'Title of Uthman', 'Title of Ali', 'Title of Bilal'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'لقب خص به النبي صلى الله عليه وسلم أبا عبيدة لأمانته.',
            explanationEn: 'Title given specifically by the Prophet to Abu Ubaidah for his trustworthiness.'
        },
        {
            id: 274,
            question: 'ما معنى "حبر الأمة"؟',
            questionEn: 'What does "Habr Al-Ummah" mean?',
            options: ['العالم (لقب ابن عباس)', 'الكاتب', 'الحبر', 'الشاعر'],
            optionsEn: ['The Scholar (Title of Ibn Abbas)', 'The Writer', 'The Ink', 'The Poet'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'لقب عبد الله بن عباس لسعة علمه بالفقه والتفسير.',
            explanationEn: 'Title of Abdullah bin Abbas for his vast knowledge of Fiqh and Tafsir.'
        },
        {
            id: 275,
            question: 'ما معنى "أسد الله"؟',
            questionEn: 'What does "Asadullah" mean?',
            options: ['لقب حمزة بن عبد المطلب', 'لقب عمر', 'لقب خالد', 'لقب معاوية'],
            optionsEn: ['Lion of Allah (Title of Hamza)', 'Title of Umar', 'Title of Khalid', 'Title of Muawiyah'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'لقب حمزة عم النبي صلى الله عليه وسلم لشجاعته.',
            explanationEn: 'Title of Hamza, uncle of the Prophet, for his bravery.'
        }
    ]
};
