import { QuizLevel } from '../quizTypes';

export const level7: QuizLevel = {
    id: 7,
    titleAr: 'قصص الأنبياء - الجزء 2',
    titleEn: 'Prophets Stories - Part 2',
    description: 'من قصة موسى عليه السلام إلى عيسى عليه السلام',
    descriptionEn: 'From Musa (AS) to Isa (AS)',
    requiredScore: 70,
    icon: '🕌',
    questions: [
        // Musa (AS)
        {
            id: 1,
            question: 'أين ولد موسى عليه السلام؟',
            questionEn: 'Where was Musa (AS) born?',
            options: ['في مصر', 'في الشام', 'في العراق', 'في مكة'],
            optionsEn: ['In Egypt', 'In Levant', 'In Iraq', 'In Mecca'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'ولد موسى عليه السلام في مصر في زمن فرعون.',
            explanationEn: 'Musa (AS) was born in Egypt during the time of Pharaoh.'
        },
        {
            id: 2,
            question: 'أين وضعت أم موسى طفلها خيفة عليه؟',
            questionEn: 'Where did Musa\'s mother put her baby out of fear for him?',
            options: ['في التابوت في اليم (النيل)', 'في غار', 'في الصحراء', 'عند الجيران'],
            optionsEn: ['In a chest in the river (Nile)', 'In a cave', 'In the desert', 'With neighbors'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'أوحى الله إليها أن تضعه في التابوت وتلقيه في اليم.',
            explanationEn: 'Allah inspired her to put him in the chest and cast him into the river.'
        },
        {
            id: 3,
            question: 'من الذي التقط موسى عليه السلام من النهر؟',
            questionEn: 'Who picked up Musa (AS) from the river?',
            options: ['آل فرعون', 'بنو إسرائيل', 'تجار', 'صيادون'],
            optionsEn: ['Pharaoh\'s family', 'Children of Israel', 'Merchants', 'Fishermen'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'التقطه آل فرعون ليكون لهم عدواً وحزناً.',
            explanationEn: 'Pharaoh\'s family picked him up to be an enemy and a source of grief for them.'
        },
        {
            id: 4,
            question: 'من هي المرأة التي كفلت موسى وربته؟',
            questionEn: 'Who is the woman who took care of Musa and raised him?',
            options: ['آسية بنت مزاحم (امرأة فرعون)', 'مريم', 'هاجر', 'سارة'],
            optionsEn: ['Asiya bint Muzahim (Pharaoh\'s wife)', 'Maryam', 'Hajar', 'Sarah'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'آسية امرأة فرعون هي التي طلبت عدم قتله وربته.',
            explanationEn: 'Asiya, Pharaoh\'s wife, asked not to kill him and raised him.'
        },
        {
            id: 5,
            question: 'لماذا هرب موسى عليه السلام من مصر إلى مدين؟',
            questionEn: 'Why did Musa (AS) flee from Egypt to Madyan?',
            options: ['لأنه قتل رجلاً من القبط خطأً', 'للبحث عن عمل', 'للدعوة', 'للتجارة'],
            optionsEn: ['Because he accidentally killed a Copt', 'Looking for work', 'For Dawah', 'For trade'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'هرب خائفاً بعد أن قتل رجلاً من قوم فرعون بالخطأ.',
            explanationEn: 'He fled in fear after accidentally killing a man from Pharaoh\'s people.'
        },
        {
            id: 6,
            question: 'من هو النبي الذي زوجه موسى ابنته في مدين؟',
            questionEn: 'Who is the Prophet whose daughter Musa married in Madyan?',
            options: ['شعيب عليه السلام', 'صالح عليه السلام', 'هود عليه السلام', 'لوط عليه السلام'],
            optionsEn: ['Shu\'aib (AS)', 'Saleh (AS)', 'Hud (AS)', 'Lut (AS)'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'زوجه شعيب عليه السلام إحدى ابنتيه مقابل أن يعمل عنده.',
            explanationEn: 'Shu\'aib (AS) married one of his daughters to him in exchange for working for him.'
        },
        {
            id: 7,
            question: 'أين كلم الله موسى عليه السلام؟',
            questionEn: 'Where did Allah speak to Musa (AS)?',
            options: ['في الوادي المقدس طوى (طور سيناء)', 'في مكة', 'في القدس', 'في السماء'],
            optionsEn: ['In the sacred valley of Tuwa (Mount Sinai)', 'In Mecca', 'In Jerusalem', 'In Heaven'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'كلمه الله عند جبل الطور في سيناء.',
            explanationEn: 'Allah spoke to him at Mount Tur in Sinai.'
        },
        {
            id: 8,
            question: 'ما هي المعجزات التي أيد الله بها موسى أمام فرعون؟',
            questionEn: 'What miracles did Allah support Musa with before Pharaoh?',
            options: ['العصا واليد البيضاء', 'الناقة', 'إحياء الموتى', 'انشقاق القمر'],
            optionsEn: ['The staff and the white hand', 'The she-camel', 'Raising the dead', 'Splitting the moon'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'ألقى عصاه فإذا هي ثعبان، ونزع يده فإذا هي بيضاء.',
            explanationEn: 'He threw his staff and it became a snake, and drew his hand and it was white.'
        },
        {
            id: 9,
            question: 'من هو أخو موسى الذي أرسله الله معه وزيراً؟',
            questionEn: 'Who is Musa\'s brother whom Allah sent with him as a helper?',
            options: ['هارون عليه السلام', 'يوشع', 'يوسف', 'عيسى'],
            optionsEn: ['Harun (AS)', 'Yusha', 'Yusuf', 'Isa'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'طلب موسى من الله أن يرسل معه أخاه هارون لأنه أفصح لساناً.',
            explanationEn: 'Musa asked Allah to send his brother Harun with him because he was more eloquent.'
        },
        {
            id: 10,
            question: 'كيف أهلك الله فرعون وجنوده؟',
            questionEn: 'How did Allah destroy Pharaoh and his soldiers?',
            options: ['بالغرق في البحر', 'بالريح', 'بالصيحة', 'بالخسف'],
            optionsEn: ['Drowning in the sea', 'Wind', 'Blast', 'Swallowing by earth'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'أغرقهم الله في البحر الأحمر ونجى موسى وقومه.',
            explanationEn: 'Allah drowned them in the Red Sea and saved Musa and his people.'
        },
        {
            id: 11,
            question: 'ما هو الكتاب الذي أنزل على موسى عليه السلام؟',
            questionEn: 'What book was revealed to Musa (AS)?',
            options: ['التوراة', 'الإنجيل', 'الزبور', 'القرآن'],
            optionsEn: ['Torah', 'Gospel (Injeel)', 'Psalms (Zabur)', 'Quran'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'أنزل الله التوراة على موسى هدى ونوراً.',
            explanationEn: 'Allah revealed the Torah to Musa as guidance and light.'
        },
        {
            id: 12,
            question: 'ماذا عبد بنو إسرائيل في غياب موسى؟',
            questionEn: 'What did the Children of Israel worship in Musa\'s absence?',
            options: ['العجل', 'الشمس', 'الأصنام', 'النار'],
            optionsEn: ['The Calf', 'The Sun', 'Idols', 'Fire'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'صنع لهم السامري عجلاً من ذهب فعبدوه.',
            explanationEn: 'As-Samiri made a golden calf for them and they worshipped it.'
        },
        {
            id: 13,
            question: 'من هو الرجل الصالح الذي رافقه موسى ليتعلم منه؟',
            questionEn: 'Who is the righteous man Musa accompanied to learn from?',
            options: ['الخضر', 'لقمان', 'ذو القرنين', 'يوشع بن نون'],
            optionsEn: ['Al-Khidr', 'Luqman', 'Dhul-Qarnayn', 'Yusha bin Nun'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'قصة موسى والخضر مذكورة في سورة الكهف.',
            explanationEn: 'The story of Musa and Al-Khidr is mentioned in Surah Al-Kahf.'
        },
        {
            id: 14,
            question: 'ماذا طلب بنو إسرائيل من موسى عندما عطشوا؟',
            questionEn: 'What did the Children of Israel ask Musa when they were thirsty?',
            options: ['أن يضرب الحجر بعصاه', 'أن يحفر بئراً', 'أن يدعو للمطر', 'أن يرجعوا لمصر'],
            optionsEn: ['To strike the stone with his staff', 'Dig a well', 'Pray for rain', 'Return to Egypt'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'فضرب الحجر فانفجرت منه اثنتا عشرة عيناً.',
            explanationEn: 'He struck the stone and twelve springs gushed forth.'
        },
        {
            id: 15,
            question: 'ما هو الطعام الذي أنزله الله على بني إسرائيل في التيه؟',
            questionEn: 'What food did Allah send down to the Children of Israel in the wilderness?',
            options: ['المن والسلوى', 'التمر واللبن', 'الخبز واللحم', 'الفواكه'],
            optionsEn: ['Manna and Salwa (Quails)', 'Dates and Milk', 'Bread and Meat', 'Fruits'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'أنزل الله عليهم المن (شيء حلو) والسلوى (طائر).',
            explanationEn: 'Allah sent down Manna (sweet substance) and Salwa (birds) to them.'
        },
        // Dawud & Sulaiman (AS)
        {
            id: 16,
            question: 'من الذي قتل جالوت؟',
            questionEn: 'Who killed Jalut (Goliath)?',
            options: ['داود عليه السلام', 'طالوت', 'موسى', 'سليمان'],
            optionsEn: ['Dawud (AS)', 'Talut', 'Musa', 'Sulaiman'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'قتل داود جالوت بالمقلاع.',
            explanationEn: 'Dawud killed Jalut with a sling.'
        },
        {
            id: 17,
            question: 'ما هو الكتاب الذي أنزل على داود عليه السلام؟',
            questionEn: 'What book was revealed to Dawud (AS)?',
            options: ['الزبور', 'التوراة', 'الإنجيل', 'الصحف'],
            optionsEn: ['Psalms (Zabur)', 'Torah', 'Gospel', 'Scrolls'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'وآتينا داود زبوراً.',
            explanationEn: 'And We gave Dawud the Zabur.'
        },
        {
            id: 18,
            question: 'بماذا اشتهر داود عليه السلام؟',
            questionEn: 'What was Dawud (AS) famous for?',
            options: ['جمال الصوت وتسبيح الجبال معه', 'بناء السفن', 'تفسير الأحلام', 'الصبر'],
            optionsEn: ['Beautiful voice and mountains praising with him', 'Building ships', 'Dream interpretation', 'Patience'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'سخر الله له الجبال والطير يسبحن معه.',
            explanationEn: 'Allah subjected the mountains and birds to praise with him.'
        },
        {
            id: 19,
            question: 'ما هي المهنة التي كان يعمل بها داود عليه السلام؟',
            questionEn: 'What was the profession of Dawud (AS)?',
            options: ['حداد (صناعة الدروع)', 'نجار', 'تاجر', 'راعي'],
            optionsEn: ['Blacksmith (making armor)', 'Carpenter', 'Merchant', 'Shepherd'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'ألان الله له الحديد فكان يصنع الدروع.',
            explanationEn: 'Allah made iron soft for him, so he used to make coats of mail (armor).'
        },
        {
            id: 20,
            question: 'من ورث النبوة والملك من داود؟',
            questionEn: 'Who inherited Prophethood and Kingdom from Dawud?',
            options: ['سليمان عليه السلام', 'يحيى', 'زكريا', 'يوسف'],
            optionsEn: ['Sulaiman (AS)', 'Yahya', 'Zakariya', 'Yusuf'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'وورث سليمان داود.',
            explanationEn: 'And Sulaiman inherited Dawud.'
        },
        {
            id: 21,
            question: 'ما هي القدرة الخاصة التي أعطاها الله لسليمان؟',
            questionEn: 'What special ability did Allah give to Sulaiman?',
            options: ['فهم لغة الطير والحيوان وتسخير الجن', 'إحياء الموتى', 'شفاء المرضى', 'انشقاق البحر'],
            optionsEn: ['Understanding birds/animals and controlling Jinn', 'Raising dead', 'Curing sick', 'Splitting sea'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'علم منطق الطير وسخرت له الريح والجن.',
            explanationEn: 'He was taught the language of birds, and the wind and Jinn were subjected to him.'
        },
        {
            id: 22,
            question: 'ما هو الطائر الذي تفقد سليمان غيابه؟',
            questionEn: 'Which bird did Sulaiman notice was missing?',
            options: ['الهدهد', 'الغراب', 'الصقر', 'الحمامة'],
            optionsEn: ['Hoopoe (Hudhud)', 'Crow', 'Falcon', 'Pigeon'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'تفقد الطير فقال ما لي لا أرى الهدهد.',
            explanationEn: 'He inspected the birds and said, "Why do I not see the Hoopoe?"'
        },
        {
            id: 23,
            question: 'من هي الملكة التي أسلمت مع سليمان؟',
            questionEn: 'Who is the Queen who accepted Islam with Sulaiman?',
            options: ['ملكة سبأ (بلقيس)', 'ملكة مصر', 'امرأة العزيز', 'آسية'],
            optionsEn: ['Queen of Sheba (Bilqis)', 'Queen of Egypt', 'Wife of Aziz', 'Asiya'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'قالت رب إني ظلمت نفسي وأسلمت مع سليمان لله رب العالمين.',
            explanationEn: 'She said, "My Lord, indeed I have wronged myself, and I submit with Sulaiman to Allah."'
        },
        // Yunus & Ayyub (AS)
        {
            id: 24,
            question: 'ماذا حدث ليونس عليه السلام عندما ألقي في البحر؟',
            questionEn: 'What happened to Yunus (AS) when he was thrown into the sea?',
            options: ['التقمه الحوت', 'غرق', 'نجته سفينة', 'سبح للشاطئ'],
            optionsEn: ['A whale swallowed him', 'He drowned', 'A ship saved him', 'Swam to shore'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'فالتقمه الحوت وهو مليم.',
            explanationEn: 'Then the whale swallowed him while he was blameworthy.'
        },
        {
            id: 25,
            question: 'ما هو دعاء يونس في بطن الحوت؟',
            questionEn: 'What was Yunus\'s Dua in the belly of the whale?',
            options: ['لا إله إلا أنت سبحانك إني كنت من الظالمين', 'رب اغفر لي', 'الحمد لله', 'الله أكبر'],
            optionsEn: ['La ilaha illa anta subhanaka inni kuntu minaz-zalimin', 'Rabbighfir li', 'Alhamdulillah', 'Allahu Akbar'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'نادى في الظلمات أن لا إله إلا أنت سبحانك إني كنت من الظالمين.',
            explanationEn: 'He called out in the darkness: "There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers."'
        },
        {
            id: 26,
            question: 'بماذا ابتلى الله أيوب عليه السلام؟',
            questionEn: 'With what did Allah test Ayyub (AS)?',
            options: ['بالمرض وفقد الأهل والمال', 'بالفقر فقط', 'بالسجن', 'بالحرب'],
            optionsEn: ['Sickness and loss of family/wealth', 'Poverty only', 'Imprisonment', 'War'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'صبر أيوب على المرض والبلاء سنوات طويلة.',
            explanationEn: 'Ayyub was patient with sickness and tribulation for many years.'
        },
        // Zakariya, Yahya, Isa (AS)
        {
            id: 27,
            question: 'من كفل مريم عليها السلام؟',
            questionEn: 'Who took care of Maryam (AS)?',
            options: ['زكريا عليه السلام', 'يحيى', 'عيسى', 'موسى'],
            optionsEn: ['Zakariya (AS)', 'Yahya', 'Isa', 'Musa'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'وكفلها زكريا.',
            explanationEn: 'And Zakariya took charge of her.'
        },
        {
            id: 28,
            question: 'ما هي الآية التي حدثت لزكريا عندما بشر بيحيى؟',
            questionEn: 'What sign happened to Zakariya when he was given tidings of Yahya?',
            options: ['لم يكلم الناس ثلاثة أيام إلا رمزاً', 'عمي بصره', 'شفي من المرض', 'نزل عليه المطر'],
            optionsEn: ['Did not speak to people for 3 days except by signal', 'Went blind', 'Cured', 'Rain fell'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'آيتك ألا تكلم الناس ثلاثة أيام إلا رمزاً.',
            explanationEn: 'Your sign is that you will not speak to the people for three days except by gesture.'
        },
        {
            id: 29,
            question: 'بماذا وصف الله يحيى عليه السلام؟',
            questionEn: 'How did Allah describe Yahya (AS)?',
            options: ['سيداً وحصوراً ونبياً من الصالحين', 'ملكاً عظيماً', 'غني', 'قوي'],
            optionsEn: ['Noble, chaste, and a prophet from the righteous', 'Great king', 'Rich', 'Strong'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'مصدقاً بكلمة من الله وسيداً وحصوراً ونبياً.',
            explanationEn: 'Confirming a word from Allah, noble, chaste, and a prophet.'
        },
        {
            id: 30,
            question: 'من هي أم عيسى عليه السلام؟',
            questionEn: 'Who is the mother of Isa (AS)?',
            options: ['مريم العذراء', 'آسية', 'خديجة', 'فاطمة'],
            optionsEn: ['Virgin Maryam', 'Asiya', 'Khadija', 'Fatima'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'عيسى ابن مريم، ولد بدون أب بمعجزة من الله.',
            explanationEn: 'Isa son of Maryam, born without a father by a miracle from Allah.'
        },
        {
            id: 31,
            question: 'ما هي أول معجزة لعيسى عليه السلام؟',
            questionEn: 'What was the first miracle of Isa (AS)?',
            options: ['تكلم في المهد صبياً', 'إحياء الموتى', 'شفاء الأكمه', 'نزول المائدة'],
            optionsEn: ['Spoke in the cradle as a baby', 'Raising dead', 'Curing blind', 'Table spread'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'قال إني عبد الله آتاني الكتاب وجعلني نبياً وهو في المهد.',
            explanationEn: 'He said, "Indeed, I am the servant of Allah..." while in the cradle.'
        },
        {
            id: 32,
            question: 'ما هو الكتاب الذي أنزل على عيسى عليه السلام؟',
            questionEn: 'What book was revealed to Isa (AS)?',
            options: ['الإنجيل', 'التوراة', 'الزبور', 'القرآن'],
            optionsEn: ['Gospel (Injeel)', 'Torah', 'Psalms', 'Quran'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'وآتيناه الإنجيل فيه هدى ونور.',
            explanationEn: 'And We gave him the Gospel, in which was guidance and light.'
        },
        {
            id: 33,
            question: 'هل صلب عيسى عليه السلام؟',
            questionEn: 'Was Isa (AS) crucified?',
            options: ['لا، بل رفعه الله إليه', 'نعم', 'مات ميتة طبيعية', 'قتل في المعركة'],
            optionsEn: ['No, Allah raised him up', 'Yes', 'Died naturally', 'Killed in battle'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'وما قتلوه وما صلبوه ولكن شبه لهم.',
            explanationEn: 'And they did not kill him, nor did they crucify him; but [another] was made to resemble him to them.'
        },
        {
            id: 34,
            question: 'ما هي المائدة التي طلبتها الحواريون؟',
            questionEn: 'What is the Table Spread the disciples asked for?',
            options: ['مائدة من السماء تكون عيداً لهم', 'طعام من الجنة', 'كنز', 'ماء'],
            optionsEn: ['Table from heaven to be a festival', 'Food from Paradise', 'Treasure', 'Water'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'طلبوا مائدة تنزل من السماء لتطمئن قلوبهم.',
            explanationEn: 'They asked for a table to come down from heaven to satisfy their hearts.'
        },
        {
            id: 35,
            question: 'من هم الحواريون؟',
            questionEn: 'Who are the Hawariyyun (Disciples)?',
            options: ['أنصار عيسى عليه السلام', 'أعداء عيسى', 'قوم موسى', 'قوم لوط'],
            optionsEn: ['Supporters of Isa (AS)', 'Enemies of Isa', 'People of Musa', 'People of Lut'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'قال الحواريون نحن أنصار الله.',
            explanationEn: 'The Disciples said, "We are the supporters of Allah."'
        },
        // More Prophets & Details
        {
            id: 36,
            question: 'من هو النبي الذي ابتلعه الحوت؟',
            questionEn: 'Who is the Prophet swallowed by the whale?',
            options: ['يونس (ذو النون)', 'يوسف', 'نوح', 'إدريس'],
            optionsEn: ['Yunus (Dhul-Nun)', 'Yusuf', 'Nuh', 'Idris'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'يونس عليه السلام هو صاحب الحوت.',
            explanationEn: 'Yunus (AS) is the companion of the whale.'
        },
        {
            id: 37,
            question: 'إلى من أرسل يونس عليه السلام؟',
            questionEn: 'To whom was Yunus (AS) sent?',
            options: ['إلى أهل نينوى', 'إلى عاد', 'إلى ثمود', 'إلى مدين'],
            optionsEn: ['To people of Nineveh', 'To Ad', 'To Thamud', 'To Madyan'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'أرسل إلى مائة ألف أو يزيدون في نينوى (العراق).',
            explanationEn: 'He was sent to a hundred thousand or more in Nineveh (Iraq).'
        },
        {
            id: 38,
            question: 'من هو النبي الذي قتله قومه داخل شجرة؟',
            questionEn: 'Who is the Prophet whose people killed him inside a tree?',
            options: ['زكريا عليه السلام', 'يحيى', 'عيسى', 'موسى'],
            optionsEn: ['Zakariya (AS)', 'Yahya', 'Isa', 'Musa'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'ورد في الآثار أن زكريا نشر بالمنشار وهو في الشجرة.',
            explanationEn: 'It is reported that Zakariya was sawed in half while inside a tree.'
        },
        {
            id: 39,
            question: 'من هو كليم الله؟',
            questionEn: 'Who is Kalimullah (The one who spoke to Allah)?',
            options: ['موسى عليه السلام', 'عيسى', 'إبراهيم', 'محمد ﷺ'],
            optionsEn: ['Musa (AS)', 'Isa', 'Ibrahim', 'Muhammad ﷺ'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'وكلم الله موسى تكليماً.',
            explanationEn: 'And Allah spoke to Musa directly.'
        },
        {
            id: 40,
            question: 'من هو روح الله؟',
            questionEn: 'Who is Ruhullah (Spirit of Allah)?',
            options: ['عيسى عليه السلام', 'موسى', 'آدم', 'جبريل'],
            optionsEn: ['Isa (AS)', 'Musa', 'Adam', 'Jibril'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'عيسى عليه السلام كلمة الله وروحه.',
            explanationEn: 'Isa (AS) is Allah\'s word and spirit.'
        },
        {
            id: 41,
            question: 'كم عدد أولي العزم من الرسل؟',
            questionEn: 'How many are the Ulul-Azm (Arch-Prophets)?',
            options: ['خمسة', 'أربعة', 'ثلاثة', 'ستة'],
            optionsEn: ['Five', 'Four', 'Three', 'Six'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'هم: نوح، إبراهيم، موسى، عيسى، ومحمد عليهم الصلاة والسلام.',
            explanationEn: 'They are: Nuh, Ibrahim, Musa, Isa, and Muhammad (peace be upon them).'
        },
        {
            id: 42,
            question: 'من هو النبي الذي صام عن الكلام؟',
            questionEn: 'Who is the Prophet who fasted from speaking?',
            options: ['زكريا عليه السلام', 'يحيى', 'عيسى', 'موسى'],
            optionsEn: ['Zakariya (AS)', 'Yahya', 'Isa', 'Musa'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'كانت آيته ألا يكلم الناس ثلاثة أيام إلا رمزاً.',
            explanationEn: 'His sign was not to speak to people for three days except by gesture.'
        },
        {
            id: 43,
            question: 'ما هي معجزة موسى مع السحرة؟',
            questionEn: 'What was Musa\'s miracle with the magicians?',
            options: ['التهمت عصاه حبالهم وعصيهم', 'أحيا الموتى', 'شفى المرضى', 'أنزل المطر'],
            optionsEn: ['His staff swallowed their ropes and staffs', 'Raised dead', 'Cured sick', 'Brought rain'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'فألقى موسى عصاه فإذا هي تلقف ما يأفكون.',
            explanationEn: 'So Musa threw his staff, and behold, it swallowed what they falsified.'
        },
        {
            id: 44,
            question: 'ماذا فعل السحرة بعد رؤية معجزة موسى؟',
            questionEn: 'What did the magicians do after seeing Musa\'s miracle?',
            options: ['سجدوا لله وآمنوا', 'حاربوا موسى', 'هربوا', 'سخروا منه'],
            optionsEn: ['Prostrated to Allah and believed', 'Fought Musa', 'Ran away', 'Mocked him'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'فألقي السحرة ساجدين قالوا آمنا برب العالمين.',
            explanationEn: 'So the magicians fell down in prostration. They said, "We have believed in the Lord of the worlds."'
        },
        {
            id: 45,
            question: 'من هو قارون؟',
            questionEn: 'Who is Qarun?',
            options: ['رجل غني من قوم موسى تكبر فخسف الله به', 'ملك مصر', 'وزير فرعون', 'أخو موسى'],
            optionsEn: ['Rich man from Musa\'s people, arrogant, swallowed by earth', 'King of Egypt', 'Pharaoh\'s minister', 'Musa\'s brother'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'فخسفنا به وبداره الأرض.',
            explanationEn: 'So We caused the earth to swallow him and his home.'
        },
        {
            id: 46,
            question: 'من هو هامان؟',
            questionEn: 'Who is Haman?',
            options: ['وزير فرعون', 'أخو فرعون', 'نبي', 'ملك'],
            optionsEn: ['Pharaoh\'s minister', 'Pharaoh\'s brother', 'Prophet', 'King'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'هامان كان وزير فرعون ومساعده في الظلم.',
            explanationEn: 'Haman was Pharaoh\'s minister and helper in oppression.'
        },
        {
            id: 47,
            question: 'ما هي القوارير التي بناها سليمان؟',
            questionEn: 'What is the glass palace built by Sulaiman?',
            options: ['صرح ممرد من قوارير (زجاج)', 'قصر من ذهب', 'قصر من خشب', 'قصر من طين'],
            optionsEn: ['Paved palace of glass', 'Gold palace', 'Wood palace', 'Mud palace'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'حسبته لجة وكشفت عن ساقيها، قال إنه صرح ممرد من قوارير.',
            explanationEn: 'She thought it was a body of water and uncovered her shins. He said, "It is a palace paved with glass."'
        },
        {
            id: 48,
            question: 'ماذا حدث لبلقيس ملكة سبأ؟',
            questionEn: 'What happened to Bilqis, Queen of Sheba?',
            options: ['أسلمت وتزوجت سليمان (في بعض الروايات)', 'قتلت', 'هربت', 'بقيت كافرة'],
            optionsEn: ['Accepted Islam and married Sulaiman (some narrations)', 'Killed', 'Escaped', 'Remained disbeliever'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'قالت أسلمت مع سليمان لله رب العالمين.',
            explanationEn: 'She said, "I submit with Sulaiman to Allah, Lord of the worlds."'
        },
        {
            id: 49,
            question: 'كيف مات سليمان عليه السلام؟',
            questionEn: 'How did Sulaiman (AS) die?',
            options: ['وهو متكئ على عصاه', 'في المعركة', 'في سريره', 'غرقاً'],
            optionsEn: ['Leaning on his staff', 'In battle', 'In bed', 'Drowning'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'مات ولم يعلم الجن بموته حتى أكلت دابة الأرض عصاه.',
            explanationEn: 'He died and the Jinn didn\'t know until a termite ate his staff.'
        },
        {
            id: 50,
            question: 'من هو النبي الذي تكفل بمريم؟',
            questionEn: 'Who is the Prophet who took charge of Maryam?',
            options: ['زكريا عليه السلام', 'يحيى', 'عيسى', 'موسى'],
            optionsEn: ['Zakariya (AS)', 'Yahya', 'Isa', 'Musa'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'كفلها زوج خالتها زكريا عليه السلام.',
            explanationEn: 'Her aunt\'s husband Zakariya (AS) took charge of her.'
        },
        {
            id: 51,
            question: 'ماذا وجد زكريا عند مريم كلما دخل عليها المحراب؟',
            questionEn: 'What did Zakariya find with Maryam whenever he entered the sanctuary?',
            options: ['رزقاً (فاكهة الصيف في الشتاء والعكس)', 'نقوداً', 'ملابس', 'كتباً'],
            optionsEn: ['Provision (summer fruit in winter & vice versa)', 'Money', 'Clothes', 'Books'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'وجد عندها رزقاً، قال يا مريم أنى لك هذا.',
            explanationEn: 'He found with her provision. He said, "O Maryam, from where is this to you?"'
        },
        {
            id: 52,
            question: 'من هو النبي الذي قتله بنو إسرائيل وقدموا رأسه مهراً لبغي؟',
            questionEn: 'Who is the Prophet killed by Bani Israel and his head given as dowry?',
            options: ['يحيى عليه السلام', 'زكريا', 'عيسى', 'موسى'],
            optionsEn: ['Yahya (AS)', 'Zakariya', 'Isa', 'Musa'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'قتل يحيى عليه السلام ظلماً وعدواناً.',
            explanationEn: 'Yahya (AS) was killed unjustly and aggressively.'
        },
        {
            id: 53,
            question: 'ما هي معجزة عيسى في الطين؟',
            questionEn: 'What was Isa\'s miracle with clay?',
            options: ['يخلق من الطين كهيئة الطير فينفخ فيه فيكون طيراً', 'يبني بيوتاً', 'يصنع أواني', 'لا شيء'],
            optionsEn: ['Create bird shape from clay, breathe into it, becomes bird', 'Build houses', 'Make pots', 'Nothing'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'بإذن الله كان يخلق من الطين طيراً.',
            explanationEn: 'By Allah\'s permission, he created birds from clay.'
        },
        {
            id: 54,
            question: 'هل عيسى عليه السلام إله؟',
            questionEn: 'Is Isa (AS) a god?',
            options: ['لا، هو عبد الله ورسوله', 'نعم', 'ابن الله', 'ثالث ثلاثة'],
            optionsEn: ['No, he is Allah\'s servant and messenger', 'Yes', 'Son of God', 'Third of three'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'إن هو إلا عبد أنعمنا عليه.',
            explanationEn: 'He is not but a servant upon whom We bestowed favor.'
        },
        {
            id: 55,
            question: 'متى ينزل عيسى عليه السلام مرة أخرى؟',
            questionEn: 'When will Isa (AS) descend again?',
            options: ['في آخر الزمان قبل يوم القيامة', 'نزل وانتهى', 'لن ينزل', 'بعد 100 سنة'],
            optionsEn: ['In end times before Judgment Day', 'Descended and finished', 'Will not descend', 'After 100 years'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'نزول عيسى عليه السلام من علامات الساعة الكبرى.',
            explanationEn: 'The descent of Isa (AS) is one of the major signs of the Hour.'
        },
        {
            id: 56,
            question: 'من يقتل المسيح الدجال؟',
            questionEn: 'Who will kill the Dajjal (Anti-Christ)?',
            options: ['عيسى عليه السلام', 'المهدي', 'محمد ﷺ', 'موسى'],
            optionsEn: ['Isa (AS)', 'Mahdi', 'Muhammad ﷺ', 'Musa'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'يقتله عيسى عليه السلام بباب لد.',
            explanationEn: 'Isa (AS) will kill him at the gate of Ludd.'
        },
        {
            id: 57,
            question: 'من هو النبي الذي ذكر في القرآن باسم "ذو الكفل"؟',
            questionEn: 'Who is the Prophet mentioned in Quran as "Dhul-Kifl"?',
            options: ['نبي من الصابرين', 'ابن أيوب', 'أخو يوسف', 'ملك'],
            optionsEn: ['A patient Prophet', 'Son of Ayyub', 'Brother of Yusuf', 'King'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'واذكر إسماعيل واليسع وذا الكفل وكل من الأخيار.',
            explanationEn: 'And remember Ismail, Alyasa, and Dhul-Kifl, and all are among the good.'
        },
        {
            id: 58,
            question: 'من هو النبي "اليسع"؟',
            questionEn: 'Who is the Prophet "Alyasa"?',
            options: ['نبي من بني إسرائيل', 'نبي عربي', 'ملك', 'صحابي'],
            optionsEn: ['Prophet from Bani Israel', 'Arab Prophet', 'King', 'Companion'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'ذكر في القرآن مرتين وهو من أنبياء بني إسرائيل.',
            explanationEn: 'Mentioned twice in Quran, a Prophet of Bani Israel.'
        },
        {
            id: 59,
            question: 'من هو النبي "إلياس"؟',
            questionEn: 'Who is the Prophet "Ilyas"?',
            options: ['نبي أرسل إلى قوم يعبدون "بعلاً"', 'نبي العرب', 'نبي مصر', 'نبي الهند'],
            optionsEn: ['Prophet sent to people worshipping "Ba\'l"', 'Prophet of Arabs', 'Prophet of Egypt', 'Prophet of India'],
            correctAnswer: 0,
            difficulty: 'hard',
            explanation: 'وإن إلياس لمن المرسلين، إذ قال لقومه ألا تتقون، أتدعون بعلاً.',
            explanationEn: 'And indeed, Ilyas was from the messengers, when he said to his people, "Will you not fear Allah? Do you call upon Ba\'l?"'
        },
        {
            id: 60,
            question: 'كم عدد الأنبياء والرسل المذكورين في القرآن؟',
            questionEn: 'How many Prophets and Messengers are mentioned in Quran?',
            options: ['25', '100', '5', '10'],
            optionsEn: ['25', '100', '5', '10'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'ذكر في القرآن 25 نبياً ورسولاً.',
            explanationEn: '25 Prophets and Messengers are mentioned in the Quran.'
        },
        {
            id: 61,
            question: 'من هو خاتم الأنبياء؟',
            questionEn: 'Who is the Seal of Prophets?',
            options: ['محمد ﷺ', 'عيسى', 'موسى', 'إبراهيم'],
            optionsEn: ['Muhammad ﷺ', 'Isa', 'Musa', 'Ibrahim'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'ما كان محمد أبا أحد من رجالكم ولكن رسول الله وخاتم النبيين.',
            explanationEn: 'Muhammad is not the father of [any] one of your men, but [he is] the Messenger of Allah and last of the prophets.'
        },
        {
            id: 62,
            question: 'ما هي السورة التي سميت باسم امرأة؟',
            questionEn: 'Which Surah is named after a woman?',
            options: ['سورة مريم', 'سورة النساء', 'سورة المجادلة', 'سورة النور'],
            optionsEn: ['Surah Maryam', 'Surah An-Nisa', 'Surah Al-Mujadila', 'Surah An-Nur'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'سورة مريم هي السورة الوحيدة باسم امرأة.',
            explanationEn: 'Surah Maryam is the only Surah named after a woman.'
        },
        {
            id: 63,
            question: 'ما هي السورة التي قصت قصة يوسف كاملة؟',
            questionEn: 'Which Surah told the story of Yusuf completely?',
            options: ['سورة يوسف', 'سورة القصص', 'سورة الأنبياء', 'سورة طه'],
            optionsEn: ['Surah Yusuf', 'Surah Al-Qasas', 'Surah Al-Anbiya', 'Surah Taha'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'سورة يوسف ذكرت القصة كاملة في سورة واحدة.',
            explanationEn: 'Surah Yusuf mentioned the complete story in one Surah.'
        },
        {
            id: 64,
            question: 'من هو النبي الذي كلمه الله عند الشجرة المباركة؟',
            questionEn: 'Who is the Prophet Allah spoke to at the blessed tree?',
            options: ['موسى عليه السلام', 'إبراهيم', 'محمد ﷺ', 'عيسى'],
            optionsEn: ['Musa (AS)', 'Ibrahim', 'Muhammad ﷺ', 'Isa'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'نودي من شاطئ الوادي الأيمن في البقعة المباركة من الشجرة.',
            explanationEn: 'He was called from the right side of the valley in the blessed spot - from the tree.'
        },
        {
            id: 65,
            question: 'ما هي "العصا" في قصص الأنبياء؟',
            questionEn: 'What is the "Staff" in Prophets stories?',
            options: ['معجزة موسى عليه السلام', 'سلاح داود', 'سفينة نوح', 'ناقة صالح'],
            optionsEn: ['Miracle of Musa (AS)', 'Weapon of Dawud', 'Ark of Nuh', 'She-camel of Saleh'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'العصا كانت معجزة موسى الكبرى.',
            explanationEn: 'The staff was Musa\'s major miracle.'
        },
        {
            id: 66,
            question: 'من هو النبي الذي كان أبوه آزر يصنع الأصنام؟',
            questionEn: 'Who is the Prophet whose father Azar made idols?',
            options: ['إبراهيم عليه السلام', 'نوح', 'موسى', 'لوط'],
            optionsEn: ['Ibrahim (AS)', 'Nuh', 'Musa', 'Lut'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'وإذ قال إبراهيم لأبيه آزر أتتخذ أصناماً آلهة.',
            explanationEn: 'And when Ibrahim said to his father Azar, "Do you take idols as deities?"'
        },
        {
            id: 67,
            question: 'من هو النبي الذي كانت زوجته كافرة؟',
            questionEn: 'Who is the Prophet whose wife was a disbeliever?',
            options: ['نوح ولوط عليهما السلام', 'إبراهيم', 'موسى', 'محمد ﷺ'],
            optionsEn: ['Nuh and Lut (AS)', 'Ibrahim', 'Musa', 'Muhammad ﷺ'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'ضرب الله مثلاً للذين كفروا امرأة نوح وامرأة لوط.',
            explanationEn: 'Allah presents an example of those who disbelieved: the wife of Noah and the wife of Lot.'
        },
        {
            id: 68,
            question: 'من هو النبي الذي كانت امرأته حمالة الحطب؟',
            questionEn: 'Who is the Prophet whose uncle\'s wife was the wood carrier?',
            options: ['ليس نبياً، بل عم النبي محمد (أبو لهب)', 'لوط', 'نوح', 'أيوب'],
            optionsEn: ['Not a Prophet, but uncle of Muhammad (Abu Lahab)', 'Lut', 'Nuh', 'Ayyub'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'وامرأته حمالة الحطب (زوجة أبي لهب).',
            explanationEn: 'And his wife, the carrier of firewood (Abu Lahab\'s wife).'
        },
        {
            id: 69,
            question: 'من هو النبي الذي دعا ربه "أني مسني الضر"؟',
            questionEn: 'Who is the Prophet who prayed "Adversity has touched me"?',
            options: ['أيوب عليه السلام', 'يونس', 'يعقوب', 'موسى'],
            optionsEn: ['Ayyub (AS)', 'Yunus', 'Yaqub', 'Musa'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'وأيوب إذ نادى ربه أني مسني الضر وأنت أرحم الراحمين.',
            explanationEn: 'And Ayyub, when he called to his Lord, "Indeed, adversity has touched me, and You are the Most Merciful of the merciful."'
        },
        {
            id: 70,
            question: 'من هو النبي الذي دعا ربه "رب لا تذرني فرداً"؟',
            questionEn: 'Who is the Prophet who prayed "My Lord, do not leave me alone"?',
            options: ['زكريا عليه السلام', 'إبراهيم', 'نوح', 'موسى'],
            optionsEn: ['Zakariya (AS)', 'Ibrahim', 'Nuh', 'Musa'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'وزكريا إذ نادى ربه رب لا تذرني فرداً وأنت خير الوارثين.',
            explanationEn: 'And Zakariya, when he called to his Lord, "My Lord, do not leave me alone [with no heir], while You are the best of inheritors."'
        },
        {
            id: 71,
            question: 'من هو النبي الذي سخرت له الجبال يسبحن معه؟',
            questionEn: 'Who is the Prophet for whom mountains were subjected to praise?',
            options: ['داود عليه السلام', 'سليمان', 'موسى', 'محمد ﷺ'],
            optionsEn: ['Dawud (AS)', 'Sulaiman', 'Musa', 'Muhammad ﷺ'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'وسخرنا مع داود الجبال يسبحن والطير.',
            explanationEn: 'And We subjected the mountains to praise with Dawud, and the birds.'
        },
        {
            id: 72,
            question: 'من هو النبي الذي كان يأكل من عمل يده؟',
            questionEn: 'Who is the Prophet who used to eat from the work of his hand?',
            options: ['داود عليه السلام', 'سليمان', 'يوسف', 'عيسى'],
            optionsEn: ['Dawud (AS)', 'Sulaiman', 'Yusuf', 'Isa'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'كان داود يأكل من عمل يده (الحدادة).',
            explanationEn: 'Dawud used to eat from the work of his hand (blacksmithing).'
        },
        {
            id: 73,
            question: 'من هو النبي الذي أوتي الحكمة وفصل الخطاب؟',
            questionEn: 'Who is the Prophet given wisdom and decisive speech?',
            options: ['داود عليه السلام', 'سليمان', 'لقمان', 'موسى'],
            optionsEn: ['Dawud (AS)', 'Sulaiman', 'Luqman', 'Musa'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'وآتيناه الحكمة وفصل الخطاب.',
            explanationEn: 'And We gave him wisdom and decisive speech.'
        },
        {
            id: 74,
            question: 'من هو النبي الذي كان له ملك لا ينبغي لأحد من بعده؟',
            questionEn: 'Who is the Prophet who had a kingdom not befitting anyone after him?',
            options: ['سليمان عليه السلام', 'داود', 'يوسف', 'ذو القرنين'],
            optionsEn: ['Sulaiman (AS)', 'Dawud', 'Yusuf', 'Dhul-Qarnayn'],
            correctAnswer: 0,
            difficulty: 'easy',
            explanation: 'رب اغفر لي وهب لي ملكاً لا ينبغي لأحد من بعدي.',
            explanationEn: 'My Lord, forgive me and grant me a kingdom such as will not belong to anyone after me.'
        },
        {
            id: 75,
            question: 'من هو النبي الذي بشر بالنبي محمد ﷺ باسم "أحمد"؟',
            questionEn: 'Who is the Prophet who gave glad tidings of Muhammad ﷺ as "Ahmad"?',
            options: ['عيسى عليه السلام', 'موسى', 'إبراهيم', 'نوح'],
            optionsEn: ['Isa (AS)', 'Musa', 'Ibrahim', 'Nuh'],
            correctAnswer: 0,
            difficulty: 'medium',
            explanation: 'ومبشراً برسول يأتي من بعدي اسمه أحمد.',
            explanationEn: 'And bringing good tidings of a messenger to come after me, whose name is Ahmad.'
        }
    ]
};
